import type { NextStep } from "../../lib/handbook/schema.ts";

export const NEXT_V02: NextStep[] = [
  {
    id: "ns-v02-live-reprobe",
    title: "Operator SSH re-probe of live deployed SHAs",
    impact: "high",
    urgency: "now",
    confidence: "incomplete",
    dependency: "Operator SSH to the current host. Still blocked from this campaign. docs/scripts/operator-reprobe.sh",
    scope: "small",
    doNow: true,
    body: "The only way to close Law 6 live SHA / scheduler / backup cells as of 2026-09-14. COM-001 historical proofs are not a substitute. Do not restart services to inspect them. Do not fill liveDeployedSha from GitHub HEAD.",
  },
  {
    id: "ns-v02-quartermaster-inspect",
    title: "Inspect local Quartermaster on the Windows path",
    impact: "medium",
    urgency: "soon",
    confidence: "incomplete",
    dependency: "Windows path C:\\Users\\anil\\Desktop\\Quartermaster Clank. Not reachable from this campaign.",
    scope: "small",
    doNow: false,
    body: "Census lists it PROBABLE, local-only, wrapper around token-stats, no GitHub remote. Nested token-stats was already observed as dirty git (31 August commit, four files). Record whether Quartermaster has its own git besides that nested checkout, and that it does not score fleet health. Do not invent a GitHub repo. Do not copy the token-stats SHA as Quartermaster HEAD.",
  },
  {
    id: "ns-v02-cvc-local",
    title: "Diff local CVC against GitHub 5328a3c if the desktop checkout is ahead",
    impact: "medium",
    urgency: "soon",
    confidence: "inferred",
    dependency: "Windows path C:\\Users\\anil\\Desktop\\CVC Clank (census: dubious ownership / NEEDS_RECONSTRUCTION). GitHub main is 5328a3c.",
    scope: "small",
    doNow: false,
    body: "Local CVC may be ahead of published GitHub. Inspect read-only; do not merge observer PRs as current architecture. Frozen corpus stays frozen.",
  },
  {
    id: "ns-v02-ledger-main",
    title: "Operator decision: give Clank Ledger a main, or keep the Jules branch as the named default",
    impact: "medium",
    urgency: "later",
    confidence: "verified",
    dependency: "anil-ganti-nbc/clank-ledger default branch is jules-m0-foundation-9044736841197359665 at 2c31787. No main.",
    scope: "small",
    doNow: false,
    body: "Do not treat the Jules branch as main. Creating main, renaming the default, or leaving NO-MAIN explicit is an operator decision. Teaching must keep originMain as NO-MAIN until that decision lands.",
  },
  {
    id: "ns-v02-dau-separate",
    title: "Keep Handbook v0.2 out of DAU mastery",
    impact: "low",
    urgency: "later",
    confidence: "verified",
    dependency: "DAU is a separate app. Practice Labs ?practice= already exists.",
    scope: "small",
    doNow: false,
    body: "Do not fold Handbook into DAU. Do not assign mastery, SRS, or course completion here. v0.2 teaching surfaces stay historical-evidence literacy, not a DAU world.",
  },
];

export const DO_NOT_V02: string[] = [
  "Do not fill liveDeployedSha from COM-001 historical proofs.",
  "Do not treat Jules Ledger branch as main.",
  "Do not invent a Quartermaster GitHub repo.",
  "Do not count Reddit as a Clank.",
  "Do not merge CVC observer PRs as current architecture.",
  "Do not implement M5.",
  "Do not assign mastery in the Handbook.",
  "Do not collapse ClankOps into Motherclank.",
];
