import type { Responsibility } from "../../lib/handbook/schema.ts";

const AS_OF = "2026-09-14";

export const RESPONSIBILITIES: Responsibility[] = [
  {
    id: "resp-participants",
    name: "Participant Clanks",
    layer: "participant",
    ownsQuestion: "What did this domain's sources actually contain, and what did we record in our own SQLite?",
    ownsState: "Per-Clank observational SQLite, parsers, soaks, QC queues, and domain sources.",
    observes: "Brand / wire / catalogue surfaces named in that Clank's charter.",
    doesNotOwn:
      "Fleet membership, Fleet Laws text, development missions, editorial HIT/MISS, model quota, or frozen evidence packages.",
    handsOffTo:
      "Diagnostic adapters (read-only), Motherclank harvest (photocopy), Ledger (human usefulness), Standards (conformance facts).",
    forbidden:
      "Must not speak for the fleet, self-ratify a standard, or treat a second checkout as a second identity. Must not count Reddit as a sibling Clank.",
    relatedFleetIds: [
      "watch-clank",
      "smartwatch-clank",
      "smartphone-clank",
      "feature-phone-clank",
      "tablet-clank",
      "oem-radar",
      "free-game-tracker",
      "chinese-tech-wire",
      "korean-tech-wire",
      "semiconductor-intelligence",
    ],
    conceptIds: ["collector", "sqlite-authoritative", "system-identity", "authoritative-state"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-diagnostic",
    name: "Diagnostic Clank",
    layer: "observation",
    ownsQuestion: "Which identities exist, on which host, at which inventory SHA, in which adapter language?",
    ownsState: "fleet.yaml membership registry, adapters, DiagnosticBench, Agent Inbox.",
    observes: "Declared Clank instances and adapter-readable state. Census later reconstructs folders; Diagnostic owns the registry.",
    doesNotOwn: "Harvest clock, Fleet Laws ratification, development missions, or production collector DBs.",
    handsOffTo: "Motherclank consumes adapters unchanged. ClankOps census is a reconstructed folder scan, not a second registry.",
    forbidden:
      "Must not become Motherclank. A directory listing is not a fleet (L-FLEET-001). Live Diagnostic deploy SHA stays UNKNOWN.",
    relatedFleetIds: ["diagnostic-clank"],
    conceptIds: ["diagnostic-clank", "source-adapter", "census-identity", "contract"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-motherclank",
    name: "Motherclank",
    layer: "observation",
    ownsQuestion: "What was last observed running in the fleet, honestly, including UNKNOWN?",
    ownsState: "Derived harvest snapshots (var/ JSONL + Markdown). Disposable. Clank SQLite untouched.",
    observes: "Diagnostic adapters on a clock: liveness, dual-plane health, named gaps including MATERIALIZATION_GAP.",
    doesNotOwn:
      "Remediation, deployment, development missions, ratification, editorial usefulness, or model quota. M5 is forbidden.",
    handsOffTo: "M3 recommendations may land in Diagnostic Agent Inbox. Humans decide. ClankOps is a different camera.",
    forbidden:
      "Must not write Clank DBs, take their locks, send alerts, or fill UNKNOWN from GitHub HEAD. Must not be collapsed into ClankOps.",
    relatedFleetIds: ["motherclank", "diagnostic-clank"],
    conceptIds: ["motherclank", "derived-state", "observability", "dual-plane-health"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-architecture",
    name: "Clank Architecture",
    layer: "governance",
    ownsQuestion: "What are the Fleet Laws, ADRs, promotion freeze, and observer-tier rules?",
    ownsState: "Governance notebook: FLEET_LAWS.md, ADRs, capability matrix, archaeology. Not a runtime.",
    observes: "Nothing live. It records doctrine. Live SHA is not its job.",
    doesNotOwn: "Collector processes, harvest timers, Standards ratification JSON, or ClankOps missions.",
    handsOffTo: "Standards may turn evidenced scars into RATIFIED STD-* files. Motherclank implements observe/propose.",
    forbidden:
      "Must not be treated as a deployer. Promotion freeze still controlling. M5 requires a future ADR.",
    relatedFleetIds: [],
    conceptIds: ["fleet-law", "promotion-gate", "invariant"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-standards",
    name: "Standards Clank",
    layer: "standards",
    ownsQuestion: "What is ratified law, and which conformance facts have been admitted against it?",
    ownsState: "Versioned STD-*.json, frozen tags, evidence indexes, operator ratification decisions.",
    observes: "Audit artefacts and source SHAs cited in conformance facts — not live hosts.",
    doesNotOwn:
      "Collector operation, scheduling, remediation authorization, or current live SHA. 7c821ea 26/26 RATIFIED is law, not a deploy.",
    handsOffTo: "Operator ratifies. Agents propose and audit. Conformance facts stay dated; they do not overwrite live UNKNOWN.",
    forbidden:
      "Agents cannot self-ratify. Tests are not the law. Historical COM-001 proofs must not be copied into liveDeployedSha.",
    relatedFleetIds: ["standards-clank"],
    conceptIds: ["standards-clank", "ratification", "normative-spec", "conformance"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-clankops",
    name: "ClankOps",
    layer: "development-control",
    ownsQuestion: "What development work is open, where did the last agent stop, and what CI/deploy evidence was recorded?",
    ownsState: "Local events + projections SQLite. Missions, sessions, checkpoints, census imports (RECONSTRUCTED).",
    observes: "Development state: git, GitHub, CI, explicit deploy captures, managed process exit (Foundation 10 / 4467c13).",
    doesNotOwn: "Fleet runtime health, Fleet Laws, ratification, editorial HIT/MISS, or model quota. No production deploy.",
    handsOffTo: "Resume packets admit a new agent; Foundation 1 handoff still closes work. Process exit is not that handoff.",
    forbidden:
      "Must not collapse into Motherclank, auto-close Sessions on process exit, invent a Clank health score, or treat census folders as extra identities.",
    relatedFleetIds: ["clankops"],
    conceptIds: ["clankops", "mission-lifecycle", "process-exit-vs-handoff", "census-identity"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-quartermaster",
    name: "Quartermaster",
    layer: "resource",
    ownsQuestion: "Which model, quota, and local token budget should this work use?",
    ownsState: "Local-only desktop wrapper (census PROBABLE). Nested token-stats observed as dirty git; Quartermaster's own current branch was not inspected this campaign.",
    observes: "Token/resource usage via token-stats substrate — not fleet health, not Clank identity.",
    doesNotOwn: "Fleet scoring, missions, ratification, observational SQLite, or a GitHub repo (there isn't one).",
    handsOffTo: "A future ClankOps link from quota spend to Missions. Not implemented.",
    forbidden:
      "Must not score fleet health. Must not be given an invented GitHub remote. token-stats is SUPPORT_COMPONENT, not Quartermaster.",
    relatedFleetIds: ["quartermaster"],
    conceptIds: ["quartermaster", "model-quota", "census-identity"],
    confidence: "incomplete",
    asOf: AS_OF,
  },
  {
    id: "resp-ledger",
    name: "Clank Ledger",
    layer: "editorial",
    ownsQuestion: "Was the thing a human actually useful? What was missed? Did anyone write?",
    ownsState: "HIT/MISS rows, QC decisions, editorial outcomes, append-only audit history. Local M0 SQLite.",
    observes: "Human judgements about Clank output. Not collector internals.",
    doesNotOwn:
      "Collector correctness, Motherclank health, Standards conformance, or ClankOps missions. Jules 2c31787 has no main.",
    handsOffTo: "External-reference seams only. No runtime imports from the other planes.",
    forbidden:
      "Must not be read as a test suite or a harvest. Do not treat the Jules branch as main. Do not fold numbers into a fleet score.",
    relatedFleetIds: ["clank-ledger"],
    conceptIds: ["clank-ledger", "editorial-usefulness", "hit-miss"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-cvc",
    name: "CVC Clank",
    layer: "evidence-validation",
    ownsQuestion: "Which frozen evidence packages exist, and what do they support?",
    ownsState: "Frozen corpus under corpus/ at GitHub 5328a3c. Operator state/ is local working state.",
    observes: "Operator-supplied packages, diagnostic reports, incident artefacts — only when explicitly ingested.",
    doesNotOwn: "Collection, scheduling, auto-ingest, Standards text, or current architecture. Unmerged observer PRs are not it.",
    handsOffTo: "Operator review, then maybe a ratification reference. Standards may later consume support grades.",
    forbidden:
      "Must not collect, remediate, or be taught from unmerged PRs. Local-ahead of 5328a3c is uninspected, not a secret canon.",
    relatedFleetIds: ["cvc-clank"],
    conceptIds: ["cvc-clank", "frozen-corpus", "evidence-package"],
    confidence: "incomplete",
    asOf: AS_OF,
  },
  {
    id: "resp-handbook",
    name: "Clank Systems Handbook",
    layer: "teaching",
    ownsQuestion: "What must a human (or a new agent) understand about this ecosystem, with UNKNOWN left visible?",
    ownsState: "TypeScript curriculum: concepts, ledger, labs, explain-it-back. Not a Clank. Not a runtime authority.",
    observes: "Git-resident artefacts and dated inventories. No SSH this campaign.",
    doesNotOwn: "Mastery, SRS, live SHA, or DAU worlds. Must not fold into DAU.",
    handsOffTo: "Practice Labs ?practice= may launch from DAU. Results do not assign Handbook completion.",
    forbidden:
      "Must not assign mastery. Must not fill UNKNOWN. Must not teach unmerged PRs as architecture. v0.1 freeze was real; v0.2 is a commissioned teaching pass, not a rewrite of v0.1 facts.",
    relatedFleetIds: [],
    conceptIds: ["operator-role", "historical-conformance", "frozen-corpus"],
    confidence: "verified",
    asOf: AS_OF,
  },
  {
    id: "resp-unified",
    name: "Unified Clank Platform",
    layer: "historical",
    ownsQuestion: "What shared runtime did early repos hope would unify the fleet?",
    ownsState: "Historical GitHub repo unified-clank-platform (first-morning, 2026-08-04). Not current architecture.",
    observes: "Nothing live. A hoped-for unification, not a supervisor that exists today.",
    doesNotOwn: "Current membership, harvest, Standards, ClankOps, or Motherclank. Diagnostic's old 'Unified' README branding is a scar.",
    handsOffTo: "The actual split: Diagnostic registry, Motherclank camera, Standards law, ClankOps development, Ledger editorial.",
    forbidden:
      "Must not be taught as the present control plane. Federated planes are the current design, not a single hierarchy under this name.",
    relatedFleetIds: ["unified-clank-platform"],
    conceptIds: ["system-identity", "contract", "diagnostic-clank"],
    confidence: "inferred",
    asOf: AS_OF,
  },
  {
    id: "resp-dau",
    name: "Dead Air University",
    layer: "teaching",
    ownsQuestion: "What should a learner master, spaced-repeat, and practise in generated worlds?",
    ownsState: "DAU curriculum, Worlds, Practice Labs handshake. Separate application from this Handbook.",
    observes: "Learner progress inside DAU. Not Clank runtime, not Handbook freeze/reveal self-rating.",
    doesNotOwn: "This Handbook's historical evidence, live SHA cells, or fleet membership.",
    handsOffTo: "May deep-link into Handbook labs via ?practice=. Must not swallow the Handbook.",
    forbidden:
      "Do not fold Handbook into DAU. Do not assign mastery in the Handbook. Native Worlds are simulated physics; Handbook labs are historical evidence.",
    relatedFleetIds: [],
    conceptIds: ["operator-role", "fixtures", "deterministic"],
    confidence: "verified",
    asOf: AS_OF,
  },
];
