import type { TimelineEvent } from "../../lib/handbook/schema.ts";

export const TIMELINE_V02: TimelineEvent[] = [
  {
    id: "t-v01-freeze",
    date: "2026-08-30",
    title: "Handbook v0.1 freeze",
    body: "v0.1 curriculum frozen at 1803f317 pending owner study. Live SHA cells stay UNKNOWN. CVC observer PR #5 is excluded from the freeze, not current architecture.",
    status: "verified",
    conceptIds: ["frozen-corpus", "operator-role", "head-vs-deployed"],
    evidenceIds: [],
    historyId: "h-v01-freeze",
    lawIds: ["law-6"],
  },
  {
    id: "t-ledger",
    date: "2026-08-31",
    title: "Clank Ledger M0 on a Jules branch",
    body: "Editorial HIT/MISS plane lands at 2c31787. Default branch is the Jules M0 branch, not main. Usefulness is not collector correctness.",
    status: "verified",
    conceptIds: ["clank-ledger", "editorial-usefulness", "hit-miss"],
    evidenceIds: [],
    historyId: "h-ledger-m0",
  },
  {
    id: "t-standards",
    date: "2026-09-05",
    title: "Standards Clank 26/26 RATIFIED",
    body: "Closure audit 7c821ea: 26 ratified standards, 0 proposed, agents cannot self-ratify. Tests guard the files; they are not the law. COM-001 historical proofs must not overwrite live UNKNOWN.",
    status: "verified",
    conceptIds: ["standards-clank", "ratification", "normative-spec", "historical-conformance"],
    evidenceIds: [],
    historyId: "h-standards-ratified",
    lawIds: ["law-6"],
  },
  {
    id: "t-reddit",
    date: "2026-09-09",
    title: "Reddit admission pilot, not a Clank",
    body: "SI a9a202a registers r/hardware as an experimental muted RSS source inside an owner Clank. Polling off; unmute-alone fails closed. Reddit is not a fleet identity.",
    status: "verified",
    conceptIds: ["reddit-admission", "source-admission", "experimental-vs-production"],
    evidenceIds: [],
    historyId: "h-reddit-pilot",
  },
  {
    id: "t-census",
    date: "2026-09-09",
    title: "ClankOps census reconstructed",
    body: "63 candidates, 8 duplicate-identity groups, source=RECONSTRUCTED. Duplicate folders are extra refs, not extra Clanks. Not live ClankOps history.",
    status: "verified",
    conceptIds: ["census-identity", "checkout-vs-identity", "clankops"],
    evidenceIds: [],
    historyId: "h-clankops-census",
  },
  {
    id: "t-clankops-f10",
    date: "2026-09-14",
    title: "ClankOps Foundation 10: process exit ≠ handoff",
    body: "4467c13 records managed agent exit as evidence. Exit 0 is not Mission completed. No production deploy. ClankOps is not Motherclank.",
    status: "verified",
    conceptIds: ["process-exit-vs-handoff", "clankops", "session-lifecycle"],
    evidenceIds: [],
    historyId: "h-clankops-f10",
  },
  {
    id: "t-handbook-v02",
    date: "2026-09-14",
    title: "Handbook v0.2 commissioned",
    body: "Teaching pass for the post-v0.1 control planes. Live host SHA remains UNKNOWN (no SSH). UNKNOWN is still information. v0.1 freeze was real.",
    status: "verified",
    conceptIds: ["operator-role", "historical-conformance", "frozen-corpus"],
    evidenceIds: [],
    historyId: "h-handbook-v02",
    lawIds: ["law-6"],
  },
];
