import type { FleetClank } from "../lib/handbook/schema.ts";

/**
 * Current-state map. asOf and staleNote are mandatory honesty.
 * Archaeology inventory was current through 2026-08-22; capability matrix
 * is a later evidence snapshot. Live host SHA/backup cells remain UNKNOWN
 * unless a later artefact re-verified them.
 */
export const FLEET: FleetClank[] = [
  {
    id: "watch-clank",
    name: "Watch Clank",
    purpose: "Editorial discovery of watch products and stories (Casio origin; Citizen/Seiko/Timex/specialists).",
    sources: "Official brand surfaces plus specialist sources; sitemap family for deltas. Region declared per collector.",
    scheduling: "Hetzner user-timers; single Discord authority; legacy crons annotated-disabled (Law 5).",
    persistence: "SQLite; collectors/parsers do not write the DB directly; pipeline persistence owns transactions. Alembic migrations.",
    host: "Hetzner production (fleet inventory RUNNING production as of 2026-08-22).",
    status: "Phase 2C read-only adapter onboarded. Human QC live. Catalogue-pass is an invocation fact after 2026-08-26.",
    limitation: "Delivery accounting not persisted (adapter reports unsupported/unknown). Host path for the production DB UNKNOWN in survivability matrix.",
    unresolved: "L-WATCH-006 region gaps OPEN. L-WATCH-003 official-but-late OPEN. Weak FIRST_SEEN class can return if a new collector infers pass quality from output size.",
    motherclank: "Observer-tier. QC dispositions ingested. scheduler_trace supported_unconfigured.",
    asOf: "2026-08-26 (QC notes) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Inspected archaeology head e982527 was not necessarily the deployed revision (inventory said f0b327a). Repo HEAD 2026-08-27 d4fda37 (exclude EXPERIMENTAL from Run All) is newer than ee3f34d QC race recovery. Re-probe host SHA before claiming current deploy. Neither commit is production evidence.",
  },
  {
    id: "smartwatch-clank",
    name: "Smartwatch Clank",
    purpose: "Connected-wearable catalogue/news observations with silent initial baseline.",
    sources: "Samsung/Google/Garmin/Apple official-news (Stage B); Garmin catalogue plus Amazfit/Zepp/COROS (Stage C).",
    scheduling: "Cron sole scheduler after systemd soak timer retired 2026-08-21T21:06Z. Policy PERIODIC on staging.",
    persistence: "SQLite volume. Restored 2026-08-23 from 2026-08-18 backup (sw-epoch-1-restored…). ACT-011 RP1 restore-verified.",
    host: "Hetzner staging. RUNNING staging in 2026-08-22 inventory.",
    status: "Events/delivery unsupported_by_policy. Continuity active with known gap. Survivability active for the recovery point only.",
    limitation: "≈3 days 13 hours of observations permanently missing. Durable off-host copy is temporary_scratch only.",
    unresolved: "Whether the pre-incident backup pipeline resumed after restore: UNKNOWN. Experimental/production scope must stay explicit (e9a897c).",
    motherclank: "Observer. INTENTIONALLY_DORMANT must not be inferred — this lane is PERIODIC.",
    asOf: "2026-08-24 (ACT-011) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Capability matrix lists baseline/run-kind unsupported_by_policy for this lane.",
  },
  {
    id: "smartphone-clank",
    name: "Smartphone Clank",
    purpose: "Evidence engine for smartphone discoveries: aliases, timeline, confidence/decay, alerts.",
    sources: "Eight-OEM soak baseline; Wave 1 Google/OnePlus/Nothing/Xiaomi isolated. Samsung traversal-success/extraction-zero is a named open case (L-SMART-001).",
    scheduling: "systemd timers. systemd-only cutover is the Law 5 reference.",
    persistence: "SQLite at /opt/smartphone-clank/data (survivability inventory). Alembic revision exposed by adapter.",
    host: "Hetzner production. Inventory RUNNING production at b8b8988 while repo later added QC writer 10d5222.",
    status: "Phase 2C adapter. Delivery active. QC writer added. Law 2 novelty debt on catalogue-inventory sources remains OPEN.",
    limitation: "HTTP/traversal success is not extraction success. Dual baseline authority is a risk.",
    unresolved: "L-SMART-001 root cause explicitly unknown. Motherclank must not recompute alias/family/decay.",
    motherclank: "Observer. DEF-M1.5 UUID-order false-STALE fixed in diagnostic-clank 97b07ae.",
    asOf: "2026-08-22 inventory + 2026-08-22 DEF-M1.5 closure",
    confidence: "verified",
    staleNote: "Production SHA vs repo HEAD disagreement recorded in archaeology; treat deployed SHA as UNKNOWN until re-probed.",
  },
  {
    id: "feature-phone-clank",
    name: "Feature Phone Clank",
    purpose: "HMD/Nokia (and isolated itel/Lava experimental) change-detection.",
    sources: "HMD listings/sitemap; experimental itel/Lava on separate runners/volumes.",
    scheduling: "Production cron (repaired after materialization gap). Experimental lanes isolated (Law 5 exception: disjoint DB+lock+volume).",
    persistence: "Recreated volume after 2026-08-23 loss. Epoch fpc-epoch-2 begins 2026-08-23T21:36:11Z. ACT-011 first RP restore-verified. Pre-incident history irrecoverable.",
    host: "Hetzner. Inventory: production plus separate experimental lanes.",
    status: "Events active. Delivery supported_undeployed (code capable, not on deployed revision at snapshot). QC unknown_or_unverified.",
    limitation: "L-PHONE-001: automated success ≠ owner launcher acceptance. Inventory pinned production to c749df3 before later notification changes.",
    unresolved: "Durable off-host NO. HMD ReadTimeout after repair is ordinary source failure, not epoch loss.",
    motherclank: "Observer. Continuity active (fpc-epoch-2).",
    asOf: "2026-08-24 (ACT-011); repo last push 2026-08-27",
    confidence: "verified",
  },
  {
    id: "tablet-clank",
    name: "Tablet Clank",
    purpose: "First-party tablet catalogue changes. No production members, no alerts by original design.",
    sources: "Apple/Samsung/Honor/TCL experimental. Apple sitemap blocked/retired (bb0115c) — must not become 'no tablets found.'",
    scheduling: "None by design after finite soak. Promotion Wave 1 moved Honor/TCL to a manual/on-demand production allowlist. Stale tablet-clank-soak.service must yield INTENTIONALLY_DORMANT, never MISSING_RUN.",
    persistence: "var/tablet_clank.db, negligible. Class EPHEMERAL→RECONSTRUCTABLE.",
    host: "Disabled experimental checkout in 2026-08-22 inventory.",
    status: "Intentionally dormant. Membership must come from manifest, not directory sweep (L-FLEET-001).",
    limitation: "Stale source freshness, no scheduler/notification, unknown backup.",
    unresolved: "Wider onboarding blocked until fresh baseline plus scheduler, backup, and source-health evidence.",
    motherclank: "Observer only if registered. Policy=RETIRED in expectations seed.",
    asOf: "2026-08-27 (repo QC/Windows launcher) / 2026-08-24 (impact-map Tablet correction)",
    confidence: "verified",
    staleNote: "Repo HEAD 2026-08-27 (a41d1e7) adds QC archive, Windows launcher, honor_uk_tablets experimental. 2026-08-22 inventory still said disabled/INTENTIONALLY_DORMANT. Live host membership UNKNOWN — do not treat HEAD as production.",
  },
  {
    id: "korean-tech-wire",
    name: "Korean Tech Wire",
    purpose: "Korean-language technology collection with per-source lifecycle. No alert integration by policy.",
    sources: "Samsung, The Elec, SK hynix, LG Display, ETNews. The Elec/ETNews promoted on evidence (379d3c2). SK hynix RSS 403 from Hetzner since 2026-08-10 (host block, not parser defect).",
    scheduling: "cron/timer; per-source due-gating and failure backoff (afe158e, 45e6ec4). Law 8 reference implementation.",
    persistence: "/opt/korean-tech-wire/var SQLite. Backup UNKNOWN.",
    host: "Hetzner staging. RUNNING staging in inventory. Phase 2C adapter.",
    status: "Events/delivery unsupported_by_policy. QC active (feedback writes take RunLock as of 6e95c29 / M4.5-ACT).",
    limitation: "HEALTHY-iff-ever-succeeded was a Law 3 violator; adapter must not display blocked streaks as healthy by history.",
    unresolved: "Host checkout trailing branch tip recorded as Law 9 first violation (healed on GitHub by merge; host may still trail).",
    motherclank: "Observer. Delivery values must remain unsupported, not zero.",
    asOf: "2026-08-22 inventory + Law 8 reference; repo last push 2026-08-27",
    confidence: "verified",
    staleNote: "Deployed SHA vs main: do not assume convergence without host evidence.",
  },
  {
    id: "chinese-tech-wire",
    name: "Chinese Tech Wire",
    purpose: "Chinese technology discovery (ITHome, MyDrivers, Expreview, ZOL, Jiwei) with original-Chinese preservation.",
    sources: "V0.1 set as above. Blocked regulatory/Geekbench monitoring is unsupported/disabled, not a silent empty source.",
    scheduling: "Hourly cron per dogfood scorecard; final live confirmation LIVE_EVIDENCE_REQUIRED.",
    persistence: "data/ctw.db (registry). Dogfood: checkout-relative refresh path was guessed and never existed — live store was a differently-named Docker volume.",
    host: "Hetzner staging. Inventory RUNNING staging; no host notification authority found.",
    status: "v0.3 observer onboarded 2026-08-24 with dogfood scorecard. Product code can support Discord; runtime capability must win.",
    limitation: "Historical secret scanning / credential rotation remain operator-required. Soak observer PENDING after deploy.",
    unresolved: "Live-state validation and human review of the transfer were still pending in the scorecard.",
    motherclank: "Observer. Zero Motherclank core participant-specific lines. Layer-tagged health is an adapter convention.",
    asOf: "2026-08-25 (ONBOARDING.md cross-check commit); repo last push 2026-08-27",
    confidence: "verified",
    staleNote: "Scheduler authority step scored LIVE_EVIDENCE_REQUIRED — do not claim a verified live cron without host probe.",
  },
  {
    id: "oem-radar",
    name: "OEM Radar",
    purpose: "Boutique PC OEM product intelligence: immutable snapshots, semantic diff, Discord via outbox. Mission: spot new hardware before mainstream media.",
    sources: "Source (platform engine + YAML) is the extension unit, not OEM-specific code. Dell US disabled for persistent 403. Experimental Lenovo/ASUS/Beelink lanes.",
    scheduling: "Stateless one-shot CLI scheduled by OS (ADR-1). Cron repaired after materialization gap. Dashboard auto-crawl later fail-closed (4e585ac) so the GUI is not a second scheduler.",
    persistence: "SQLite WAL, append-only content-hash snapshots. Continuity CONTIGUOUS (no volume loss). Backup UNKNOWN.",
    host: "Hetzner staging plus isolated experimental lane. Inventory RUNNING staging.",
    status: "Events/delivery/QC active in capability matrix. BANKAI recall remains the mission-level scar.",
    limitation: "L-OEM-001 first fire mistaken for hourly cadence (actually daily). L-OEM-003 operational health ≠ newsroom recall. L-OEM-004 Beelink miss: UNKNOWN, do not invent parser fault.",
    unresolved: "Dashboard historically shared prod webhook authority (Law 5 open at codification). Promotion records missing until Phase 2A.",
    motherclank: "Observer. Reference for snapshots/outbox, not a shared library.",
    asOf: "2026-08-22 inventory + 2026-08-24 continuity (CONTIGUOUS)",
    confidence: "verified",
  },
  {
    id: "free-game-tracker",
    name: "Free Game Tracker (Newsroom)",
    purpose: "Detect newly free PC games (Epic, Steam 100%-off, GOG, GamerPower). Facts separate from editorial judgment.",
    sources: "Store catalogues plus GamerPower aggregator. Subscription-entitlement path is a different coverage axis (L-FGT-001 Helldivers 2/PS Plus miss, root cause unknown).",
    scheduling: "Hourly cron on Hetzner production. Windows Task Scheduler leftover must not share the production webhook (dual-host risk).",
    persistence: "Container volume is production. Repository-directory newsroom.db is a stale legacy copy (inventory warning). Backup scripts exist; whether they are scheduled is UNKNOWN.",
    host: "Hetzner production. Inventory RUNNING production.",
    status: "Capability matrix: collection/health/events active-by-code-evidence; REAL_STATE_VALIDATION BLOCKED until live read-only copy. Delivery log-only. QC unsupported.",
    limitation: "Law 1 violator at codification (fresh-DB notifies all). Law 7 specimen: /api/run threading.Lock bypass, DB Eradication. 840641f: logs swallowed after DB init.",
    unresolved: "Discord webhook rotation AUTHORIZED, BLOCKED-ON-OPERATOR. FGT registry filename drift caught during CTW dogfood.",
    motherclank: "Observer onboarding tests exist (FGT-G1..G10). Do not treat local checkout DB as production truth.",
    asOf: "2026-08-21 last push / 2026-08-24 capability matrix",
    confidence: "verified",
    staleNote: "Pushed_at 2026-08-21 — older than several other Clanks. Re-verify before claiming current production behaviour.",
  },
  {
    id: "semiconductor-intelligence",
    name: "Semiconductor Intelligence",
    purpose: "Claims-and-evidence research tool. Atomic unit is a claim, not an article.",
    sources: "Deterministic source plugins, Signal Radar import (preview-first; derived legacy data not trusted).",
    scheduling: "OperationalScheduler is the intended path. Inventory residual: hourly cron invoked pipeline run directly (Laws 3/5). Repo head is not proof the host changed.",
    persistence: "semintel_staging_data SQLite/alembic. Backup UNKNOWN.",
    host: "Hetzner staging. RUNNING staging.",
    status: "v0.3 observer dogfood 2026-08-25. intelligence_assertion@1 evidence type seeded. Scheduler residual explicitly open.",
    limitation: "Broken Task Scheduler action meant collection was not unattended until d43481f. Law 6 specimen: d43481f claim-vs-ledger contradiction.",
    unresolved: "Windows UNKNOWN state. Do not automatically promote imported derived legacy data.",
    motherclank: "Observer. Distinct subject model (claims), not article events.",
    asOf: "2026-08-25 SI dogfood / 2026-08-22 inventory",
    confidence: "verified",
    staleNote: "Last push 2026-08-22. Live scheduler path requires host corroboration.",
  },
  {
    id: "motherclank",
    name: "Motherclank",
    purpose: "Read-only fleet harvester/supervisor (ADR-0002). Observe, reason, propose — never remediate in M0–M4.",
    sources: "Diagnostic-Clank-owned adapters, consumed unchanged. Inventory: fleet.yaml.",
    scheduling: "ONE fixed-clock systemd user timer. host-harvest.sh refreshes read-only copies then harvests.",
    persistence: "Append-only dated JSONL snapshots + derived Markdown. Disposable. Clank DBs untouched.",
    host: "Hetzner user service (documented). Rollback = disable timer, delete snapshots.",
    status: "M0–M4 implemented with golden corpus, continuity, liveness, survivability derivation, closeout v1 (2026-08-26 inputs). M5 excluded.",
    limitation: "Cannot see what adapters cannot read. Missing host var/ artefacts blocked row-level confirmation of 22–23 Aug batches.",
    unresolved: "M5 requires future ADR with authn/fencing/authorization/rollback. Durable off-host observation of backups still OPEN.",
    motherclank: "This row is the supervisor.",
    asOf: "2026-08-26 closeout inputs / 2026-08-26 last push",
    confidence: "verified",
  },
  {
    id: "diagnostic-clank",
    name: "Diagnostic Clank",
    purpose: "Read-only diagnostics, Agent Output Inbox, fleet inventory, adapter plane. Not Motherclank.",
    sources: "Report ingestion, DiagnosticBench cases, fleet.yaml, adapters per Clank.",
    scheduling: "Not a collector scheduler. Prototype control plane; promotion frozen.",
    persistence: "Own diagnostic.db (Watch corpus extracted from owner-supplied zip). Does not own Clank SQLite.",
    host: "Default branch diagnostic-clank-2026-08 (not main). Last push 2026-08-26.",
    status: "Owns adapters Motherclank consumes. ADR-0001 inventory owner. Agent Inbox may receive M3 recommendations (ADR-0003).",
    limitation: "README still branded 'Unified Clank Platform' / Stage 1A — historical naming. No production behaviour authorized.",
    unresolved: "Cross-Clank identity ADR still blocking participant profile. Fresh host verification of fleet.yaml still required for live claims.",
    motherclank: "Sibling: adapters-src. Motherclank is consumer, not successor.",
    asOf: "2026-08-26",
    confidence: "verified",
    staleNote: "README status banner may lag the adapter work on the 2026-08 branch.",
  },
];
