import type { FleetClank } from "../lib/handbook/schema.ts";

/**
 * Current-state map. asOf and staleNote are mandatory honesty.
 * Archaeology inventory was current through 2026-08-22; capability matrix
 * is a later evidence snapshot. Live host SHA/backup cells remain UNKNOWN
 * unless a later artefact re-verified them.
 *
 * Three SHA columns are the teaching point:
 *   inventorySha  = fleet.yaml deployed_commit_sha as_of 2026-08-22T22:30:00Z
 *   repoHead      = GitHub default-branch HEAD as of this teaching capture
 *   liveDeployedSha = always UNKNOWN until a live host probe
 * GitHub HEAD is not production. Do not fill liveDeployedSha from repoHead.
 */
const INVENTORY_AS_OF = "2026-08-22T22:30:00Z";
const REPO_HEAD_AS_OF = "2026-08-27T18:00Z";
const LIVE_UNKNOWN = "UNKNOWN";
const HEAD_NOTE =
  "GitHub default-branch HEAD captured 2026-08-27 via the GitHub API for this teaching pass. Not a host checkout. Not a running image. Not production.";

export const FLEET: FleetClank[] = [
  {
    id: "watch-clank",
    name: "Watch Clank",
    purpose: "Editorial discovery of watch products and stories (Casio origin; Citizen/Seiko/Timex/specialists).",
    sources: "Official brand surfaces plus specialist sources; sitemap family for deltas. Region declared per collector.",
    scheduling: "Hetzner user-timers; single Discord authority; legacy crons annotated-disabled (Law 5).",
    persistence: "SQLite; collectors/parsers do not write the DB directly; pipeline persistence owns transactions. Alembic migrations.",
    host: "Hetzner production (fleet inventory RUNNING production as of 2026-08-22).",
    status: "Phase 2C read-only adapter onboarded. Human QC live. Catalogue-pass is an invocation fact after 2026-08-26.",
    limitation: "Delivery accounting not persisted (adapter reports unsupported/unknown). Host path for the production DB UNKNOWN in survivability matrix.",
    unresolved: "L-WATCH-006 region gaps OPEN. L-WATCH-003 official-but-late OPEN. Weak FIRST_SEEN class can return if a new collector infers pass quality from output size.",
    motherclank: "Observer-tier. QC dispositions ingested. scheduler_trace supported_unconfigured.",
    asOf: "2026-08-26 (QC notes) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote:
      "Inspected archaeology head e982527 was not necessarily the deployed revision (inventory said f0b327a). Repo HEAD 2026-08-27 9d812ed (Windows frozen-exe project_root) is newer than d4fda37 and ee3f34d. Re-probe host SHA before claiming current deploy. Neither commit is production evidence.",
    inventorySha: "f0b327acc9970221de230c68d4bc03480d853a46",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance watch-hetzner-user-timers-01, environment production, image watch-clank:f0b327a. Database path UNKNOWN-host-path-under-anilganti.",
    repoHead: "9d812ed4e4cb2acdd01b0107cd9558be18e1346a",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "smartwatch-clank",
    name: "Smartwatch Clank",
    purpose: "Connected-wearable catalogue/news observations with silent initial baseline.",
    sources: "Samsung/Google/Garmin/Apple official-news (Stage B); Garmin catalogue plus Amazfit/Zepp/COROS (Stage C).",
    scheduling: "Cron sole scheduler after systemd soak timer retired 2026-08-21T21:06Z. Policy PERIODIC on staging.",
    persistence: "SQLite volume. Restored 2026-08-23 from 2026-08-18 backup (sw-epoch-1-restored…). ACT-011 RP1 restore-verified.",
    host: "Hetzner staging. RUNNING staging in 2026-08-22 inventory.",
    status: "Events/delivery unsupported_by_policy. Continuity active with known gap. Survivability active for the recovery point only.",
    limitation: "≈3 days 13 hours of observations permanently missing. Durable off-host copy is temporary_scratch only.",
    unresolved: "Whether the pre-incident backup pipeline resumed after restore: UNKNOWN. Experimental/production scope must stay explicit (e9a897c).",
    motherclank: "Observer. INTENTIONALLY_DORMANT must not be inferred — this lane is PERIODIC.",
    asOf: "2026-08-24 (ACT-011) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote:
      "Capability matrix lists baseline/run-kind unsupported_by_policy for this lane. Repo HEAD a717977 is a Windows PyInstaller spec — not evidence the restored volume is still on the host.",
    inventorySha: "d987b66ad3b6f96575ddf1c04f8a76833a837026",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Cron lane RUNNING staging at d987b66. A second inventory row (smartwatch-hetzner-soak-timer-retired) shares that SHA and is DISABLED — Law 5 remnant, not a second live authority.",
    repoHead: "a717977074ac2697155e4eed2c57f0d78231d6b6",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "smartphone-clank",
    name: "Smartphone Clank",
    purpose: "Evidence engine for smartphone discoveries: aliases, timeline, confidence/decay, alerts.",
    sources: "Eight-OEM soak baseline; Wave 1 Google/OnePlus/Nothing/Xiaomi isolated. Samsung traversal-success/extraction-zero is a named open case (L-SMART-001).",
    scheduling: "systemd timers. systemd-only cutover is the Law 5 reference.",
    persistence: "SQLite at /opt/smartphone-clank/data (survivability inventory). Alembic revision exposed by adapter.",
    host: "Hetzner production. Inventory RUNNING production at b8b8988 while repo later added QC writer 10d5222.",
    status: "Phase 2C adapter. Delivery active. QC writer added. Law 2 novelty debt on catalogue-inventory sources remains OPEN.",
    limitation: "HTTP/traversal success is not extraction success. Dual baseline authority is a risk.",
    unresolved: "L-SMART-001 root cause explicitly unknown. Motherclank must not recompute alias/family/decay.",
    motherclank: "Observer. DEF-M1.5 UUID-order false-STALE fixed in diagnostic-clank 97b07ae.",
    asOf: "2026-08-22 inventory + 2026-08-22 DEF-M1.5 closure",
    confidence: "verified",
    staleNote: "Production SHA vs repo HEAD disagreement recorded in archaeology; treat deployed SHA as UNKNOWN until re-probed.",
    inventorySha: "b8b89885e5229cb36dbc47e78cd1ef4fd1b32937",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance smartphone-hetzner-opt-timers-01, environment production, detached-at-PR3-merge, path /opt/smartphone-clank.",
    repoHead: "97886d778f97b37aada9abefc6f18c239d602573",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "feature-phone-clank",
    name: "Feature Phone Clank",
    purpose: "HMD/Nokia (and isolated itel/Lava experimental) change-detection.",
    sources: "HMD listings/sitemap; experimental itel/Lava on separate runners/volumes.",
    scheduling: "Production cron (repaired after materialization gap). Experimental lanes isolated (Law 5 exception: disjoint DB+lock+volume).",
    persistence: "Recreated volume after 2026-08-23 loss. Epoch fpc-epoch-2 begins 2026-08-23T21:36:11Z. ACT-011 first RP restore-verified. Pre-incident history irrecoverable.",
    host: "Hetzner. Inventory: production plus separate experimental lanes.",
    status: "Events active. Delivery supported_undeployed (code capable, not on deployed revision at snapshot). QC unknown_or_unverified.",
    limitation: "L-PHONE-001: automated success ≠ owner launcher acceptance. Inventory pinned production to c749df3 before later notification changes.",
    unresolved: "Durable off-host NO. HMD ReadTimeout after repair is ordinary source failure, not epoch loss.",
    motherclank: "Observer. Continuity active (fpc-epoch-2).",
    asOf: "2026-08-24 (ACT-011); repo last push 2026-08-27",
    confidence: "verified",
    inventorySha: "c749df33c11b1d8283a3fe48026c6bac6ca4da7e",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Production instance fpc-hetzner-prod-cron-01 at c749df3 (main-pinned-pre-phase0). Experimental lane fpc-hetzner-experimental-cron-01 is a different SHA 49eab2570fad4b92092c56c8fc5b9a635a5d107d on expansion/itel-lava — do not collapse the two.",
    repoHead: "43ceb6d51b7c65cc3226a254030e5a124abba355",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "tablet-clank",
    name: "Tablet Clank",
    purpose: "First-party tablet catalogue changes. No production members, no alerts by original design.",
    sources: "Apple/Samsung/Honor/TCL experimental. Apple sitemap blocked/retired (bb0115c) — must not become 'no tablets found.'",
    scheduling: "None by design after finite soak. Promotion Wave 1 moved Honor/TCL to a manual/on-demand production allowlist. Stale tablet-clank-soak.service must yield INTENTIONALLY_DORMANT, never MISSING_RUN.",
    persistence: "var/tablet_clank.db, negligible. Class EPHEMERAL→RECONSTRUCTABLE.",
    host: "Disabled experimental checkout in 2026-08-22 inventory.",
    status: "Intentionally dormant. Membership must come from manifest, not directory sweep (L-FLEET-001).",
    limitation: "Stale source freshness, no scheduler/notification, unknown backup.",
    unresolved: "Wider onboarding blocked until fresh baseline plus scheduler, backup, and source-health evidence.",
    motherclank: "Observer only if registered. Policy=RETIRED in expectations seed.",
    asOf: "2026-08-27 (repo QC/Windows launcher) / 2026-08-24 (impact-map Tablet correction)",
    confidence: "verified",
    staleNote:
      "Repo HEAD 2026-08-27 (4611307 Windows PyInstaller spec) is newer than a41d1e7 QC archive. 2026-08-22 inventory still said disabled/INTENTIONALLY_DORMANT at 1d3509b. Live host membership UNKNOWN — do not treat HEAD as production.",
    inventorySha: "1d3509b3cd042b0b55701d072512f5255f62a7df",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance tablet-hetzner-idle-checkout-01, deployment_state DISABLED, environment experimental. Soak unit installed disabled+inactive.",
    repoHead: "46113079f520e79d54413ef4e2df8d83e9245c54",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "korean-tech-wire",
    name: "Korean Tech Wire",
    purpose: "Korean-language technology collection with per-source lifecycle. No alert integration by policy.",
    sources: "Samsung, The Elec, SK hynix, LG Display, ETNews. The Elec/ETNews promoted on evidence (379d3c2). SK hynix RSS 403 from Hetzner since 2026-08-10 (host block, not parser defect).",
    scheduling: "cron/timer; per-source due-gating and failure backoff (afe158e, 45e6ec4). Law 8 reference implementation.",
    persistence: "/opt/korean-tech-wire/var SQLite. Backup UNKNOWN.",
    host: "Hetzner staging. RUNNING staging in inventory. Phase 2C adapter.",
    status: "Events/delivery unsupported_by_policy. QC active (feedback writes take RunLock as of 6e95c29 / M4.5-ACT).",
    limitation: "HEALTHY-iff-ever-succeeded was a Law 3 violator; adapter must not display blocked streaks as healthy by history.",
    unresolved: "Host checkout trailing branch tip recorded as Law 9 first violation (healed on GitHub by merge; host may still trail).",
    motherclank: "Observer. Delivery values must remain unsupported, not zero.",
    asOf: "2026-08-22 inventory + Law 8 reference; repo last push 2026-08-27",
    confidence: "verified",
    staleNote: "Deployed SHA vs main: do not assume convergence without host evidence.",
    inventorySha: "262c36dc7eae2d9e8ba3fdfeabc3a002e5cb5577",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at 262c36d. SK hynix HOST-BLOCKED is a source gap, not a healthy zero.",
    repoHead: "cc06a1a0ca8cfefc80804614aca22b31669a09c3",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "chinese-tech-wire",
    name: "Chinese Tech Wire",
    purpose: "Chinese technology discovery (ITHome, MyDrivers, Expreview, ZOL, Jiwei) with original-Chinese preservation.",
    sources: "V0.1 set as above. Blocked regulatory/Geekbench monitoring is unsupported/disabled, not a silent empty source.",
    scheduling: "Hourly cron per dogfood scorecard; final live confirmation LIVE_EVIDENCE_REQUIRED.",
    persistence: "data/ctw.db (registry). Dogfood: checkout-relative refresh path was guessed and never existed — live store was a differently-named Docker volume.",
    host: "Hetzner staging. Inventory RUNNING staging; no host notification authority found.",
    status: "v0.3 observer onboarded 2026-08-24 with dogfood scorecard. Product code can support Discord; runtime capability must win.",
    limitation: "Historical secret scanning / credential rotation remain operator-required. Soak observer PENDING after deploy.",
    unresolved: "Live-state validation and human review of the transfer were still pending in the scorecard.",
    motherclank: "Observer. Zero Motherclank core participant-specific lines. Layer-tagged health is an adapter convention.",
    asOf: "2026-08-25 (ONBOARDING.md cross-check commit); repo last push 2026-08-27",
    confidence: "verified",
    staleNote: "Scheduler authority step scored LIVE_EVIDENCE_REQUIRED — do not claim a verified live cron without host probe.",
    inventorySha: "c1b3a415a07bc5b58f4237268aff03ee2fb82ff1",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at c1b3a41. Refresh-path guess is a Law 6 specimen, not a live SHA.",
    repoHead: "1a47220c69e6bb91f2899a0508508c42254c9d5b",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "oem-radar",
    name: "OEM Radar",
    purpose: "Boutique PC OEM product intelligence: immutable snapshots, semantic diff, Discord via outbox. Mission: spot new hardware before mainstream media.",
    sources: "Source (platform engine + YAML) is the extension unit, not OEM-specific code. Dell US disabled for persistent 403. Experimental Lenovo/ASUS/Beelink lanes.",
    scheduling: "Stateless one-shot CLI scheduled by OS (ADR-1). Cron repaired after materialization gap. Dashboard auto-crawl later fail-closed (4e585ac) so the GUI is not a second scheduler.",
    persistence: "SQLite WAL, append-only content-hash snapshots. Continuity CONTIGUOUS (no volume loss). Backup UNKNOWN.",
    host: "Hetzner staging plus isolated experimental lane. Inventory RUNNING staging.",
    status: "Events/delivery/QC active in capability matrix. BANKAI recall remains the mission-level scar.",
    limitation: "L-OEM-001 first fire mistaken for hourly cadence (actually daily). L-OEM-003 operational health ≠ newsroom recall. L-OEM-004 Beelink miss: UNKNOWN, do not invent parser fault.",
    unresolved: "Dashboard historically shared prod webhook authority (Law 5 open at codification). Promotion records missing until Phase 2A.",
    motherclank: "Observer. Reference for snapshots/outbox, not a shared library.",
    asOf: "2026-08-22 inventory + 2026-08-24 continuity (CONTIGUOUS)",
    confidence: "verified",
    inventorySha: "410313b64b41e430e408c344382720c2e8a04f47",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Staging instance oem-radar-hetzner-staging-cron-01 at 410313b (BANKAI merge). Experimental BANKAI soak timer is a different SHA 31fc46be895664865ab23bcc6b10a370559b766a — isolated lane, not the staging authority.",
    repoHead: "d720e0635894ddcc9a39f116e2aa4a1768090042",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "free-game-tracker",
    name: "Free Game Tracker (Newsroom)",
    purpose: "Detect newly free PC games (Epic, Steam 100%-off, GOG, GamerPower). Facts separate from editorial judgment.",
    sources: "Store catalogues plus GamerPower aggregator. Subscription-entitlement path is a different coverage axis (L-FGT-001 Helldivers 2/PS Plus miss, root cause unknown).",
    scheduling: "Hourly cron on Hetzner production. Windows Task Scheduler leftover must not share the production webhook (dual-host risk).",
    persistence: "Container volume is production. Repository-directory newsroom.db is a stale legacy copy (inventory warning). Backup scripts exist; whether they are scheduled is UNKNOWN.",
    host: "Hetzner production. Inventory RUNNING production.",
    status: "Capability matrix: collection/health/events active-by-code-evidence; REAL_STATE_VALIDATION BLOCKED until live read-only copy. Delivery log-only. QC unsupported.",
    limitation: "Law 1 violator at codification (fresh-DB notifies all). Law 7 specimen: /api/run threading.Lock bypass, DB Eradication. 840641f: logs swallowed after DB init.",
    unresolved: "Discord webhook rotation AUTHORIZED, BLOCKED-ON-OPERATOR. FGT registry filename drift caught during CTW dogfood.",
    motherclank: "Observer onboarding tests exist (FGT-G1..G10). Do not treat local checkout DB as production truth.",
    asOf: "2026-08-21 last push / 2026-08-24 capability matrix",
    confidence: "verified",
    staleNote: "Pushed_at 2026-08-21 — older than several other Clanks. Re-verify before claiming current production behaviour.",
    inventorySha: "cec034695d52affc284701fe93966dd7c59c5bcd",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING production at cec0346. Checkout newsroom.db is documented STALE; container volume is the production claim — still not a 2026-08-27 live probe.",
    repoHead: "45b47a5af3680c800ebf535d0764afcb7d263ce6",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "semiconductor-intelligence",
    name: "Semiconductor Intelligence",
    purpose: "Claims-and-evidence research tool. Atomic unit is a claim, not an article.",
    sources: "Deterministic source plugins, Signal Radar import (preview-first; derived legacy data not trusted).",
    scheduling: "OperationalScheduler is the intended path. Inventory residual: hourly cron invoked pipeline run directly (Laws 3/5). Repo head is not proof the host changed.",
    persistence: "semintel_staging_data SQLite/alembic. Backup UNKNOWN.",
    host: "Hetzner staging. RUNNING staging.",
    status: "v0.3 observer dogfood 2026-08-25. intelligence_assertion@1 evidence type seeded. Scheduler residual explicitly open.",
    limitation: "Broken Task Scheduler action meant collection was not unattended until d43481f. Law 6 specimen: d43481f claim-vs-ledger contradiction.",
    unresolved: "Windows UNKNOWN state. Do not automatically promote imported derived legacy data.",
    motherclank: "Observer. Distinct subject model (claims), not article events.",
    asOf: "2026-08-25 SI dogfood / 2026-08-22 inventory",
    confidence: "verified",
    staleNote: "Last inventory SHA 9dbf06d. Repo HEAD 8a356a3 adds human QC for Radar candidates — not host evidence.",
    inventorySha: "9dbf06d11cff23961fb11f240b2f2ea94c728777",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at 9dbf06d. OperationalScheduler vs hourly cron residual is a Law 5 question for the host probe.",
    repoHead: "8a356a3bc87bea0f0d95e66c072c8e8a629156d5",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "motherclank",
    name: "Motherclank",
    purpose: "Read-only fleet harvester/supervisor (ADR-0002). Observe, reason, propose — never remediate in M0–M4.",
    sources: "Diagnostic-Clank-owned adapters, consumed unchanged. Inventory: fleet.yaml.",
    scheduling: "ONE fixed-clock systemd user timer. host-harvest.sh refreshes read-only copies then harvests.",
    persistence: "Append-only dated JSONL snapshots + derived Markdown. Disposable. Clank DBs untouched.",
    host: "Hetzner user service (documented). Rollback = disable timer, delete snapshots.",
    status: "M0–M4 implemented with golden corpus, continuity, liveness, survivability derivation, closeout v1 (2026-08-26 inputs). M5 excluded.",
    limitation: "Cannot see what adapters cannot read. Missing host var/ artefacts blocked row-level confirmation of 22–23 Aug batches.",
    unresolved: "M5 requires future ADR with authn/fencing/authorization/rollback. Durable off-host observation of backups still OPEN.",
    motherclank: "This row is the supervisor.",
    asOf: "2026-08-26 closeout inputs / 2026-08-26 last push",
    confidence: "verified",
    inventorySha: "UNKNOWN",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "fleet.yaml deployment_facts rows at the end of the inventory leave instance_id, host, and deployed_commit_sha UNKNOWN — likely Diagnostic/Motherclank themselves. Do not invent a SHA for the camera.",
    repoHead: "7cee2f89c4e84fdad3eb337a7eb4cbcc5dce8e04",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
  },
  {
    id: "diagnostic-clank",
    name: "Diagnostic Clank",
    purpose: "Read-only diagnostics, Agent Output Inbox, fleet inventory, adapter plane. Not Motherclank.",
    sources: "Report ingestion, DiagnosticBench cases, fleet.yaml, adapters per Clank.",
    scheduling: "Not a collector scheduler. Prototype control plane; promotion frozen.",
    persistence: "Own diagnostic.db (Watch corpus extracted from owner-supplied zip). Does not own Clank SQLite.",
    host: "Default branch diagnostic-clank-2026-08 (not main). Last push 2026-08-26.",
    status: "Owns adapters Motherclank consumes. ADR-0001 inventory owner. Agent Inbox may receive M3 recommendations (ADR-0003).",
    limitation: "README still branded 'Unified Clank Platform' / Stage 1A — historical naming. No production behaviour authorized.",
    unresolved: "Cross-Clank identity ADR still blocking participant profile. Fresh host verification of fleet.yaml still required for live claims.",
    motherclank: "Sibling: adapters-src. Motherclank is consumer, not successor.",
    asOf: "2026-08-26",
    confidence: "verified",
    staleNote: "README status banner may lag the adapter work on the 2026-08 branch.",
    inventorySha: "UNKNOWN",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "fleet.yaml lists diagnostic-clank as SUPPORTING_SYSTEM with deployment_state UNKNOWN. The 2026-08-22 inventory does not pin a Diagnostic deploy SHA.",
    repoHead: "3667af02c8dd33503ce75461ec2974d42f2f1d4c",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote:
      "HEAD of default branch diagnostic-clank-2026-08 (not main). 3667af0 is the Tablet observer adapter. Control-plane commit, not Tablet production membership.",
    liveDeployedSha: LIVE_UNKNOWN,
  },
];
