import type { FleetClank } from "../lib/handbook/schema.ts";

/**
 * Current-state map. asOf and staleNote are mandatory honesty.
 *
 * SHA columns (do not collapse):
 *   inventorySha  = fleet.yaml deployed_commit_sha as_of 2026-08-22T22:30:00Z
 *                   Systems born after that inventory use ABSENT-FROM-2026-08-22-INVENTORY.
 *   repoHead      = GitHub default-branch HEAD as of the 2026-09-14 teaching capture
 *                   (Jules branch for clank-ledger; LOCAL-ONLY for Quartermaster).
 *   liveDeployedSha = always UNKNOWN until a live host probe this campaign.
 *   historicallyProvenDeployedSha = optional Standards COM-001 point-in-time live proof
 *                   around 2026-09-05. Dated. Not current. Must not be copied into live.
 * GitHub HEAD is not production. Do not fill liveDeployedSha from repoHead or COM-001.
 */
const INVENTORY_AS_OF = "2026-08-22T22:30:00Z";
const REPO_HEAD_AS_OF = "2026-09-14T10:00Z";
const LIVE_UNKNOWN = "UNKNOWN";
const HEAD_NOTE =
  "GitHub default-branch HEAD captured 2026-09-14 via the GitHub API for this teaching pass. Not a host checkout. Not a running image. Not production.";
const COM001_NOTE =
  "Standards COM-001 historically proven live deployment around 2026-09-05. Source canon later advanced. This is a dated proof, not today's running SHA. This campaign did not re-probe the host. Do not copy into liveDeployedSha.";
const ABSENT_INV = "ABSENT-FROM-2026-08-22-INVENTORY";
const ABSENT_NOTE =
  "Not present in diagnostic-clank fleet.yaml as_of 2026-08-22T22:30:00Z. Absence from that inventory is a fact about 22 August, not a claim the system did not exist later.";

export const FLEET: FleetClank[] = [
  {
    id: "watch-clank",
    name: "Watch Clank",
    purpose: "Editorial discovery of watch products and stories (Casio origin; Citizen/Seiko/Timex/specialists).",
    sources: "Official brand surfaces plus specialist sources; sitemap family for deltas. Region declared per collector. Post-v0.1: casio_multi JP product component moved onto the official sitemap lane (930aef1).",
    scheduling: "Hetzner user-timers; single Discord authority; legacy crons annotated-disabled (Law 5).",
    persistence: "SQLite; collectors/parsers do not write the DB directly; pipeline persistence owns transactions. Alembic migrations.",
    host: "Hetzner production (fleet inventory RUNNING production as of 2026-08-22).",
    status: "Phase 2C read-only adapter onboarded. Human QC live. Catalogue-pass is an invocation fact after 2026-08-26. Post-v0.1 Horology Sentinel / casio_multi component-health work is in git, not a live-host claim.",
    limitation: "Delivery accounting not persisted (adapter reports unsupported/unknown). Host path for the production DB UNKNOWN in survivability matrix.",
    unresolved: "L-WATCH-006 region gaps OPEN. L-WATCH-003 official-but-late OPEN. Live SHA UNKNOWN. COM-001 historical proof d03bc4b is not current live.",
    motherclank: "Observer-tier. QC dispositions ingested. scheduler_trace supported_unconfigured.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote:
      "Inventory still f0b327a (2026-08-22). Repo HEAD 930aef1 (casio_multi, 2026-09-10) is newer. COM-001 historically proved d03bc4b live around 2026-09-05. Three different objects. None of them is filled into liveDeployedSha.",
    inventorySha: "f0b327acc9970221de230c68d4bc03480d853a46",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance watch-hetzner-user-timers-01, environment production, image watch-clank:f0b327a. Database path UNKNOWN-host-path-under-anilganti.",
    repoHead: "930aef1e0aac29062600d06537e85a1426ec4e9e",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "d03bc4b2f90289686331af0447d5ca4e8cf55822",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What watch products and stories appeared, in which region, with what novelty class?",
    doesNotOwn: "Fleet health, standards ratification, editorial HIT/MISS, model quota.",
    evolution: "Post-v0.1: casio_multi JP component health on the official sitemap lane (PR #10, 930aef1, 2026-09-10). Horology Sentinel/tripwire work sits in this window. Qualification-evidence preservation (d03bc4b, 2026-09-01) is the COM-001 historical live SHA — later source is not that proof.",
  },
  {
    id: "smartwatch-clank",
    name: "Smartwatch Clank",
    purpose: "Connected-wearable catalogue/news observations with silent initial baseline.",
    sources: "Samsung/Google/Garmin/Apple official-news (Stage B); Garmin catalogue plus Amazfit/Zepp/COROS (Stage C).",
    scheduling: "Cron sole scheduler after systemd soak timer retired 2026-08-21T21:06Z. Policy PERIODIC on staging.",
    persistence: "SQLite volume. Restored 2026-08-23 from 2026-08-18 backup (sw-epoch-1-restored…). ACT-011 RP1 restore-verified. Post-v0.1: schema v3→v4 additive for Discord outbox (9d85f92); fail-closed schema-state barrier (a933554, COM-001 historical).",
    host: "Hetzner staging. RUNNING staging in 2026-08-22 inventory.",
    status: "Events/delivery were unsupported_by_policy at v0.1. Repo HEAD 2026-09-10 implements persistence-first Discord outbox behind schema-state authority. Whether that code is on the host: UNKNOWN.",
    limitation: "≈3 days 13 hours of observations permanently missing. Durable off-host copy is temporary_scratch only.",
    unresolved: "Whether the pre-incident backup pipeline resumed after restore: UNKNOWN. Discord webhook activation is a live procedure (runbook), not a git fact.",
    motherclank: "Observer. INTENTIONALLY_DORMANT must not be inferred — this lane is PERIODIC.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote:
      "Inventory d987b66. COM-001 historical a933554 (schema fail-closed, 2026-09-02). HEAD 9d85f92 Discord delivery (2026-09-10). Live UNKNOWN.",
    inventorySha: "d987b66ad3b6f96575ddf1c04f8a76833a837026",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Cron lane RUNNING staging at d987b66. A second inventory row (smartwatch-hetzner-soak-timer-retired) shares that SHA and is DISABLED — Law 5 remnant, not a second live authority.",
    repoHead: "9d85f926474e55310f3b565782c1c5cc4b7a20ea",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "a93355480bb11e1bd16ae7837256ce9002fc2aa7",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What connected-wearable catalogue/news changes appeared?",
    doesNotOwn: "Fleet supervision, editorial HIT/MISS, model quota.",
    evolution: "Post-v0.1: STD-DEPLOY-COM-002 fail-closed schema-state (a933554). Discord delivery: persist-before-send outbox, activation cutoff, editorial gate CRITICAL/NEWSWORTHY only (9d85f92). 323 tests passed in git — that is not a host activation.",
  },
  {
    id: "smartphone-clank",
    name: "Smartphone Clank",
    purpose: "Evidence engine for smartphone discoveries: aliases, timeline, confidence/decay, alerts.",
    sources: "Eight-OEM soak baseline; Wave 1 Google/OnePlus/Nothing/Xiaomi isolated. Samsung traversal-success/extraction-zero is a named open case (L-SMART-001). Post-v0.1: samsung_us_owners_product promoted from CANARY to production maturity (60bc5f5, 2026-09-05 operator decision).",
    scheduling: "systemd timers. systemd-only cutover is the Law 5 reference.",
    persistence: "SQLite at /opt/smartphone-clank/data (survivability inventory). Alembic revision exposed by adapter.",
    host: "Hetzner production. Inventory RUNNING production at b8b8988 while repo later added QC writer 10d5222.",
    status: "Phase 2C adapter. Delivery active. QC writer added. 2026-09-05: canary source promoted in git. Live membership of that promotion: UNKNOWN.",
    limitation: "HTTP/traversal success is not extraction success. Dual baseline authority is a risk.",
    unresolved: "L-SMART-001 root cause explicitly unknown. Motherclank must not recompute alias/family/decay. Live SHA UNKNOWN.",
    motherclank: "Observer. DEF-M1.5 UUID-order false-STALE fixed in diagnostic-clank 97b07ae.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (promotion + COM-001) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Inventory b8b8988. COM-001 historical e514c45. HEAD 60bc5f5 promote-canary. Live UNKNOWN.",
    inventorySha: "b8b89885e5229cb36dbc47e78cd1ef4fd1b32937",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance smartphone-hetzner-opt-timers-01, environment production, detached-at-PR3-merge, path /opt/smartphone-clank.",
    repoHead: "60bc5f595c79b093abfd084577b9658b197b497e",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "e514c45dca4cf966441c27799d98761096dc8c40",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What smartphone discoveries are evidenced, with what alias/family/decay?",
    doesNotOwn: "Fleet law, development sessions, editorial HIT/MISS.",
    evolution: "Post-v0.1: samsung_us_owners_product promoted CANARY→production maturity by explicit operator decision 2026-09-05 (60bc5f5). samsung_support stays soak AND disabled — promoting maturity must not silently enable a source. Fail-closed default unchanged.",
  },
  {
    id: "feature-phone-clank",
    name: "Feature Phone Clank",
    purpose: "HMD/Nokia (and isolated itel/Lava experimental) change-detection.",
    sources: "HMD listings/sitemap; experimental itel/Lava on separate runners/volumes.",
    scheduling: "Production cron (repaired after materialization gap). Experimental lanes isolated (Law 5 exception: disjoint DB+lock+volume).",
    persistence: "Recreated volume after 2026-08-23 loss. Epoch fpc-epoch-2 begins 2026-08-23T21:36:11Z. Post-v0.1: constructing SqliteStore is a fail-closed compatibility barrier (b60e881 / STD-DEPLOY-COM-002).",
    host: "Hetzner. Inventory: production plus separate experimental lanes.",
    status: "Events active. Delivery supported_undeployed at v0.1 snapshot. Schema-compatibility barrier is in git; host admission of that barrier: UNKNOWN.",
    limitation: "L-PHONE-001: automated success ≠ owner launcher acceptance. Inventory pinned production to c749df3 before later notification changes.",
    unresolved: "Durable off-host NO. Live SHA UNKNOWN. Compose .env gitignored at c376801 — a secret-hygiene commit, not a deploy.",
    motherclank: "Observer. Continuity active (fpc-epoch-2).",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    inventorySha: "c749df33c11b1d8283a3fe48026c6bac6ca4da7e",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Production instance fpc-hetzner-prod-cron-01 at c749df3 (main-pinned-pre-phase0). Experimental lane fpc-hetzner-experimental-cron-01 is a different SHA 49eab2570fad4b92092c56c8fc5b9a635a5d107d on expansion/itel-lava — do not collapse the two.",
    repoHead: "c376801cb2cbf59c30c1d7e305ae24ecc4cea0e5",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "b60e881319b16d36625268d9ba2d66cb8ea8f818",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What HMD/Nokia (and isolated experimental) listing changes appeared?",
    doesNotOwn: "Production vs experimental lane identity is two instances, not two Clanks.",
    evolution: "Post-v0.1: M14 fail-closed persistent-state compatibility (b60e881, 2026-09-01) — FRESH/COMPATIBLE migrate; NEWER/UNKNOWN/CORRUPT/PARTIAL refuse, file byte-identical. HEAD c376801 gitignores compose .env.",
  },
  {
    id: "tablet-clank",
    name: "Tablet Clank",
    purpose: "First-party tablet catalogue changes. No production members, no alerts by original design.",
    sources: "Apple/Samsung/Honor/TCL experimental. Apple sitemap blocked/retired (bb0115c) — must not become 'no tablets found.'",
    scheduling: "None by design after finite soak. Promotion Wave 1 moved Honor/TCL to a manual/on-demand production allowlist. Stale tablet-clank-soak.service must yield INTENTIONALLY_DORMANT, never MISSING_RUN.",
    persistence: "var/tablet_clank.db, negligible. Class EPHEMERAL→RECONSTRUCTABLE. Post-v0.1 fail-closed incompatible-state (b3088ebc).",
    host: "Disabled experimental checkout in 2026-08-22 inventory.",
    status: "Intentionally dormant at inventory. Repo HEAD 7fd6939 stamps MANUAL qualification provenance on GUI 'Collect Now' so a dashboard run is not UNKNOWN-provenance. That does not make Tablet production.",
    limitation: "Stale source freshness, no scheduler/notification, unknown backup.",
    unresolved: "Live host membership UNKNOWN — still do not treat HEAD as production.",
    motherclank: "Observer only if registered. Policy=RETIRED in expectations seed.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote:
      "Inventory 1d3509b DISABLED/INTENTIONALLY_DORMANT. COM-001 historical b3088ebc. HEAD 7fd6939 GUI qualification provenance. Live UNKNOWN. INTENTIONALLY_DORMANT remains the controlling liveness output until a live probe says otherwise.",
    inventorySha: "1d3509b3cd042b0b55701d072512f5255f62a7df",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml instance tablet-hetzner-idle-checkout-01, deployment_state DISABLED, environment experimental. Soak unit installed disabled+inactive.",
    repoHead: "7fd69392a89f320a98fee8c046419acb466f98f3",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "b3088ebc716227b99e1d8aa66942c8a6e87bbfcb",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What first-party tablet catalogue changes appeared, when this lane is actually run?",
    doesNotOwn: "A GUI collect is not a scheduler. Manual provenance is not production membership.",
    evolution: "Post-v0.1: fail-closed DB state (b3088ebc). GUI Collect Now now stamps MANUAL into manual:<source> so STD-OPS-COM-003 provenance is not UNKNOWN (7fd6939, 2026-09-06). _gate() already refused UNKNOWN; what was missing was the evidence.",
  },
  {
    id: "korean-tech-wire",
    name: "Korean Tech Wire",
    purpose: "Korean-language technology collection with per-source lifecycle. No alert integration by policy.",
    sources: "Samsung, The Elec, SK hynix, LG Display, ETNews. The Elec/ETNews promoted on evidence (379d3c2). SK hynix RSS 403 from Hetzner since 2026-08-10 (host block, not parser defect). Post-v0.1: The Elec members-only stories filtered (c80a696) — can the operator read this page?",
    scheduling: "cron/timer; per-source due-gating and failure backoff (afe158e, 45e6ec4). Law 8 reference implementation.",
    persistence: "/opt/korean-tech-wire/var SQLite. Backup UNKNOWN.",
    host: "Hetzner staging. RUNNING staging in inventory. Phase 2C adapter.",
    status: "Events/delivery unsupported_by_policy. QC active. Members-only gate is in git; host running that gate: UNKNOWN.",
    limitation: "HEALTHY-iff-ever-succeeded was a Law 3 violator; adapter must not display blocked streaks as healthy by history.",
    unresolved: "Host checkout trailing branch tip recorded as Law 9 first violation (healed on GitHub by merge; host may still trail).",
    motherclank: "Observer. Delivery values must remain unsupported, not zero.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Inventory 262c36d. COM-001 historical f49bd02. HEAD c80a696 The Elec members-only. Live UNKNOWN.",
    inventorySha: "262c36dc7eae2d9e8ba3fdfeabc3a002e5cb5577",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at 262c36d. SK hynix HOST-BLOCKED is a source gap, not a healthy zero.",
    repoHead: "c80a69697ac94d4069c818e015f6c5f10bdb5986",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "f49bd02eb214b650a146e9c0f6f348d526285a91",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What Korean-language tech stories appeared that the operator can actually read?",
    doesNotOwn: "A login panel is not an article. Members-only rejection is filtering, not collector failure.",
    evolution: "Post-v0.1: The Elec 회원전용기사 panel pair is the access gate (c80a696, 2026-09-10). Index cards have no marker; gate is post-hydration. A run that sheds paywalled stories stays healthy — deliberate filter. Restricted rows fall out of dashboard/QC/translation/Discord via record_status='valid'.",
  },
  {
    id: "chinese-tech-wire",
    name: "Chinese Tech Wire",
    purpose: "Chinese technology discovery (ITHome, MyDrivers, Expreview, ZOL, Jiwei) with original-Chinese preservation.",
    sources: "V0.1 set as above. Blocked regulatory/Geekbench monitoring is unsupported/disabled, not a silent empty source.",
    scheduling: "Hourly cron per dogfood scorecard; final live confirmation LIVE_EVIDENCE_REQUIRED. Post-v0.1 Health UI dropped the stale Task-Scheduler block because CTW is manually operated in that console (e7f10f8) — backend scheduler modules untouched.",
    persistence: "data/ctw.db (registry). Dogfood: checkout-relative refresh path was guessed and never existed — live store was a differently-named Docker volume.",
    host: "Hetzner staging. Inventory RUNNING staging; no host notification authority found.",
    status: "v0.3 observer onboarded 2026-08-24. Post-v0.1: manual-run launch survives DB races; Health UI no longer pretends a scheduler is the authority.",
    limitation: "Historical secret scanning / credential rotation remain operator-required.",
    unresolved: "Live-state validation still pending. Translation-cost containment is operator pressure in this window; host topology of translation: UNKNOWN without live probe.",
    motherclank: "Observer. Zero Motherclank core participant-specific lines. Layer-tagged health is an adapter convention.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Inventory c1b3a41. COM-001 historical cfbd315. HEAD e7f10f8 manual-run/DB-race. Scheduler authority still LIVE_EVIDENCE_REQUIRED.",
    inventorySha: "c1b3a415a07bc5b58f4237268aff03ee2fb82ff1",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at c1b3a41. Refresh-path guess is a Law 6 specimen, not a live SHA.",
    repoHead: "e7f10f843e2066a088c45602d47c8cc05d887589",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "cfbd3158a5272aab6e67a2a9005be2c3a45544e6",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What Chinese-language tech discoveries appeared, preserving original text?",
    doesNotOwn: "A dashboard GET is not a scheduler. Stale Task-Scheduler UI was a lie about authority.",
    evolution: "Post-v0.1: /operations/run-now survives SQLite lock races during child ingest (e7f10f8). Health UI removes obsolete scheduler block because CTW is manually operated there. Logging redaction vs uvicorn AccessFormatter was a separate scar (cfbd315, COM-001 historical).",
  },
  {
    id: "oem-radar",
    name: "OEM Radar",
    purpose: "Boutique PC OEM product intelligence: immutable snapshots, semantic diff, Discord via outbox. Mission: spot new hardware before mainstream media.",
    sources: "Source (platform engine + YAML) is the extension unit, not OEM-specific code. Dell US disabled for persistent 403. Experimental Lenovo/ASUS/Beelink lanes.",
    scheduling: "Stateless one-shot CLI scheduled by OS (ADR-1). Cron repaired after materialization gap. Dashboard auto-crawl later fail-closed (4e585ac) so the GUI is not a second scheduler.",
    persistence: "SQLite WAL, append-only content-hash snapshots. Continuity CONTIGUOUS (no volume loss). Backup UNKNOWN.",
    host: "Hetzner staging plus isolated experimental lane. Inventory RUNNING staging.",
    status: "Events/delivery/QC active in capability matrix. BANKAI recall remains the mission-level scar. Post-v0.1: container now exports baked GIT_REVISION as OEM_RADAR_GIT_SHA (24d61dd) so runtime logs stop saying git_sha=unknown.",
    limitation: "L-OEM-001 first fire mistaken for hourly cadence (actually daily). L-OEM-003 operational health ≠ newsroom recall. L-OEM-004 Beelink miss: UNKNOWN, do not invent parser fault.",
    unresolved: "Dashboard historically shared prod webhook authority (Law 5 open at codification). Live SHA UNKNOWN even though the image can now name itself.",
    motherclank: "Observer. Reference for snapshots/outbox, not a shared library.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    inventorySha: "410313b64b41e430e408c344382720c2e8a04f47",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "Staging instance oem-radar-hetzner-staging-cron-01 at 410313b (BANKAI merge). Experimental BANKAI soak timer is a different SHA 31fc46be895664865ab23bcc6b10a370559b766a — isolated lane, not the staging authority.",
    repoHead: "24d61dd4238ad03c073ae592c57e2ffa6fbdb488",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "070914c82516c29be781a49acb77c8d86953f1e2",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "What boutique OEM hardware appeared before mainstream coverage?",
    doesNotOwn: "Baking GIT_REVISION into the image is runtime identity, not a live probe of this campaign.",
    evolution: "Post-v0.1: sixth and final Clank onto Collector UI Design System v1 (070914c, COM-001 historical). 2026-09-10: pass baked GIT_REVISION into the container as OEM_RADAR_GIT_SHA (24d61dd, PR #9) because discord_runtime provenance logged git_sha=unknown inside images that have no .git.",
  },
  {
    id: "free-game-tracker",
    name: "Free Game Tracker (Newsroom)",
    purpose: "Detect newly free PC games (Epic, Steam 100%-off, GOG, GamerPower). Facts separate from editorial judgment.",
    sources: "Store catalogues plus GamerPower aggregator. Subscription-entitlement path is a different coverage axis (L-FGT-001 Helldivers 2/PS Plus miss, root cause unknown). Reddit admission, if any, is a participant-owned experimental source — FGT is not 'Reddit Clank'.",
    scheduling: "Hourly cron on Hetzner production. Windows Task Scheduler leftover must not share the production webhook (dual-host risk).",
    persistence: "Container volume is production. Repository-directory newsroom.db is a stale legacy copy (inventory warning). Backup scripts exist; whether they are scheduled is UNKNOWN.",
    host: "Hetzner production. Inventory RUNNING production.",
    status: "Capability matrix: collection/health/events active-by-code-evidence; REAL_STATE_VALIDATION BLOCKED until live read-only copy. Delivery log-only. QC unsupported. Post-v0.1: operator-console tests lock GET-never-collects (011b89f, 2026-09-04).",
    limitation: "Law 1 violator at codification (fresh-DB notifies all). Law 7 specimen: /api/run threading.Lock bypass, DB Eradication. 840641f: logs swallowed after DB init.",
    unresolved: "Discord webhook rotation AUTHORIZED, BLOCKED-ON-OPERATOR. Live volume UNKNOWN.",
    motherclank: "Observer onboarding tests exist (FGT-G1..G10). Do not treat local checkout DB as production truth.",
    asOf: "2026-09-14 (repo HEAD) / 2026-08-22 (inventory). No COM-001 historical live SHA recorded for FGT in the nine-system wave.",
    confidence: "verified",
    staleNote: "Inventory cec0346. HEAD 011b89f operator-console tests. No COM-001 row — do not invent one. Live UNKNOWN.",
    inventorySha: "cec034695d52affc284701fe93966dd7c59c5bcd",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING production at cec0346. Checkout newsroom.db is documented STALE; container volume is the production claim — still not a 2026-09-14 live probe.",
    repoHead: "011b89fc6747ce2bd93e75aba327fd1cffbf3b69",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "Which PC games became free, as store facts rather than editorial judgment?",
    doesNotOwn: "A GUI GET must never collect. Reddit sources, if admitted, stay experimental and participant-owned.",
    evolution: "Post-v0.1: test_operator_console.py locks GET-never-invokes-collector, POST /api/run goes through cli.run_pipeline, duplicate runs refused, five distinct no-data/zero/failed/partial/disabled values (011b89f). Worktree feat/reddit-discovery-admission exists as an experiment, not a production Clank.",
  },
  {
    id: "semiconductor-intelligence",
    name: "Semiconductor Intelligence",
    purpose: "Claims-and-evidence research tool. Atomic unit is a claim, not an article.",
    sources: "Deterministic source plugins, Signal Radar import (preview-first; derived legacy data not trusted). Post-v0.1: silent experimental Reddit RSS pilot r/hardware-only (a9a202a), muted, polling off, no production registration.",
    scheduling: "OperationalScheduler is the intended path. Inventory residual: hourly cron invoked pipeline run directly (Laws 3/5). Repo head is not proof the host changed.",
    persistence: "semintel_staging_data SQLite/alembic. Backup UNKNOWN. Reddit pilot: no schema migration.",
    host: "Hetzner staging. RUNNING staging.",
    status: "v0.3 observer dogfood 2026-08-25. Reddit source is experimental and muted. admit_source_for_delivery is the only authority grant.",
    limitation: "Broken Task Scheduler action meant collection was not unattended until d43481f. Law 6 specimen: d43481f claim-vs-ledger contradiction. Canonical CI is not green (RED-CI protocol on SemInt).",
    unresolved: "Windows UNKNOWN state. Do not automatically promote imported derived legacy data. Reddit not admitted.",
    motherclank: "Observer. Distinct subject model (claims), not article events. Must not become the Reddit collector.",
    asOf: "2026-09-14 (repo HEAD) / 2026-09-05 (COM-001 historical) / 2026-08-22 (inventory)",
    confidence: "verified",
    staleNote: "Inventory 9dbf06d. COM-001 historical 53cb3f1. HEAD a9a202a Reddit RSS pilot (muted). Live UNKNOWN. Suite RED — do not call it green.",
    inventorySha: "9dbf06d11cff23961fb11f240b2f2ea94c728777",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: "fleet.yaml RUNNING staging at 9dbf06d. OperationalScheduler vs hourly cron residual is a Law 5 question for the host probe.",
    repoHead: "a9a202ad82d6365890d49a34de75dceeac329762",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    historicallyProvenDeployedSha: "53cb3f1f5358ad28a2d92ebd78efeab9534ddfa1",
    historicallyProvenDeployedAsOf: "2026-09-05",
    historicallyProvenDeployedNote: COM001_NOTE,
    layer: "participant",
    presence: "github",
    postV01: false,
    ownsQuestion: "Which semiconductor claims are evidenced, and which sources are admitted to notify?",
    doesNotOwn: "Reddit. Unmute is not admission. No production registration of r/hardware.",
    evolution: "Post-v0.1: M0 Reddit pilot r/hardware-only RSS (a9a202a, 2026-09-09 PR #5): experimental, muted, polling off, fail-closed watermarks, silent first-success baseline, no schema migration, no deployment. STD-UI-COM-010 timezone convention (53cb3f1) is the COM-001 historical SHA.",
  },
  {
    id: "motherclank",
    name: "Motherclank",
    purpose: "Read-only fleet harvester/supervisor (ADR-0002). Observe, reason, propose — never remediate in M0–M4.",
    sources: "Diagnostic-Clank-owned adapters, consumed unchanged. Inventory: fleet.yaml.",
    scheduling: "ONE fixed-clock systemd user timer. host-harvest.sh refreshes read-only copies then harvests.",
    persistence: "Append-only dated JSONL snapshots + derived Markdown. Disposable. Clank DBs untouched.",
    host: "Hetzner user service (documented). Rollback = disable timer, delete snapshots.",
    status: "M0–M4 implemented with golden corpus, continuity, liveness, survivability derivation, closeout v1 (2026-08-26 inputs). M5 excluded. GitHub HEAD unchanged vs Handbook v0.1 (7cee2f8).",
    limitation: "Cannot see what adapters cannot read. Missing host var/ artefacts blocked row-level confirmation of 22–23 Aug batches.",
    unresolved: "M5 requires future ADR with authn/fencing/authorization/rollback. Durable off-host observation of backups still OPEN. Not ClankOps, not Standards, not Quartermaster, not Ledger.",
    motherclank: "This row is the supervisor.",
    asOf: "2026-09-14 (repo HEAD unchanged since 2026-08-26)",
    confidence: "verified",
    inventorySha: "UNKNOWN",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "fleet.yaml deployment_facts rows at the end of the inventory leave instance_id, host, and deployed_commit_sha UNKNOWN — likely Diagnostic/Motherclank themselves. Do not invent a SHA for the camera.",
    repoHead: "7cee2f89c4e84fdad3eb337a7eb4cbcc5dce8e04",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE + " Unchanged vs v0.1 freeze capture.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "observation",
    presence: "github",
    postV01: false,
    ownsQuestion: "What did the fleet look like at harvest time, with UNKNOWN preserved?",
    doesNotOwn: "Development missions, standards ratification, editorial HIT/MISS, model quota, evidence-package validation, remediation.",
    evolution: "No default-branch commits after 2026-08-26 closeout hygiene. Later CVC observer PRs exist unmerged and are not current architecture. Mission 3 architecture/handoff audit (separate campaign) found BOUNDARY HEALTHY WITH MINOR REPAIRS; those PRs stay unmerged.",
  },
  {
    id: "diagnostic-clank",
    name: "Diagnostic Clank",
    purpose: "Read-only diagnostics, Agent Output Inbox, fleet inventory, adapter plane. Not Motherclank.",
    sources: "Report ingestion, DiagnosticBench cases, fleet.yaml, adapters per Clank.",
    scheduling: "Not a collector scheduler. Prototype control plane; promotion frozen.",
    persistence: "Own diagnostic.db (Watch corpus extracted from owner-supplied zip). Does not own Clank SQLite.",
    host: "Default branch diagnostic-clank-2026-08 (not main). Last push 2026-08-26. Unchanged vs v0.1.",
    status: "Owns adapters Motherclank consumes. ADR-0001 inventory owner. Agent Inbox may receive M3 recommendations (ADR-0003).",
    limitation: "README still branded 'Unified Clank Platform' / Stage 1A — historical naming. No production behaviour authorized. 2026-08-22 inventory is still the last dated fleet.yaml this Handbook trusts.",
    unresolved: "Cross-Clank identity ADR still blocking participant profile. Fresh host verification of fleet.yaml still required for live claims.",
    motherclank: "Sibling: adapters-src. Motherclank is consumer, not successor.",
    asOf: "2026-09-14 (repo HEAD unchanged since 2026-08-26)",
    confidence: "verified",
    staleNote: "README status banner may lag the adapter work on the 2026-08 branch. Unmerged CVC observer PR is not current architecture.",
    inventorySha: "UNKNOWN",
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote:
      "fleet.yaml lists diagnostic-clank as SUPPORTING_SYSTEM with deployment_state UNKNOWN. The 2026-08-22 inventory does not pin a Diagnostic deploy SHA.",
    repoHead: "3667af02c8dd33503ce75461ec2974d42f2f1d4c",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote:
      "HEAD of default branch diagnostic-clank-2026-08 (not main), captured 2026-09-14. Unchanged vs v0.1. 3667af0 is the Tablet observer adapter. Control-plane commit, not Tablet production membership.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "observation",
    presence: "github",
    postV01: false,
    ownsQuestion: "Which Clanks exist, on which host, at which inventory SHA, in which adapter language?",
    doesNotOwn: "Harvest clock, Fleet Laws text, development sessions, collection itself.",
    evolution: "Default branch unchanged after v0.1. Census (ClankOps) later added identity vocabulary; it does not replace fleet.yaml as the 22 August inventory document.",
  },
  {
    id: "standards-clank",
    name: "Standards Clank",
    purpose: "Normative fleet standards: ratification, frozen domains, machine-readable profiles, conformance evidence, historical vs current truth.",
    sources: "Ratified standard texts, evidence facts/indexes, audit reports. Not collector HTML.",
    scheduling: "Not a collector. Closure campaign, not a harvest timer.",
    persistence: "Git-resident standards, profiles, exceptions, constitutions, evidence indexes. Not a newsroom SQLite.",
    host: "GitHub master. Not a Hetzner collector runtime.",
    status: "26 standards, 26 RATIFIED, 0 PROPOSED. Five populated/frozen domains: UI, Data/Ontology, Operations, Deployment, Collector UI Design. M58 STANDARDS_CLANK_COMPLETE_WITH_NON_BLOCKING_DEBT at 7c821ea (2026-09-05). Front-door README still saying 12/3 is stale — do not teach the banner as current.",
    limitation: "An implementation pattern shared by six repos is not a MUST unless the ratified text says so. Agents cannot self-ratify. Historical COM-001 9/9 live proofs are not current-canon live.",
    unresolved: "Non-blocking debt remains (that is what the verdict named). Live current-conformance of collectors after 2026-09-05: UNKNOWN without a new audit. This Handbook is not a standard.",
    motherclank: "Does not harvest. Motherclank may later observe conformance facts; it does not ratify.",
    asOf: "2026-09-14 (repo HEAD = 2026-09-05 closure)",
    confidence: "verified",
    staleNote: "README 12/3 vs 26/26 RATIFIED is a documentation drift inside Standards itself. Teach the M58 audit, not the banner.",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE,
    repoHead: "7c821ea974d8a58e7b049b1bee538a64cca43dc2",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE + " Default branch is master.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "standards",
    presence: "github",
    postV01: true,
    ownsQuestion: "What is law, what was ratified, and what conformance facts exist at a named SHA?",
    doesNotOwn: "Collection, harvest, development sessions, editorial HIT/MISS, runtime remediation, this Handbook's prose.",
    evolution: "Existed around the v0.1 freeze boundary; became a substantial system by 2026-09-05 closure. Not a strict post-v0.1 GitHub birth. Major system missing from Handbook v0.1.",
  },
  {
    id: "cvc-clank",
    name: "CVC Clank",
    purpose: "Reproducible validation of frozen evidence corpora and support-grade evidence packages. Operator-triggered ingest/review.",
    sources: "Frozen artefacts (42 on GitHub HEAD). Not live collector feeds.",
    scheduling: "Operator-triggered. Not a fleet harvest timer.",
    persistence: "Frozen corpus + validation outputs. Not participant SQLite.",
    host: "GitHub main 5328a3c (2026-08-30). Local Windows CVC may be ahead — this campaign could not inspect it. Verifier depends on non-portable Windows source paths.",
    status: "CVC_MISSION_COMPLETE_WITH_OPEN_EVIDENCE_BLOCKERS. Explicitly excluded from Handbook v0.1. Does not collect, promote, or enforce. Unmerged observer PRs (cvc#1, motherclank#1, diagnostic#9) are not current architecture.",
    limitation: "GitHub may trail local. Non-portable paths. Completeness of local CVC: UNKNOWN.",
    unresolved: "Whether local Desktop CVC is the real product: UNKNOWN in this Linux campaign. CVC Workbench is a separate local journalist tool, not this Clank.",
    motherclank: "Must not become an observer-by-unmerged-PR. Motherclank consumes Diagnostic adapters, not CVC.",
    asOf: "2026-09-14 (GitHub HEAD is 2026-08-30)",
    confidence: "verified",
    staleNote: "v0.1 freeze named CVC PR #5 as excluded. This card is a new teaching surface, not a merge of that PR.",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE + " CVC GitHub import landed around the freeze and was deliberately left out of v0.1.",
    repoHead: "5328a3cd4e06e1b9fd6ecf56250b4b5d8022d1e4",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "evidence-validation",
    presence: "github",
    postV01: true,
    ownsQuestion: "Does this frozen evidence package still validate, reproducibly?",
    doesNotOwn: "Collection, source promotion, Fleet Laws, harvest, editorial HIT/MISS.",
    evolution: "Imported to GitHub shortly before v0.1 freeze; excluded from v0.1 on purpose. v0.2 teaches it as a validator, not as an operationalised observer plane.",
  },
  {
    id: "clank-ledger",
    name: "Clank Ledger",
    purpose: "HIT/MISS, QC decisions, editorial outcomes, article performance — human usefulness as an append-only plane.",
    sources: "Operator/editorial records. External-reference seam for future integrations. Not collector health.",
    scheduling: "Not a collector scheduler. Review CLI + server-rendered UI.",
    persistence: "SQLite / SQLAlchemy / Alembic. Append-only decision/outcome history.",
    host: "No production deploy evidenced. Default branch is Jules M0, not main — there is no main.",
    status: "M0 HIT/MISS/QC/editorial/article-performance. HEAD 2c31787 (2026-08-31) on jules-m0-foundation-9044736841197359665. AST-guarded against other Clanks. Jules branch IS the product.",
    limitation: "No main. M0 only. Do not treat later imagined integrations as shipped.",
    unresolved: "Whether a main branch will exist is an operator decision. Usefulness metrics beyond M0: UNKNOWN.",
    motherclank: "Does not harvest collectors. A technically healthy collector can still be a Ledger MISS.",
    asOf: "2026-09-14 (repo HEAD is 2026-08-31 Jules M0)",
    confidence: "verified",
    staleNote: "Strict post-v0.1 GitHub birth. No main. Do not 'helpfully' fill origin/main.",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE,
    repoHead: "2c31787904c270f9423dd22de4c95e669ba26a67",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote:
      "HEAD of Jules M0 branch jules-m0-foundation-9044736841197359665 captured 2026-09-14. This repository has no main. The Jules branch is the product. Not a host checkout. Not production.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "editorial",
    presence: "github",
    postV01: true,
    ownsQuestion: "Was this output useful to a human editor — HIT, MISS, QC, outcome?",
    doesNotOwn: "Collector correctness, fleet health, novelty classification, source admission.",
    evolution: "Created 2026-08-31 after Handbook v0.1 freeze. One of two strict post-v0.1 GitHub births (with ClankOps).",
  },
  {
    id: "clankops",
    name: "ClankOps",
    purpose: "Development control plane: census, Mission/Session lifecycle, Git/CI/deploy observations, attention, resume packets, managed-agent provenance. Not fleet runtime health.",
    sources: "Local workspace observations, Git/GitHub, CI, process lifecycle. Census of 2026-09-09 is RECONSTRUCTED, not omniscient live history.",
    scheduling: "Not a collector. Managed launch gate. Python 3.14+, local SQLite.",
    persistence: "Append-only development ledger (Foundation 0, hardened 0.1). Derived projections (attention queue, resume packets) are not the ledger.",
    host: "No production deploy evidenced. GitHub main 4467c13 (2026-09-14 Foundation 10 / PR #11).",
    status: "Foundations 0–10: append-only ledger, census/identity, Mission, Session/checkpoint/handoff, fleet adoption, read-only Terminal, Git/GitHub reconciliation, CI evidence + artefact attachment, deployment/runtime provenance, derived attention + freshness + resume packets, agent admission + managed launch + launcher provenance + managed process-exit observability.",
    limitation: "Census source=RECONSTRUCTED. Observation ≠ permission. Freshness metadata ≠ truth. Attention queue ≠ health score. Resume packet ≠ LLM summary. Launcher/actor ≠ authority. Process exit ≠ handoff.",
    unresolved: "Not a Hetzner runtime. Whether every Foundation is adopted across the fleet: UNKNOWN. Local-only systems in the census remain local-only until evidence says otherwise.",
    motherclank: "Sibling question, not a successor. Motherclank photocopies collector state. ClankOps photocopies development state.",
    asOf: "2026-09-14 (GitHub main = Foundation 10)",
    confidence: "verified",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE + " ClankOps GitHub repo created after the freeze (visible ~2026-09-09).",
    repoHead: "4467c137f5c5db1a10ee29484628677bcd3c3284",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: HEAD_NOTE,
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "development-control",
    presence: "github",
    postV01: true,
    ownsQuestion: "What is being developed, in which Mission/Session, with what Git/CI/process evidence, and what should a new agent resume?",
    doesNotOwn: "Collector SQLite, Fleet Laws ratification, editorial HIT/MISS, model quota, live fleet harvest.",
    evolution: "Census listed it PROBABLE local-only on 2026-09-09; GitHub main now holds Foundations through F10 (4467c13). One of two strict post-v0.1 GitHub births.",
  },
  {
    id: "quartermaster",
    name: "Quartermaster Clank",
    purpose: "Model/resource/quota awareness and recommendations. Roster/burn/resource layer — not fleet health, not development-state ownership.",
    sources: "Token/model usage (census: wrapper around Annihilater/token-stats, reported ahead 12 and dirty). Not collector feeds.",
    scheduling: "UNKNOWN. No git. No GitHub repository found under this identity.",
    persistence: "UNKNOWN. Local folder only, per reconstructed census.",
    host: "LOCAL-ONLY. Census path C:\\Users\\anil\\Desktop\\Quartermaster Clank. That Windows path is not in this Linux campaign. Do not invent a remote URL.",
    status: "PROBABLE local-only per ClankOps census 2026-09-09 (source=RECONSTRUCTED). Not found on GitHub. Architecture, maturity, and current code: UNKNOWN in this campaign.",
    limitation: "This card is a teaching stub with incomplete evidence, not a fake architecture diagram. Wrapper+token-stats is census reconstruction, not a verified design review.",
    unresolved: "Everything operational. Inspect the Windows folder before claiming APIs, deploys, or completeness.",
    motherclank: "Does not decide fleet health. Motherclank must not grow quota opinions.",
    asOf: "2026-09-14 (census 2026-09-09; local path not inspected)",
    confidence: "incomplete",
    staleNote: "Strict post-v0.1 logical birth. Not a GitHub birth. Presence is census-PROBABLE, not VERIFIED.",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE,
    repoHead: "LOCAL-ONLY-NO-GITHUB-REPO",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote:
      "ClankOps census 2026-09-09 listed a probable local folder with no git. This Linux campaign could not inspect C:\\Users\\anil\\Desktop\\Quartermaster Clank. Not a GitHub repository. Not a deployed SHA.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "resource",
    presence: "local-only",
    postV01: true,
    ownsQuestion: "What model/quota/resource is being burned, and what should be recommended — without owning fleet truth?",
    doesNotOwn: "Fleet health, harvest, Missions, standards, editorial HIT/MISS, collection.",
    evolution: "Appears after v0.1 freeze as a local system in the 9 September census. Treat as incomplete until the folder is read.",
  },
  {
    id: "unified-clank-platform",
    name: "Unified Clank Platform (historical)",
    purpose: "The 4 August hoped-for unification. Not the current control/governance architecture.",
    sources: "Historical repo unified-clank-platform (created 2026-08-04 with oem-radar, FGT, clank-architecture). ADR-0001 proposed supersession.",
    scheduling: "Not a live fleet scheduler.",
    persistence: "Git history. Not authoritative collector state.",
    host: "GitHub. Last visible HEAD around 2026-08-21 (56bf7f7 in v0.1 notes). Not re-probed as a runtime.",
    status: "Historical / non-canonical. Diagnostic README still branded this name in places — naming drift, not a revival.",
    limitation: "Teaching this as current architecture would erase the reason Motherclank, Diagnostic, Standards, ClankOps, Ledger, and Quartermaster split apart.",
    unresolved: "Whether anything still runs under this name: UNKNOWN. Do not assume deployed.",
    motherclank: "Not a parent. Unification was hoped for before it was earned (h-first-repos).",
    asOf: "2026-09-14 (historical identity; not a live card)",
    confidence: "inferred",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE + " Created 2026-08-04 but not a 2026-08-22 fleet.yaml collector instance.",
    repoHead: "56bf7f7-SEE-NOTE-NOT-A-LIVE-PROBE",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote:
      "v0.1 notes cited 56bf7f7 (Aug 21). This campaign did not re-fetch a full SHA. Treat as historical identity, not current HEAD evidence.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "historical",
    presence: "historical",
    postV01: false,
    ownsQuestion: "What did 'unify everything' look like before the fleet earned separate planes?",
    doesNotOwn: "Anything current.",
    evolution: "Remains historical. v0.2 names it so readers do not confuse README banners with architecture.",
  },
  {
    id: "editorial-assist",
    name: "Editorial Assist / Story Intelligence (local-probable)",
    purpose: "Local probable journalist-assist tool. Not a collector Clank. Not Clank Ledger.",
    sources: "Census PROBABLE, local, no git. Not inspected this campaign.",
    scheduling: "UNKNOWN.",
    persistence: "UNKNOWN.",
    host: "Local-only per reconstructed census. Path not in this Linux sandbox.",
    status: "PROBABLE local. Do not count as a post-v0.1 birth Clank on the same footing as Ledger/ClankOps/Quartermaster until inspected.",
    limitation: "Teaching-only identity so it is not silently merged into CVC, Ledger, or a collector.",
    unresolved: "Everything. Incomplete.",
    motherclank: "Not a participant collector.",
    asOf: "2026-09-14 (census 2026-09-09; not inspected)",
    confidence: "incomplete",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE,
    repoHead: "LOCAL-ONLY-NO-GITHUB-REPO",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: "Census PROBABLE local, no git. Not inspected. Not a GitHub repository.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "local-probable",
    presence: "local-only",
    postV01: false,
    ownsQuestion: "UNKNOWN until the local folder is read.",
    doesNotOwn: "Do not assume collection, HIT/MISS, or CVC validation.",
    evolution: "Named so v0.2 does not pretend the census did not see it, and does not promote it to a birth Clank.",
  },
  {
    id: "cvc-workbench",
    name: "CVC Workbench (local-probable, not CVC Clank)",
    purpose: "Separate local probable journalist workbench. Not CVC Clank. Not a validator corpus.",
    sources: "Census PROBABLE local. Not inspected.",
    scheduling: "UNKNOWN.",
    persistence: "UNKNOWN.",
    host: "Local-only. Do not collapse into cvc-clank GitHub 5328a3c.",
    status: "Distinct identity. Collapsing it into CVC is the mistake this card exists to prevent.",
    limitation: "Incomplete. Local path unavailable.",
    unresolved: "Everything operational.",
    motherclank: "Not a participant.",
    asOf: "2026-09-14 (census 2026-09-09; not inspected)",
    confidence: "incomplete",
    inventorySha: ABSENT_INV,
    inventoryAsOf: INVENTORY_AS_OF,
    inventoryNote: ABSENT_NOTE,
    repoHead: "LOCAL-ONLY-NO-GITHUB-REPO",
    repoHeadAsOf: REPO_HEAD_AS_OF,
    repoHeadNote: "Separate from cvc-clank. Census PROBABLE. Not inspected.",
    liveDeployedSha: LIVE_UNKNOWN,
    layer: "local-probable",
    presence: "local-only",
    postV01: false,
    ownsQuestion: "UNKNOWN. Whatever it is, it is not CVC's frozen corpus.",
    doesNotOwn: "CVC validation, collection, standards.",
    evolution: "Named to keep CVC Clank's GitHub corpus from absorbing a different local tool.",
  },
];
