import type { HistoryEntry, HistoryPhase } from "../lib/handbook/schema.ts";

export const PHASES: HistoryPhase[] = [
  {
    id: "p-origin",
    title: "Origin: independent collectors",
    dateRange: "2026-08-03 to 2026-08-10",
    summary:
      "The GitHub account appears. OEM Radar, Free Game Tracker, unified-clank-platform, and clank-architecture land on 4 August. Consumer-device Clanks and news wires follow within a week. There is no fleet supervisor.",
    components: ["oem-radar", "free-game-tracker", "watch-clank", "smartwatch-clank", "smartphone-clank", "feature-phone-clank", "chinese-tech-wire", "korean-tech-wire", "semiconductor-intelligence", "clank-architecture"],
    responsibilities: "Each Clank collects, stores, and (sometimes) notifies for one domain. Architecture repo is a governance notebook, not a runtime.",
    dataFlow: "Source HTML/RSS → parser → SQLite. No shared database.",
    scheduling: "Local one-shot CLIs plus OS schedulers (Windows Task Scheduler, later cron/systemd). No single fleet clock.",
    storage: "Per-Clank SQLite. Baseline commits are recoverability checkpoints, not proof of design.",
    alerting: "Optional Discord webhooks. Several Clanks have no alert path by policy.",
    qc: "None as a fleet function. Editorial judgment is the human reading Discord or a local dashboard.",
    fleetSupervision: "None. Local dashboards and operator memory.",
    whyThisLayer:
      "The newsroom needed sensors for OEM hardware, free games, watches, phones, and regional tech wires. Independent Python collectors were the fastest way to start. Unification was not yet a problem because there was not yet a fleet.",
    before:
      "No hosted Git identity for the fleet. No collectors. The newsroom had no automated sensors.",
    failurePressure:
      "Editors needed OEM, free-game, watch, phone, and regional-wire coverage that a human refresh could not keep up with. Unification was hoped for (unified-clank-platform) before it was earned.",
    newAbstraction:
      "One independent Python collector per domain, each with its own SQLite notebook. clank-architecture is a governance notebook, not a runtime.",
    newRule:
      "None fleet-wide. Each Clank owns its collection, storage, and optional Discord path. There is no supervisor and no shared database.",
    resultingArchitecture:
      "A bag of sensors. Account anil-ganti-nbc appears 2026-08-03. OEM Radar, Free Game Tracker, unified-clank-platform, and clank-architecture land 4 August; consumer Clanks and wires follow 8–10 August.",
    unresolvedLimitations:
      "No fleet inventory, no shared health language, no host identity, no single clock. A collector that only runs when a laptop is open is not yet a newsroom sensor.",
    confidence: "verified",
  },
  {
    id: "p-portability",
    title: "Portability: Docker, NAS, Hetzner",
    dateRange: "2026-08-08 to 2026-08-19",
    summary:
      "Collectors leave the laptop. Docker images, runtime identity, backup scripts, and host-specific handoffs appear. Each Clank becomes a separate runtime with local state.",
    components: ["Docker images", "Hetzner host", "NAS (FGT/OEM lore)", "Windows Task Scheduler remnants", "per-Clank volumes"],
    responsibilities: "Move collection off the operator's workstation without rewriting collectors.",
    dataFlow: "Same pipelines; data now lives in container volumes and host paths. Local checkout databases become stale copies.",
    scheduling: "Host cron, systemd user timers, leftover Windows tasks. Duplicate authorities start to appear.",
    storage: "SQLite in named volumes. Backup/restore scripts exist in some repos; scheduling of those scripts is often UNKNOWN.",
    alerting: "Production Discord webhooks move to Hetzner. Dual-host delivery becomes a real risk.",
    qc: "Still human, still per-Clank.",
    fleetSupervision: "Still none. Field-test launchers become an acceptance gate.",
    whyThisLayer:
      "A collector that only runs when the laptop is open cannot be a newsroom sensor. Portability created the first real deployment identity problems: which SHA is running, which database is production, which scheduler is live.",
    before:
      "Collectors ran from a workstation. Local checkout databases were the only copies. Scheduling was a laptop habit (Windows Task Scheduler, one-shot CLIs).",
    failurePressure:
      "A newsroom sensor that sleeps when the laptop lid closes is not a sensor. Docker images, NAS lore, and a Hetzner host appear so collection can outlive the operator's session.",
    newAbstraction:
      "Container images, named volumes, host-specific working directories, backup/restore scripts in some repos. Each Clank becomes a separate runtime with local state.",
    newRule:
      "None codified yet. Dual-host delivery (Hetzner webhook plus leftover Windows tasks) becomes a real risk rather than a written law.",
    resultingArchitecture:
      "Same parsers, new addresses. Data lives in container volumes and host paths. Local checkout databases start to go stale. Duplicate scheduler authorities start to appear.",
    unresolvedLimitations:
      "Which SHA is running, which database is production, and which scheduler is live are now real questions. Backup scripts existing in git is not proof they are scheduled. Human review still flags this phase for possible over-read of 'portability' as a completed migration.",
    confidence: "verified",
  },
  {
    id: "p-expansion",
    title: "Expansion, field test, and first scars",
    dateRange: "2026-08-10 to 2026-08-21",
    summary:
      "Source sets explode. False novelty, empty catalogues, 403s, dual schedulers, and 'green build ≠ owner can launch' show up as named failures. Diagnostic Clank is created as a read-only control-plane prototype.",
    components: ["watch-clank source expansion", "smartwatch Stage A–C", "KTW editorial sources", "oem-radar BANKAI soaks", "diagnostic-clank", "tablet-clank"],
    responsibilities: "Cover more of the market. Prove recall. Survive field tests.",
    dataFlow: "More sources, same SQLite notebooks. Baseline floods and FIRST_SEEN inversions pollute events.",
    scheduling: "Per-source timers, soak runners, dual lanes. Recurrence is often assumed from a first fire.",
    storage: "Authoritative SQLite plus experimental volumes that must not mix.",
    alerting: "Notification paths proliferate and sometimes go silent (casio_multi, FGT subscription blackout).",
    qc: "Watch begins human review dispositions. Others remain dashboard/Discord.",
    fleetSupervision: "Diagnostic Clank inventories the fleet; it does not supervise runtime.",
    whyThisLayer:
      "Coverage pressure produced the failure classes the later laws exist to name: FIRST_SEEN ≠ new, HTTP 200 ≠ useful, first fire ≠ cadence, green tests ≠ mission recall.",
    before:
      "Few sources per Clank. Failure was still anecdotal. Membership of the fleet was a folder listing and operator memory.",
    failurePressure:
      "Source sets explode. False novelty, empty catalogues, 403s, dual schedulers, and 'green build ≠ owner can launch' show up as named failures. A directory sweep will later omit Tablet (L-FLEET-001).",
    newAbstraction:
      "Diagnostic Clank (17 Aug) as a read-only control-plane prototype: inventory and adapters, not a collector and not a supervisor.",
    newRule:
      "None fleet-wide yet. Per-Clank scars accumulate (BANKAI soaks, Watch FIRST_SEEN, SK hynix host-block) without a shared law text.",
    resultingArchitecture:
      "More sources, same SQLite notebooks. Diagnostic Clank inventories the fleet; it does not supervise runtime. Tablet exists as a repo and can still vanish from a folder listing.",
    unresolvedLimitations:
      "FIRST_SEEN ≠ new, HTTP 200 ≠ useful, first fire ≠ cadence, green tests ≠ recall. No camera, no freeze, no promotion record requirement.",
    confidence: "verified",
  },
  {
    id: "p-phase0",
    title: "Phase 0 freeze and Fleet Laws",
    dateRange: "2026-08-21 to 2026-08-22",
    summary:
      "Promotion is frozen. Governance is assigned to clank-architecture; inventory to diagnostic-clank. Eight binding Fleet Laws are codified from hostile-audit specimens.",
    components: ["clank-architecture", "FLEET_LAWS.md", "NO_PROMOTION_POLICY.md", "conformance/test_fleet_laws.py", "diagnostic-clank fleet.yaml"],
    responsibilities: "Stop promoting until the fleet can tell the truth about itself.",
    dataFlow: "Unchanged collectors. New: a written law that events, health, novelty, and delivery are different planes.",
    scheduling: "Law 5: exactly one enabled scheduler per Clank-lane.",
    storage: "Law 7: one cross-process lock per SQLite file, dashboards included.",
    alerting: "Law 4: fail-closed unknown reasons. Law 8: no production source without a promotion record.",
    qc: "Named as a plane, not yet a fleet function.",
    fleetSupervision: "Still missing — laws without a harvester.",
    whyThisLayer:
      "The audit showed the same lies in ten dialects. Writing them down as testable invariants was cheaper than rewriting every collector.",
    before:
      "Same failure classes in ten dialects. Promotion still possible. Inventory and governance lived in the same informal operator memory.",
    failurePressure:
      "Hostile-audit specimens (FGT fresh-DB burst, Timex FIRST_SEEN, dual scheduler lanes, HTTP 200+0, dashboard lock bypass) made another silent promotion too expensive.",
    newAbstraction:
      "Fleet Laws as named, testable invariants. Governance assigned to clank-architecture; inventory assigned to diagnostic-clank. Hermetic conformance suite (test_fleet_laws.py).",
    newRule:
      "Eight binding laws (d046d54, 2026-08-21). Law 9 deferred — default branch trailing production needs inventory machinery that did not exist at codification. Promotion frozen (NO_PROMOTION_POLICY.md).",
    resultingArchitecture:
      "A written constitution without a camera. Collectors unchanged. Events, health, novelty, and delivery named as different planes. Still no fleet-wide harvester.",
    unresolvedLimitations:
      "Laws without a harvester can be ignored on the host. Live SHA, scheduler authority, and backup state remain unenforced until someone can read them without guessing.",
    confidence: "verified",
  },
  {
    id: "p-motherclank",
    title: "Motherclank M0–M4",
    dateRange: "2026-08-22",
    summary:
      "ADR-0002 creates a separate read-only supervisory layer. Motherclank harvests adapter snapshots, synthesizes UNKNOWN-honest health, detects anomalies, and proposes — it never remediates. Diagnostic Clank keeps the adapter plane.",
    components: ["motherclank", "diagnostic-clank adapters", "fleet.yaml inventory", "user systemd harvest timer"],
    responsibilities: "Observe the fleet without becoming a second writer, scheduler, or notifier.",
    dataFlow: "Read-only copies of Clank state → adapters → hash-chained JSONL snapshots + Markdown report. Clank SQLite remains authoritative.",
    scheduling: "One fixed-clock user timer. Dual timers per lane would violate Law 5.",
    storage: "Derived snapshots only. Disposable. Rollback = disable timer and delete var/.",
    alerting: "None. Recommendations are text.",
    qc: "M4 may ingest disposition corpora read-only.",
    fleetSupervision: "First fleet-wide single view. M5 mutation is explicitly forbidden.",
    whyThisLayer:
      "Local dashboards could not be trusted: timers that fired without starting, 200-with-zero, dual schedulers, soaks with no promotion record. A camera was needed that could not also hold the keys.",
    before:
      "Fleet Laws on paper. Local dashboards and operator memory as the only fleet picture. Diagnostic Clank owns adapters but nothing harvests them on a clock.",
    failurePressure:
      "Timers that fired without starting, HTTP 200 with zero items, dual schedulers, soaks with no promotion record. A supervisor that can write would be a second Clank with blast radius over the whole fleet.",
    newAbstraction:
      "Motherclank (ADR-0002, b341b0f, 2026-08-22): a separate read-only supervisory layer. Adapters stay on Diagnostic Clank. Snapshots are derived JSONL + Markdown. Clank SQLite stays authoritative.",
    newRule:
      "Observe, synthesize, detect, recommend, learn. Never remediate in M0–M4. One fixed-clock user timer. Dual timers per lane would violate Law 5. M5 mutation forbidden until a future ADR.",
    resultingArchitecture:
      "Clanks write notebooks. Diagnostic Clank translates. Motherclank photocopies. Operators read proposals. Rollback = disable timer and delete var/.",
    unresolvedLimitations:
      "Cannot see what adapters cannot read. Live timer enablement UNKNOWN. Host var/ batches for 22–23 Aug were not recovered. Repo HEAD 7cee2f8 is not proof the harvest is healthy.",
    confidence: "verified",
  },
  {
    id: "p-scars",
    title: "Silent outage and volume loss",
    dateRange: "2026-08-22 to 2026-08-24",
    summary:
      "Two incident families in one window: a stash -u recreation of root-owned logs/ stopped collectors before they started (~36h), then a destructive operator error deleted live volumes. Smartwatch restored with a gap; feature-phone began a new epoch.",
    components: ["oem-radar", "smartwatch-clank", "feature-phone-clank", "cron", "Docker volumes", "Motherclank continuity seeds"],
    responsibilities: "Survive human/agent destructive error and prove what actually ran.",
    dataFlow: "Interrupted. Then rewritten by restore vs new-epoch. Organic recovery narratives are forbidden.",
    scheduling: "Cron still elapsed during the materialization gap. Invocation was not execution.",
    storage: "SQLite volumes revealed as irreplaceable observational memory.",
    alerting: "Silent. No failure records could exist if the process never started.",
    qc: "Unmeasurable on affected lanes; UNKNOWN, not zero.",
    fleetSupervision: "Motherclank could not yet name MATERIALIZATION_GAP; STALE_RUN inference was the wrong shape.",
    whyThisLayer:
      "These two days produced continuity, survivability, liveness, and runtime-state-separation ADRs. The architecture after 24 August is a scar map.",
    before:
      "Fired timer meant ran. Empty volume looked like a crash. A restore looked like a rewind of the world. Motherclank could not yet name MATERIALIZATION_GAP.",
    failurePressure:
      "Two incident families in one window: stash -u recreated root-owned logs/ and collectors never started (~36h), then a destructive operator error deleted live volumes. Smartwatch restored with a gap; feature-phone began a new epoch.",
    newAbstraction:
      "MATERIALIZATION_GAP as an execution-plane fact. RESTORED_HISTORY + GAP_KNOWN versus NEW_EPOCH. Continuity seeds rather than reconstructed syslog.",
    newRule:
      "Organic recovery narratives are forbidden. Invocation is not execution. Cron elapsed during the gap; that is not collector regression. UNKNOWN, not zero, when QC is unmeasurable.",
    resultingArchitecture:
      "A scar map that the next day's ADRs will name. Motherclank continuity seeds (INC-20260822-23, INC-20260823) exist in git. Host syslog and var/ batches from the window do not.",
    unresolvedLimitations:
      "Syslog/journal for 22–23 Aug unavailable from current artefacts. Motherclank live var/ batches BLOCKED. FPC pre-epoch-2 state irrecoverable. Do not reconstruct those as fact.",
    confidence: "verified",
  },
  {
    id: "p-continuity",
    title: "Continuity, liveness, survivability",
    dateRange: "2026-08-24",
    summary:
      "ADR-0006 (epochs), 0007 (destructive safety), 0008 (execution liveness / MATERIALIZATION_GAP), 0009 (runtime state vs source tree). Golden incidents GIC-01–25. Archaeology report. Canonical architecture v0.2.",
    components: ["motherclank continuity/liveness/survivability modules", "G1–G8 fixtures", "ACT-011 restore drills", "clank-architecture ADRs"],
    responsibilities: "Name states that used to be collapsed: restored vs new-epoch, fired vs started vs useful work, backup present vs restore-verified.",
    dataFlow: "Append-only ContinuityEvent registry. Derived claims carry epoch identity.",
    scheduling: "Six-stage execution-liveness model. INTENTIONALLY_DORMANT is not MISSING_RUN (Tablet).",
    storage: "Protection classes proposed. Durable off-host copies remain OPEN.",
    alerting: "Still Motherclank-propose only.",
    qc: "Soak opened as a separate axis from Clank maturity.",
    fleetSupervision: "Observer contract v0.2. Capability is a six-state vocabulary, not a boolean.",
    whyThisLayer:
      "Without these names, a restored database looks like a rewind, an empty new epoch looks like a market crash, and a fired timer looks like a healthy collector.",
    before:
      "Collapsed words: fired=ran, restore=rewind, empty=crash, backup-script-exists=survivable, INTENTIONALLY_DORMANT confused with MISSING_RUN.",
    failurePressure:
      "22–23 August destroyed those collapses. ACT-011 had to prove a restore, not a rumour. Tablet's stale soak unit had to yield dormant, not missing.",
    newAbstraction:
      "ADR-0006 epochs, 0007 destructive safety, 0008 six-stage execution liveness, 0009 runtime state vs source tree. Golden incidents GIC-01–25. Capability as a six-state vocabulary, not a boolean.",
    newRule:
      "Absence of evidence is UNKNOWN, never NO. INTENTIONALLY_DORMANT is not MISSING_RUN. A backup never restored is a rumour. Durable off-host copies remain OPEN — ACT-011 scratch is not Layer C.",
    resultingArchitecture:
      "Append-only ContinuityEvent registry. Derived claims carry epoch identity. Observer contract v0.2. Two lanes have restore-verified recovery points on temporary_scratch only.",
    unresolvedLimitations:
      "Whether scratch files still exist today: UNKNOWN. Layer C off-host backup: DESIGNED ONLY. Scheduler-trace: supported_unconfigured fleet-wide.",
    confidence: "verified",
  },
  {
    id: "p-qc-onboard",
    title: "Human QC, dogfood onboarding, freeze",
    dateRange: "2026-08-25 to 2026-08-26",
    summary:
      "Watch QC flood teaches that catalogue-pass is an invocation fact. CTW and Semiconductor Intelligence are onboarded as observer adapters and scored against the playbook. Architecture v0.3 is frozen.",
    components: ["watch-clank QC", "CTW adapter", "SI adapter", "ONBOARDING.md", "FLEET_CAPABILITY_MATRIX.md"],
    responsibilities: "Prove a new Clank can join as an observer without Motherclank growing Clank-name conditionals.",
    dataFlow: "Typed EvidenceEnvelope (ADR-0014). Participant-native confidence preserved verbatim.",
    scheduling: "Scheduler-trace capability remains supported_unconfigured fleet-wide.",
    storage: "Unchanged. Survivability still unproven except smartwatch + feature-phone recovery points.",
    alerting: "Unsupported or undeployed on several lanes, honestly labelled.",
    qc: "Watch queue accounting (639 / 580 / 41). Review mode three-valued.",
    fleetSupervision: "v0.3 frozen 2026-08-25: no speculative core redesign until a real participant proves the contract insufficient.",
    whyThisLayer:
      "Onboarding is how the architecture is tested. Dogfooding the playbook on CTW caught a guessed refresh path that review could not see.",
    before:
      "Observer contract v0.2 untested on a real new Clank. Catalogue-pass could still be inferred from output size. Motherclank risked growing Clank-name conditionals.",
    failurePressure:
      "Watch QC flood: validation runs counted as catalogue passes (639 / 580 / 41). CTW and Semiconductor Intelligence needed to join as observers without rewriting Motherclank.",
    newAbstraction:
      "Typed EvidenceEnvelope (ADR-0014). Participant-native confidence preserved verbatim. ONBOARDING.md scorecard. Catalogue-pass is an invocation fact (max_items), never inferred from how many items came back.",
    newRule:
      "v0.3 frozen 2026-08-25: no speculative core redesign until a real participant proves the contract insufficient. Guessed refresh paths are forbidden (7f977d6 after CTW dogfood).",
    resultingArchitecture:
      "Watch QC live. CTW and SI onboarded as observers. FGT registry filename drift caught during the same dogfood. Architecture freeze is a test, not a claim of health.",
    unresolvedLimitations:
      "Scheduler-trace remains supported_unconfigured. CTW live cron scored LIVE_EVIDENCE_REQUIRED. Survivability still unproven except two recovery points on scratch.",
    confidence: "verified",
  },
  {
    id: "p-current",
    title: "Current mature-ish fleet",
    dateRange: "2026-08-26 to 2026-08-27",
    summary:
      "A heterogeneous, law-bound, observer-supervised fleet. Promotion remains frozen. Durable off-host backups are still a blocker. The Clank Systems Handbook is created so the operator can explain the process without collapsing it into 'I pasted one AI output into another.'",
    components: ["active Clanks", "Motherclank harvest", "Diagnostic Clank adapters", "Dead Air University", "Clank Systems Handbook"],
    responsibilities: "Keep collecting; keep observing; do not auto-promote; teach the operator the real engineering process.",
    dataFlow: "Clank SQLite authoritative → adapter facts → Motherclank derived snapshots. Handbook is historical evidence, not SRS.",
    scheduling: "Per-Clank single authority, plus one Motherclank harvest timer.",
    storage: "Per-Clank SQLite. Two lanes have restore-verified recovery points on temporary scratch only.",
    alerting: "Mixed: some active, some unsupported_by_policy, some supported_undeployed.",
    qc: "Watch live; smartphone writer added; KTW feedback under RunLock; others unsupported or unverified.",
    fleetSupervision: "Motherclank M0–M4. M5 still requires a future ADR.",
    whyThisLayer:
      "This is not a finished platform. It is a fleet that can admit UNKNOWN, that remembers some of its scars as fixtures, and that still cannot survive another volume deletion on most lanes.",
    before:
      "Architecture still moving. Operator could not yet explain the process without collapsing it into 'I pasted one AI output into another.' Live host cells still un-probed.",
    failurePressure:
      "Repo HEADs keep moving (Windows launchers, QC writers, flock repairs) while the last fleet inventory stays 2026-08-22. Teaching GitHub=production would be a new Law 6 violation.",
    newAbstraction:
      "Clank Systems Handbook as historical evidence, not SRS. DAU retains mastery/SRS. Practice-shaped labs here do not write mastery. Fleet teaching snapshot shows inventory SHA vs repo HEAD vs live UNKNOWN as three columns.",
    newRule:
      "Promotion remains frozen. UNKNOWN stays UNKNOWN. GitHub HEAD is not production. ACT-011 scratch is not Layer C. This Handbook must not fold into DAU.",
    resultingArchitecture:
      "A heterogeneous, law-bound, observer-supervised fleet plus a literacy app. M0–M4 implemented in git. M5 still requires a future ADR.",
    unresolvedLimitations:
      "Every live Law 6 cell remains UNKNOWN. Durable off-host backups OPEN. Watch production DB path UNKNOWN. Whether 06:15 UTC Motherclank timer is enabled: UNKNOWN. cpu-memory SME sign-off on DAU Worlds is a separate repo's pending item, not a fleet fact.",
    confidence: "verified",
  },
];

function e(
  id: string,
  rest: Omit<HistoryEntry, "id">,
): HistoryEntry {
  return { id, ...rest };
}

export const HISTORY: HistoryEntry[] = [
  e("h-github-account", {
    date: "2026-08-03",
    period: "2026-08-03",
    phaseId: "p-origin",
    systems: ["github.com/anil-ganti-nbc"],
    event: "GitHub account anil-ganti-nbc is created. Idea becomes a remote that can hold repositories.",
    before: "No hosted Git identity for the fleet.",
    change: "Account created_at 2026-08-03T08:56:41Z (GitHub user API).",
    why: "Collectors needed a shared remote so agent sessions and hosts could push and pull the same history.",
    evidence: [
      {
        id: "ev-gh-me",
        kind: "repo",
        repo: "anil-ganti-nbc",
        url: "https://github.com/anil-ganti-nbc",
        note: "User created_at 2026-08-03T08:56:41Z via GitHub API.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["github", "repository", "origin"],
    lawIds: [],
    incidentIds: [],
    laterConsequence: "Every later SHA, PR, and host checkout is relative to this remote.",
    confidence: "verified",
  }),
  e("h-first-repos", {
    date: "2026-08-04",
    period: "2026-08-04",
    phaseId: "p-origin",
    systems: ["oem-radar", "free-game-tracker", "unified-clank-platform", "clank-architecture"],
    event: "First four Clank-related repositories appear on GitHub the same morning.",
    before: "No versioned project boxes.",
    change:
      "oem-radar 09:15Z (import/pilot), free-game-tracker 09:17Z, unified-clank-platform 09:19Z, clank-architecture 09:52Z with initial baseline commit b91c156.",
    why: "OEM hardware and free-game detection were the first newsroom sensors. Architecture and a 'unified platform' idea were created the same day — unification was hoped for before it was earned.",
    evidence: [
      {
        id: "ev-oem-created",
        kind: "repo",
        repo: "anil-ganti-nbc/oem-radar",
        note: "created_at 2026-08-04T09:15:02Z. Description: oem radar before discount tracker nad new oems.",
        status: "verified",
      },
      {
        id: "ev-arch-init",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "b91c156f9eb5fa092892a602a8dba445c2d06b41",
        note: "Initial architecture baseline and implementation history, 2026-08-04T09:52:48Z.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-architecture", sha: "b91c156f9eb5fa092892a602a8dba445c2d06b41", note: "architecture baseline" },
    ],
    conceptIds: ["repository", "commit", "collector"],
    lawIds: [],
    incidentIds: [],
    laterConsequence: "unified-clank-platform is later proposed for supersession (ADR-0001); collectors remain independent repos.",
    confidence: "verified",
  }),
  e("h-consumer-clanks", {
    date: "2026-08-09",
    period: "2026-08-08 to 2026-08-10",
    phaseId: "p-origin",
    systems: ["watch-clank", "smartwatch-clank", "smartphone-clank", "feature-phone-clank", "chinese-tech-wire", "semiconductor-intelligence", "korean-tech-wire"],
    event: "Consumer-device Clanks and regional wires proliferate. Many collectors, not yet a supervisor.",
    before: "Two product sensors (OEM Radar, FGT) plus architecture notes.",
    change:
      "CTW 14:28Z, watch-clank 14:29Z, smartwatch-clank 14:29Z, smartphone-clank 14:28Z, feature-phone + SemInt 15:00Z on 9 Aug; KTW bootstrapped 10 Aug 07:39Z. Archaeology names Git baselines such as Watch 14712d9 (8 Aug) and Smartwatch 4c115ce (9 Aug).",
    why: "Each product category and language market needed its own source adapters. Copying a working SQLite collector was faster than a platform.",
    evidence: [
      {
        id: "ev-archaeology-origin",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        sha: "431ba01efc156729574ffd9a470fb41f0a8aaa62",
        note: "§3 Origin/import phase: repos imported or bootstrapped 2026-08-04 through 2026-08-10.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["collector", "source-adapter", "database", "sqlite-authoritative"],
    lawIds: [],
    incidentIds: [],
    laterConsequence: "Heterogeneous semantics become the reason Motherclank must adapt rather than rewrite.",
    confidence: "verified",
  }),
  e("h-sqlite-authoritative", {
    date: "2026-08-09",
    period: "2026-08-04 to 2026-08-19",
    phaseId: "p-origin",
    systems: ["all collectors"],
    event: "SQLite becomes more than storage: it is the memory of what each collector has already seen.",
    before: "A scraper that printed results could forget yesterday.",
    change:
      "Every mature Clank persists observations in a local SQLite file. Novelty, baselines, outboxes, and QC all hang off that file. Archaeology: 'independently evolved, mostly SQLite-backed collectors'.",
    why: "Without durable local state, FIRST_SEEN and baseline are impossible, and a restart looks like the birth of the market.",
    evidence: [
      {
        id: "ev-sqlite-arch",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        note: "Executive finding: mostly SQLite-backed collectors; Motherclank must not centralize their databases.",
        status: "verified",
      },
      {
        id: "ev-adr2-sqlite",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "adr/0002-motherclank-supervisory-architecture.md",
        sha: "b341b0f0805ff747c6ada55888ce21476fc05386",
        note: "Clank SQLite remains authoritative; Motherclank never becomes the source of domain truth.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "b341b0f0805ff747c6ada55888ce21476fc05386" }],
    conceptIds: ["sqlite-authoritative", "database", "baseline", "authoritative-state", "derived-state"],
    lawIds: ["law-7"],
    incidentIds: ["inc-writer-lock"],
    laterConsequence: "Law 7 (writer lock) and ADR-0002 (Motherclank must not write Clank DBs) are the legal form of this decision.",
    confidence: "verified",
  }),
  e("h-portability", {
    date: "2026-08-12",
    period: "2026-08-08 to 2026-08-19",
    phaseId: "p-portability",
    systems: ["Hetzner", "NAS", "Docker", "Windows Task Scheduler"],
    event: "Collectors gain portable deployment machinery and host handoff support.",
    before: "Local Python CLIs and Windows scheduled tasks.",
    change:
      "Archaeology §3 in the 2026-08-24 report records a portability/deployment phase from 2026-08-08 through 2026-08-19 in which most collector repos gained Docker or external one-shot runners, source/image identity, backup artefacts, scheduler launchers, and host-specific handoff notes. That proves portable deployment machinery entered the git record. It does not prove those exact versions ran on a host then, or run now. FGT 473931e and Watch 12e8d3e / 938cc62 / f0b327a are archaeology-cited commits from that phase, not live deployed SHAs. The 2026-08-22 fleet inventory later recorded Watch f0b327a and FGT cec0346; that is a dated inventory snapshot, not a current runtime probe. Git-resident Docker, unit, and backup templates do not prove timer enablement, a running image, or a live volume. Current deployed SHAs remain UNKNOWN.",
    why: "A newsroom sensor has to run unattended. Moving hosts created the first SHA-vs-runtime and volume-vs-checkout problems.",
    evidence: [
      {
        id: "ev-port-phase",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        note: "§3 Portability/deployment phase 2026-08-08 through 2026-08-19. Named SHAs in that report are commit citations, not live deployed revisions.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["deployment", "container", "host", "volume", "head-vs-deployed", "production", "staging"],
    lawIds: ["law-6"],
    incidentIds: ["inc-deployed-sha"],
    whatFailed: "Container host names, lock semantics, duplicate scheduling, stale local DBs mistaken for production.",
    laterConsequence: "Law 6 provenance and Law 9 (deferred) trailing-checkout metric.",
    verification:
      "Portable deployment machinery in git / archaeology §3: VERIFIED. Named SHAs are archaeology citations, not live deployed SHAs. 2026-08-22 inventory (Watch f0b327a, FGT cec0346) is a dated snapshot, not a current probe. Live deployed SHA, enabled scheduler, and live volume: UNKNOWN.",
    residualRisk:
      "Current deployed SHAs remain UNKNOWN. Do not re-promote FGT 473931e or Watch 12e8d3e / 938cc62 / f0b327a as live. Later repo HEADs (Watch 9d812ed, FGT 45b47a5) stay out of this row.",
    confidence: "verified",
  }),
  e("h-diagnostic-clank", {
    date: "2026-08-17",
    period: "2026-08-17 to 2026-08-21",
    phaseId: "p-expansion",
    systems: ["diagnostic-clank"],
    event: "Diagnostic Clank is created as a deterministic read-only diagnostics, inventory, and adapter plane — not a Motherclank.",
    before: "No machine-readable fleet inventory. Membership could be guessed from a directory listing.",
    change:
      "Repo created 2026-08-17T21:01:36Z. Default branch diagnostic-clank-2026-08. Later owns fleet.yaml and the adapter plane Motherclank consumes (ADR-0001, ADR-0002).",
    why: "Someone had to know which Clanks existed, on which host, at which SHA, without taking their locks.",
    evidence: [
      {
        id: "ev-dc-created",
        kind: "repo",
        repo: "anil-ganti-nbc/diagnostic-clank",
        note: "created_at 2026-08-17T21:01:36Z. Description names read-only diagnostics, Agent Output Inbox, dynamic registry.",
        status: "verified",
      },
      {
        id: "ev-adr1",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "adr/0001-authority-and-phase0-freeze.md",
        sha: "515ed4b4c25d90758bd97fe4614ab08cfb38fc17",
        note: "Governance in clank-architecture; control plane and inventory in diagnostic-clank.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["diagnostic-clank", "contract", "source-adapter"],
    lawIds: [],
    incidentIds: ["inc-directory-sweep"],
    laterConsequence: "L-FLEET-001 (directory sweep omitted Tablet) becomes the membership rule: registry, not filesystem.",
    confidence: "verified",
  }),
  e("h-expansion-scars", {
    date: "2026-08-18",
    period: "2026-08-10 to 2026-08-21",
    phaseId: "p-expansion",
    systems: ["watch-clank", "oem-radar", "smartwatch-clank", "korean-tech-wire", "smartphone-clank"],
    event: "Source expansion produces the first named failure classes: false novelty, empty-but-200, dual schedulers, recall gaps.",
    before: "Collectors that 'worked' on a handful of sources.",
    change:
      "Watch adds Citizen/Seiko/Timex/specialists. Smartwatch Stages A–C. KTW Korean editorial sources (SK hynix 403 from Hetzner since 10 Aug). OEM Radar BANKAI soaks. DiagnosticBench cases L-WATCH-*, L-OEM-*, L-SMART-001.",
    why: "Coverage without novelty/health/delivery planes produces floods and false confidence.",
    evidence: [
      {
        id: "ev-exp-phase",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        note: "§3 Expansion, field test, and repair 2026-08-10 through 08-21. High-value failures listed.",
        status: "verified",
      },
      {
        id: "ev-lw001-hist",
        kind: "doc",
        repo: "anil-ganti-nbc/watch-clank",
        path: "WATCH_EXPANSION_FAILURE_CORPUS.md",
        note: "L-WATCH-001 FIRST_SEEN_BY_CLANK ≠ NEW_TO_MARKET, CONFIRMED FIXED.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["first-seen", "false-positive", "health-check", "mission-fail", "soak"],
    lawIds: ["law-1", "law-2", "law-3"],
    incidentIds: ["inc-qc", "inc-bankai", "inc-health-honesty"],
    laterConsequence: "These specimens are copied into Fleet Laws v1 on 21–22 August.",
    confidence: "verified",
  }),
  e("h-dual-scheduler", {
    date: "2026-08-21",
    period: "2026-08-21",
    phaseId: "p-phase0",
    systems: ["smartwatch-clank", "watch-clank", "semiconductor-intelligence"],
    event: "Law 5 specimen: smartwatch dual-lane — competing soak timer retired in the 2026-08-21 law/inventory record.",
    before: "A Clank-lane could have more than one enabled scheduling mechanism. Experimental soaks could reach production collectors.",
    change:
      "FLEET_LAWS.md Law 5 (d046d54) records dual scheduling as a named failure class and the smartwatch specimen: systemd soak timer retired 2026-08-21T21:06Z, cron kept. That timestamp is law/inventory text (also fleet.yaml soak row observed_at_utc 2026-08-21T21:06:00Z), not recovered journalctl. The 2026-08-22 inventory lists smartwatch-hetzner-soak-timer-retired as DISABLED (enabled: false; files retained unscheduled) beside a cron lane RUNNING staging at d987b66 — a dated snapshot of what Phase 2A recorded, not a current probe. Git-resident soak unit/crontab examples prove competing-scheduler machinery existed; templates do not prove enablement then or now. Sibling specimens (Watch fcb5e91 ghost cron; SemInt cron bypassing OperationalScheduler) name the class; the SemInt residual was still OPEN in that inventory. Later repo HEADs stay out of this row. Current enabled scheduler per lane remains UNKNOWN.",
    why: "Two clocks on one notebook double-notify, starve each other, or hide which path actually ran.",
    evidence: [
      {
        id: "ev-law5",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        sha: "d046d54428b1e9dfdb63b8336959df955dd6820a",
        note: "Law 5: smartwatch dual-lane (cron kept, systemd retired 2026-08-21T21:06Z). Timestamp is law/inventory text, not live journalctl.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "d046d54428b1e9dfdb63b8336959df955dd6820a", note: "Fleet Laws v1" }],
    conceptIds: ["scheduler", "cron", "systemd", "configuration-drift"],
    lawIds: ["law-5"],
    incidentIds: ["inc-dual-scheduler"],
    whatFailed: "Failing timer fired hourly with zero observability (Law 3 specimen). Experimental soak ran production Samsung collectors (e9a897c made scope explicit).",
    laterConsequence: "GIC-24 dual scheduler authority. Tablet later encoded as INTENTIONALLY_DORMANT so a stale unit file is not a second authority.",
    verification:
      "Failure class and dated recorded retirement (Law 5 @ d046d54; 2026-08-22 inventory soak row DISABLED at 21:06Z): VERIFIED. 21:06Z is law/inventory text, not recovered journalctl. Current enabled scheduler per lane: UNKNOWN.",
    residualRisk:
      "Do not teach 'cron is the sole scheduler now'. Git templates ≠ enabled. Watch fcb5e91 and SemInt residuals are the class, not this host action; SemInt was still OPEN in the 22 Aug inventory. Later HEADs (smartwatch a717977) stay out. Live scheduler authority remains UNKNOWN.",
    confidence: "verified",
  }),
  e("h-phase0-freeze", {
    date: "2026-08-21",
    period: "2026-08-21",
    phaseId: "p-phase0",
    systems: ["clank-architecture", "diagnostic-clank", "unified-clank-platform"],
    event: "Phase 0: promotion freeze. Governance vs control-plane authority split (ADR-0001).",
    before: "Repos could be treated as 'ready' because CI was green or a dashboard existed.",
    change:
      "NO_PROMOTION_POLICY.md; ADR-0001; Phase 0 remediation merge ac83a2e (Hetzner and NAS untouched). unified-clank-platform proposed for supersession.",
    why: "Deployment truth was UNKNOWN in the fleet ledger. Promoting on repository state would launder guesses into production.",
    evidence: [
      {
        id: "ev-adr1-full",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "adr/0001-authority-and-phase0-freeze.md",
        note: "clank-architecture = governance; diagnostic-clank = inventory/control plane.",
        status: "verified",
      },
      {
        id: "ev-p0-merge",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "ac83a2ea7ed01452eb9d7612aec143a6446f41af",
        note: "Phase 0 remediation merge 2026-08-21T08:56:35Z.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-architecture", sha: "ac83a2ea7ed01452eb9d7612aec143a6446f41af" },
      { repo: "anil-ganti-nbc/clank-architecture", sha: "9b1d2ffbcb826e70a713de2e8e12ba22599285db", note: "activate promotion freeze" },
    ],
    conceptIds: ["promotion-gate", "deployment", "contract", "operator-role"],
    lawIds: ["law-8"],
    incidentIds: ["inc-bankai"],
    laterConsequence: "As of 2026-08-27 the freeze is still the controlling production rule.",
    confidence: "verified",
  }),
  e("h-fleet-laws", {
    date: "2026-08-22",
    period: "2026-08-21 to 2026-08-22",
    phaseId: "p-phase0",
    systems: ["clank-architecture", "all Clanks"],
    event: "Fleet Laws v1 codified: eight binding invariants plus deferred Law 9.",
    before: "Failure stories lived in commit messages, handoffs, and DiagnosticBench YAML.",
    change:
      "FLEET_LAWS.md + conformance/test_fleet_laws.py (d046d54, 2026-08-21T21:27:48Z). Status ACTIVE as of Phase 2A 2026-08-22. Laws 1–8 name reference implementations, violators, exceptions, invariants, specimens.",
    why: "Without a named invariant, a fix is a one-off. Specimens must never re-occur.",
    evidence: [
      {
        id: "ev-laws-commit",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "d046d54428b1e9dfdb63b8336959df955dd6820a",
        path: "FLEET_LAWS.md",
        note: "Codify Fleet Laws v1 + hermetic conformance suite (Phase 2A).",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "d046d54428b1e9dfdb63b8336959df955dd6820a" }],
    conceptIds: ["fleet-law", "invariant", "regression-test", "allowlist"],
    lawIds: ["law-1", "law-2", "law-3", "law-4", "law-5", "law-6", "law-7", "law-8", "law-9"],
    incidentIds: [],
    laterConsequence: "Every later ADR and GIC is a specialization of these planes.",
    confidence: "verified",
  }),
  e("h-motherclank-born", {
    date: "2026-08-22",
    period: "2026-08-22",
    phaseId: "p-motherclank",
    systems: ["motherclank", "diagnostic-clank", "clank-architecture"],
    event: "ADR-0002 and the motherclank repository: a camera, not a janitor.",
    before: "Laws existed. Nobody harvested fleet evidence without taking locks or trusting dashboards.",
    change:
      "ADR-0002 (b341b0f, 2026-08-22T05:52:04Z) and creation of the motherclank repository shortly afterward established the design for a read-only supervisory layer over the Clank fleet. The ADR defines Motherclank as an observer/reasoner that may recommend but must not mutate production state; M5 mutation is explicitly deferred. The repository itself was initially described as M0, a read-only fleet harvester. That proves the supervisory architecture was created, not that live supervision was already active: Git-resident installer/unit templates do not prove timer enablement, successful harvests, host var/ snapshots, or a deployed SHA. Those runtime facts remain UNKNOWN.",
    why: "A supervisor that can write is a second Clank with blast radius over the whole fleet.",
    evidence: [
      {
        id: "ev-adr2-commit",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "b341b0f0805ff747c6ada55888ce21476fc05386",
        path: "adr/0002-motherclank-supervisory-architecture.md",
        note: "PROPOSED reviewed draft. UNKNOWN-propagation binding. Onboarding = Phase 2C adapter order.",
        status: "verified",
      },
      {
        id: "ev-mc-created",
        kind: "repo",
        repo: "anil-ganti-nbc/motherclank",
        note: "created_at 2026-08-22T06:02:49Z. Description: Motherclank M0 - read-only fleet harvester per ADR-0002.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "b341b0f0805ff747c6ada55888ce21476fc05386" }],
    conceptIds: ["motherclank", "diagnostic-clank", "observability", "derived-state"],
    lawIds: ["law-3", "law-6"],
    incidentIds: [],
    laterConsequence: "ADR-0003 (same day) authorises M3 recommendations into Diagnostic Clank Agent Inbox — still no execution.",
    verification:
      "Architectural birth (ADR-0002, repo created_at, read-only intent, M5 deferred): VERIFIED. Do not present M1–M4 as proven live stages on 22 Aug. Live Motherclank SHA, process, timer enablement, harvests, and host var/: UNKNOWN.",
    residualRisk:
      "Live Motherclank SHA, process, timer, and host var/ remain UNKNOWN. Git-resident installer/unit templates do not prove enablement. Later repo HEAD (7cee2f8) is not a deployed SHA.",
    confidence: "verified",
  }),
  e("h-def-m15", {
    date: "2026-08-22",
    period: "2026-08-22",
    phaseId: "p-motherclank",
    systems: ["smartphone-clank", "diagnostic-clank", "motherclank"],
    event: "DEF-M1.5: smartphone adapter ordered runs by UUID-string id, producing false-STALE (and inverse false-HEALTHY risk).",
    before: "Motherclank M1 first synthesis trusted adapter-mapped run order and a shared status mapper.",
    change:
      "Fixed in diagnostic-clank 97b07ae with UUID-trap + never-upgrade regressions. Ledger row CLOSED the same day (b300b36).",
    why: "Lexical UUID order is not time. A mapper that upgrades UNKNOWN/PARTIAL into HEALTHY launders a lie.",
    evidence: [
      {
        id: "ev-def-m15",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "DECISION_LEDGER.md",
        note: "DEF-M1.5 CLOSED: UUID-string id ordering; shared mapper lacked fleet vocabularies SUCCESS/PARTIAL/ZERO_ITEMS/BLOCKED.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "b300b36e1f9c257b0c90331f5977ceea58103dfc", note: "ledger DEF-M1.5 CLOSED" }],
    conceptIds: ["health-check", "false-positive", "runtime-provenance", "implementation-agent"],
    lawIds: ["law-3"],
    incidentIds: ["inc-health-honesty"],
    diagnosis: "Motherclank's first synthesis found adapter-truth defects. The supervisor dogfooded itself.",
    laterConsequence: "Never-upgrade property tests become a Motherclank invariant.",
    confidence: "verified",
  }),
  e("h-materialization", {
    date: "2026-08-22",
    period: "2026-08-22 to 2026-08-24",
    phaseId: "p-scars",
    systems: ["oem-radar", "smartwatch-clank", "feature-phone-clank", "cron"],
    event:
      "A scheduled Clank outage exposed a materialization gap: scheduler activity was visible, but the collector never successfully became a running process.",
    before: "Health checks that watched the calendar treated elapsed timers as successful work.",
    change:
      "Preserved decision/architecture records (DECISION_LEDGER INC-20260822-A, ADR-0008) attribute this to a pre-exec logging/permission failure: stash -u recreated untracked logs/ as root:root, so cron redirects failed before the collector started. Codified as MATERIALIZATION_GAP. OEM Radar lost no DB data. The impact map records a ~09:59–10:06Z window and ~36h silence — those host-level timestamps are operator-addendum in that document, not recovered syslog.",
    why: "Untracked runtime directories lived inside source checkouts, so a Git hygiene command became a production outage.",
    evidence: [
      {
        id: "ev-inc-a",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "DECISION_LEDGER.md",
        note: "INC-20260822-A recorded 2026-08-24. Mechanism: stash -u, logs/ root:root, pre-exec failure. Named MATERIALIZATION_GAP.",
        status: "verified",
      },
      {
        id: "ev-impact-a",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/INCIDENT_IMPACT_MAP_2026-08-23.md",
        note: "Family A as recorded in the impact map. Host timestamps (~09:59–10:06Z, ~36h) are not independently recovered syslog.",
        status: "incomplete",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "cd276689a4055436cd974beb1d3272465e3b4145", note: "ADR-0008 + ADR-0009" }],
    conceptIds: ["materialization-gap", "execution-liveness", "scheduler", "cron", "untracked"],
    lawIds: ["law-3"],
    incidentIds: ["inc-materialization"],
    whatFailed: "Collectors never became processes. Dashboards that watched invocation stayed calm.",
    diagnosis: "Pre-exec redirect failure, not a collector regression, not a legitimate zero.",
    fix: "Directory ownership; six-stage liveness model; GIC-04; ADR-0009 runtime-state/source-tree separation.",
    verification:
      "Incident class and mechanism: VERIFIED from DECISION_LEDGER.md, ADR-0008, G1–G8 fixtures (motherclank @3558fab). Exact host chronology and raw syslog: INCOMPLETE — not recovered this campaign, not in the Handbook checkout.",
    residualRisk:
      "Any future redirect, permission, or missing binary reproduces MATERIALIZATION_GAP. Do not re-promote impact-map timestamps as independently re-read journalctl.",
    laterConsequence: "Law 3's invocation≠commit becomes a first-class detection, not a slogan.",
    confidence: "verified",
  }),
  e("h-volume-loss", {
    date: "2026-08-23",
    period: "2026-08-23",
    phaseId: "p-scars",
    systems: ["smartwatch-clank", "feature-phone-clank", "Docker volumes"],
    event: "INC-20260823: two live volumes deleted — Smartwatch restored with a known gap; Feature Phone began a new epoch.",
    before: "Volumes were treated as ordinary containers of files. Feature-phone had no backup. Smartwatch had a 18 Aug backup.",
    change:
      "Impact map Family B and continuity seeds record smartwatch_clank_staging_data destroyed 2026-08-23T21:22:08Z and feature_phone_clank_staging_data 21:22:11Z. Those instants are operator-provided evidence, not live logs. Smartwatch was restored 22:09Z from the 2026-08-18T20:50:37Z backup — RESTORED_HISTORY, not a new epoch; observations ≈2026-08-18T20:13Z–2026-08-22T10:00Z (~3d13h) never made it into that backup and are gone. Feature Phone had no backup: fresh DB at 21:36:11Z → NEW_EPOCH fpc-epoch-2; pre-incident history is irrecoverable even on the host. ACT-011 (24 Aug, separate row) proved a disposable-volume restore of the remaining recovery points on temporary_scratch. That is not rewind, not durable off-host backup, and not proof the volumes are still attached. Motherclank var/ for states A–E remains BLOCKED. Live path, epoch, and backup state remain UNKNOWN.",
    why: "Human and agent destructive error is an expected failure mode (DATA_SURVIVABILITY R2).",
    evidence: [
      {
        id: "ev-inc-23",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "DECISION_LEDGER.md",
        note: "INC-20260823. Seed: motherclank continuity/seeds/INC-20260823-volume-loss.jsonl.",
        status: "verified",
      },
      {
        id: "ev-impact-b",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/INCIDENT_IMPACT_MAP_2026-08-23.md",
        note: "Family B states A–E. Instants are operator-provided evidence, not live logs. Artifact-level Motherclank var/ confirmation BLOCKED.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "7337efc8718552e33452c7e55aca33ed1cc43ae0", note: "ADR-0006/0007 + impact map" }],
    conceptIds: ["epoch", "volume", "rollback", "blast-radius", "authoritative-state"],
    lawIds: ["law-1"],
    incidentIds: ["inc-volume-loss"],
    whatFailed: "Irreplaceable observational memory. FPC pre-incident history entirely irrecoverable. SW ~3d13h never in the 18 Aug backup.",
    diagnosis: "Two families sharing a window must not be conflated. Restore ≠ rewind. HMD ReadTimeout after FPC repair is an ordinary source failure.",
    fix: "ContinuityEvent registry; DB-LOSS-RESTORE vs DB-LOSS-NEW-EPOCH golden incidents. ACT-011 (24 Aug) is a later scratch drill, not this incident's closing.",
    verification:
      "Named volume loss, SW RESTORED_HISTORY vs FPC NEW_EPOCH, and the irrecoverable windows: VERIFIED from impact map Family B and continuity seeds. Instants are operator-provided, not live logs. ACT-011 is a later scratch restore of remaining RPs (h-act011), not rewind. Motherclank var/ A–E: BLOCKED. Live path/epoch/backup: UNKNOWN.",
    residualRisk:
      "Restore ≠ rewind. Do not teach ACT-011 as closing the gap. Durable off-host is NO (temporary_scratch). Live volume attachment UNKNOWN. Do not re-round 3d13h to 4 days. Seeds ≠ missing var/ batches.",
    laterConsequence: "ADR-0007 destructive-operation safety: pattern-derived names never authorize deletion.",
    confidence: "verified",
  }),
  e("h-dau-worlds", {
    date: "2026-08-23",
    period: "2026-08-23",
    phaseId: "p-continuity",
    systems: ["dau-world-generator", "idle-time-learning-doodad"],
    event: "DAU World Generator vertical slice: causal seeded diagnostic worlds.",
    before: "Incident teaching required live fleet evidence or hand-written stories.",
    change:
      "dau-world-generator created 2026-08-23T19:57:17Z. Later absorbed natively into Dead Air University (commit 5595073 cited in existing Handbook) without deleting the provenance repo.",
    why: "Replayable worlds teach diagnosis without mutating production Clanks.",
    evidence: [
      {
        id: "ev-dwg-created",
        kind: "repo",
        repo: "anil-ganti-nbc/dau-world-generator",
        note: "created_at 2026-08-23T19:57:17Z.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["deterministic", "fixtures", "e2e"],
    lawIds: [],
    incidentIds: [],
    laterConsequence: "Handbook investigation labs reuse freeze→reveal, but their physics is history, not a simulator.",
    confidence: "verified",
  }),
  e("h-archaeology", {
    date: "2026-08-24",
    period: "2026-08-24",
    phaseId: "p-continuity",
    systems: ["clank-architecture", "ten Clanks in scope"],
    event: "Fleet Archaeology Report: adapter-first preservation, not collector rewrite.",
    before: "Oral history and scattered handoffs. Risk of inventing a platform that never existed.",
    change:
      "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md. Four independent audits ratify it (ADR-0005 ACCEPTED). Canonical v0.2 adds observer-only Phase 1, instance/lane identity, evidence-bearing capability states, golden incidents.",
    why: "The fleet was not built from one platform. Pretending otherwise would destroy local semantics.",
    evidence: [
      {
        id: "ev-arch-report",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        sha: "431ba01efc156729574ffd9a470fb41f0a8aaa62",
        note: "Evidence-led, not a promotion decision. Inventory current through 2026-08-22.",
        status: "verified",
      },
      {
        id: "ev-adr5",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "DECISION_LEDGER.md",
        note: "ADR-0005 ACCEPTED 2026-08-24.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-architecture", sha: "e16d48bfa32ea4693405931961e38b67273ceccc", note: "Ratify archaeology-derived integration gates" },
      { repo: "anil-ganti-nbc/clank-architecture", sha: "2b872ad56762bbe024f2fe65cb70b2f3c43c2b3c", note: "Adopt canonical v0.1" },
    ],
    conceptIds: ["dogfooding", "contract", "source-adapter", "implementation-agent", "operator-role"],
    lawIds: [],
    incidentIds: ["inc-directory-sweep"],
    laterConsequence: "AGENT_RULES.md binds future agents: preserve historical material; UNKNOWN is not healthy; no auto-promote.",
    confidence: "verified",
  }),
  e("h-act011", {
    date: "2026-08-24",
    period: "2026-08-24",
    phaseId: "p-continuity",
    systems: ["smartwatch-clank", "feature-phone-clank", "motherclank"],
    event: "ACT-011: operator-executed live recovery-point verification.",
    before: "Restored/new-epoch DBs existed; restorability was a story.",
    change:
      "Smartwatch RP1: 516 runs, 52,126 observations, integrity_check=ok, disposable-volume restore passed. Feature-phone epoch-2 first RP: integrity ok, restore passed. Off-host copies exist only as temporary_scratch. Durable gate OPEN.",
    why: "A backup that has never been restored is a rumour (GIC-16/17).",
    evidence: [
      {
        id: "ev-act011",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "DATA_SURVIVABILITY.md",
        note: "§17.1 ACT-011 LIVE/VERIFIED. Evidence seed survivability-ACT011-verified-live.jsonl.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "cd276689a4055436cd974beb1d3272465e3b4145" }],
    conceptIds: ["rollback", "epoch", "volume", "verification"],
    lawIds: [],
    incidentIds: ["inc-volume-loss"],
    residualRisk: "Durable off-host redundancy DESIGNED ONLY. Least-privilege destructive-capability audit NOT STARTED (ACT-012).",
    laterConsequence: "Acceptance test 'Claude deletes the volume again' is still DESIGNED for most lanes.",
    confidence: "verified",
  }),
  e("h-ctw-dogfood", {
    date: "2026-08-24",
    period: "2026-08-24 to 2026-08-25",
    phaseId: "p-qc-onboard",
    systems: ["chinese-tech-wire", "motherclank", "diagnostic-clank"],
    event: "CTW dogfood (24–25 Aug): the observer playbook passed its own register step on a guessed path.",
    before: "Onboarding.md was a document. No field scorecard.",
    change:
      "CTW_ONBOARDING_DOGFOOD.md (66cef4c / blob 64f92aa) is a 14-step field scorecard against ONBOARDING.md, not a current host map. It tested whether CTW could join as an observer with zero Motherclank-core participant-specific edits: 0 such lines; adapter ~230 LOC; 38 GICs green. Step 8 was scored PASS on a registry row + guarded refresh line. Scorecard friction is FGT registry filename vs live-verified inner name newsroom.db. The guessed CTW path is not on that card. Anil 7f977d6 (2026-08-25T00:20Z) records the finding: checkout-relative data/ never existed, the live store was a differently-named Docker volume, and refresh silently SKIPs a missing source — caught only by live discovery, not review. That commit is the operator write-up and the playbook patch (ONBOARDING.md step 8 three-way cross-check), not a later code state. The path it happened to find that day is dated evidence, not the thing to memorise. Scorecard steps 2 and 11 stayed LIVE_EVIDENCE_REQUIRED. 2026-08-22 inventory still listed data/ctw.db under checkout. Later repo HEAD 1a47220 stays out. Live CTW volume, deployed SHA, and scheduler remain UNKNOWN.",
    why: "Dogfooding exposed that the playbook was guessing where the system lived instead of proving it.",
    evidence: [
      {
        id: "ev-ctw-dog",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "CTW_ONBOARDING_DOGFOOD.md",
        sha: "64f92aa42f233ed189c8c6cb10f550b8dfd77b11",
        note: "14-step scorecard 2026-08-24. Step 8 PASS. Steps 2 and 11 LIVE_EVIDENCE_REQUIRED. Guessed path is not on this card.",
        status: "verified",
      },
      {
        id: "ev-onboard-crosscheck",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "7f977d6bc5d4839a6f89c7dc7b87cf5fdefa89a5",
        note: "Anil: operator write-up of guessed path + ONBOARDING.md step 8 three-way cross-check.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-architecture", sha: "66cef4c89a0f7cd4ddbea10a14149a63835ec4f5", note: "CTW dogfood scorecard" },
      { repo: "anil-ganti-nbc/clank-architecture", sha: "7f977d6bc5d4839a6f89c7dc7b87cf5fdefa89a5", note: "operator finding + playbook patch" },
    ],
    conceptIds: ["dogfooding", "operator-role", "implementation-agent", "source-adapter"],
    lawIds: ["law-6"],
    incidentIds: ["inc-deployed-sha"],
    diagnosis: "A git-visible registry row and refresh line can PASS while the path is a guess. Silent SKIP hides drift from review.",
    laterConsequence: "ONBOARDING.md step 8 requires cross-checking registry filename, refresh-script source path, and actual deployed datastore. Do not memorise the volume from that day.",
    verification:
      "Dogfood run and adapter-thinness: VERIFIED from 66cef4c/64f92aa. Guessed-path finding and playbook patch: VERIFIED from 7f977d6. Dated host topology from that exercise: INCOMPLETE. Live CTW volume/SHA/scheduler: UNKNOWN.",
    residualRisk:
      "Do not fossilise the 24–25 Aug path or volume as current production. Inventory data/ctw.db under checkout is the class of claim the trial contradicted. Later repo HEAD 1a47220 is not a deployed SHA.",
    confidence: "verified",
  }),
  e("h-gitignore-runtime", {
    date: "2026-08-24",
    period: "2026-08-24",
    phaseId: "p-continuity",
    systems: ["oem-radar"],
    event: "oem-radar excludes runtime logs/backups from git so stash -u cannot recreate them with the wrong owner.",
    before: "Untracked runtime directories lived inside source checkouts (ADR-0009 scar).",
    change:
      "Commit 44ce1ac 2026-08-24T00:12:39Z: 'Prevents a repeat of the 2026-08-22/23 incident pattern where root git stash -u / stash pop against these checkouts recreated untracked runtime directories with wrong ownership and broke cron redirects before collector start.'",
    why: "A Git hygiene command must not be a production outage. Runtime state does not belong in the source tree.",
    evidence: [
      {
        id: "ev-oem-gi",
        kind: "commit",
        repo: "anil-ganti-nbc/oem-radar",
        sha: "44ce1ac5538ed9f2ddf9b204d9241eaaa571ee18",
        note: "chore: exclude runtime logs/backups from git. Direct citation of INC-20260822-A pattern.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/oem-radar", sha: "44ce1ac5538ed9f2ddf9b204d9241eaaa571ee18" }],
    conceptIds: ["untracked", "materialization-gap", "working-tree"],
    lawIds: ["law-3"],
    incidentIds: ["inc-materialization"],
    laterConsequence: "ADR-0009 runtime-state/source-tree separation has a per-repo mechanical counterpart.",
    confidence: "verified",
  }),
  e("h-watch-qc", {
    date: "2026-08-25",
    period: "2026-08-25 to 2026-08-26",
    phaseId: "p-qc-onboard",
    systems: ["watch-clank", "human QC queue"],
    event:
      "Watch QC filled with low-value first-sightings because qualification treated smoke/validation runs as real catalogue passes.",
    before: "Qualification inferred 'real pass' from successful-run count, then from discovered_count > 1.",
    change:
      "watch-clank 5de5329 (2026-08-26T02:01:27Z) and ARCHITECTURE_NOTES_QC_VOLUME.md: catalogue-pass is an invocation fact (persisted max_items), never inferred from output size. Weak FIRST_SEEN (score ≤ 15) auto-deprioritized; useful FS in history scored ≥ 25. Queue accounting in that 2026-08-26 snapshot was 639 raw unreviewed / 580 default FIFO before repair replay / 41 after. Those counts are the incident values in the notes, not a live queue.",
    why: "Human attention is the scarce resource. A filter that treats smoke as harvest hides launches.",
    evidence: [
      {
        id: "ev-qc-vol-h",
        kind: "commit",
        repo: "anil-ganti-nbc/watch-clank",
        path: "ARCHITECTURE_NOTES_QC_VOLUME.md",
        sha: "5de5329f43adc3fdad0ee797f0e691427f802641",
        note: "2026-08-26 notes + repair: invocation provenance, weak-FS deprioritization, three-tier queue accounting. Snapshot 639/580/41 is in this commit, not a live dashboard.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/watch-clank", sha: "5de5329f43adc3fdad0ee797f0e691427f802641", note: "QC-volume notes and repair, 2026-08-26T02:01:27Z" }],
    conceptIds: ["qc-flood", "runtime-provenance", "first-seen", "initial-fill", "editorial-eligibility"],
    lawIds: ["law-2"],
    incidentIds: ["inc-qc"],
    laterConsequence: "L-WATCH-009: execution provenance is part of data provenance. Later Watch HEADs are a different story and not this incident.",
    residualRisk: "Live Watch QC queue size remains UNKNOWN. Do not teach 639/580/41 as current.",
    confidence: "verified",
  }),
  e("h-watch-unwired", {
    date: "2026-08-25",
    period: "2026-08-25",
    phaseId: "p-qc-onboard",
    systems: ["watch-clank"],
    event: "Tissot and Timex UK collectors existed in code and in the pipeline registry, but were absent from the production invocation chain — so systemd units could not be rendered.",
    before: "Implementation plus a registry row were treated as 'the collector is in production.'",
    change:
      "e7eeb3f (2026-08-25T00:18:48Z): KNOWN_COLLECTORS, collector_registry, run_pipeline argparse, and render_units.py wired tissot_sitemap and timex_uk_products. test_production_wiring.py: every EXPERIMENTAL_READY_FOR_HETZNER collector must be mechanically invokable. Delivery-silence canonized as a promotion privilege.",
    why: "A host deployment found the gap. Code on GitHub is not the same as a unit file the timer can start.",
    evidence: [
      {
        id: "ev-watch-unwired",
        kind: "commit",
        repo: "anil-ganti-nbc/watch-clank",
        sha: "e7eeb3fa1f9b19315b985d1ea6c015f8e6df63a8",
        note: "Repair: wire tissot + timex_uk into production invocation path; canonize delivery gate. Deployment finding (Claude, Hetzner 2026-08-25).",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/watch-clank", sha: "e7eeb3fa1f9b19315b985d1ea6c015f8e6df63a8" }],
    conceptIds: ["deployment", "configuration-drift", "head-vs-deployed", "promotion-gate"],
    lawIds: ["law-6", "law-8"],
    incidentIds: ["inc-deployed-sha"],
    whatFailed: "Collectors that 'existed' could not be scheduled. Registry membership was not invocation membership.",
    diagnosis: "Three tables had to agree: health.KNOWN_COLLECTORS, collector_registry._CONTROLS, render_units.py/run_pipeline.py. Two of three was not enough.",
    laterConsequence: "A production-wiring invariant test, not a README checkbox.",
    confidence: "verified",
  }),
  e("h-v03-freeze", {
    date: "2026-08-25",
    period: "2026-08-25",
    phaseId: "p-qc-onboard",
    systems: ["clank-architecture", "motherclank"],
    event: "Architecture v0.3 frozen. No speculative core redesign until a real participant or incident proves the contract insufficient.",
    before: "Rapid ADR sequence 0006–0014 in 48 hours.",
    change:
      "FLEET_CAPABILITY_MATRIX.md freeze marker. Bug fixes, new adapters, new GICs, operational improvements permitted. SI onboarding dogfood the same window (4fb9c44).",
    why: "A contract that changes every afternoon cannot be dogfooded. Freeze is how you find out whether it works.",
    evidence: [
      {
        id: "ev-freeze",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_CAPABILITY_MATRIX.md",
        note: "v0.3 FROZEN (2026-08-25).",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/clank-architecture", sha: "e9c4a2b77f0a484171b01980469eee34971f8ee5", note: "closure hygiene freeze marker 2026-08-26" }],
    conceptIds: ["contract", "fleet-law", "operator-role"],
    lawIds: [],
    incidentIds: [],
    residualRisk: "Scheduler-trace still supported_unconfigured on all lanes. Survivability unproven except two recovery points on scratch.",
    confidence: "verified",
  }),
  e("h-ai-workflow", {
    date: "2026-08-26",
    period: "2026-08-04 to 2026-08-26",
    phaseId: "p-qc-onboard",
    systems: ["all Clanks", "clank-architecture", "motherclank"],
    event: "Staged AI-assisted engineering is the actual development process: implementation agents draft, reviewer/auditor agents check, the human operator decides.",
    before: "A tempting story: 'I pasted one AI output into another.'",
    change:
      "Commit metadata on clank-architecture shows two durable roles: ox-alpha@agents.local (ADRs 0006–0014, golden incidents, dogfood scorecards) and Anil / anil-ganti-nbc (account creation, Phase 0 merge, ADR-0002, ONBOARDING.md cross-check 7f977d6, ACT-011). oem-radar commits 1c55834 / 31fc46b / 3a4d0a1 name Co-Authored-By: Claude Sonnet 5. AGENT_RULES.md binds agents: preserve history, UNKNOWN is not healthy, no auto-promote, no silent conflict resolution.",
    why: "The fleet is too heterogeneous for one-shot generation. Requirements had to be carried between sessions, evidence demanded, and mission criteria chosen by a human who is not trying to become a programmer.",
    evidence: [
      {
        id: "ev-agent-rules",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "AGENT_RULES.md",
        sha: "0a80fe6513dbef115044f02ab1dfffe13502f044",
        note: "Fifteen binding rules for agents on Clanks, Motherclank, adapters, conformance.",
        status: "verified",
      },
      {
        id: "ev-anil-onboard",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "7f977d6bc5d4839a6f89c7dc7b87cf5fdefa89a5",
        note: "Human operator follow-up after CTW guessed refresh path. Author: Anil, 2026-08-25T00:20:58Z.",
        status: "verified",
      },
      {
        id: "ev-ox-adr8",
        kind: "commit",
        repo: "anil-ganti-nbc/clank-architecture",
        sha: "cd276689a4055436cd974beb1d3272465e3b4145",
        note: "ox-alpha authored ADR-0008/0009. Implementation agent, not the operator.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-architecture", sha: "7f977d6bc5d4839a6f89c7dc7b87cf5fdefa89a5", note: "human operator" },
      { repo: "anil-ganti-nbc/clank-architecture", sha: "cd276689a4055436cd974beb1d3272465e3b4145", note: "implementation agent" },
    ],
    conceptIds: ["implementation-agent", "reviewer-agent", "operator-role", "lifecycle", "dogfooding"],
    lawIds: [],
    incidentIds: ["inc-deployed-sha"],
    laterConsequence: "The Handbook exists so this process can be explained without collapsing it into paste.",
    confidence: "verified",
  }),
  e("h-handbook", {
    date: "2026-08-27",
    period: "2026-08-27",
    phaseId: "p-current",
    systems: ["clank-systems-handbook"],
    event: "Clank Systems Handbook repository created: evidence-backed literacy, not a programming course.",
    before: "The operator could point at ADRs and incident files but did not have a course that taught the process in human language.",
    change:
      "Repo created 2026-08-27T02:02:54Z. Initial content 3374e81; GUI 49ebe3e; standalone build c8198d9. This curriculum expansion is the content phase.",
    why: "The unacceptable explanation of the fleet is 'I pasted one AI output into another.'",
    evidence: [
      {
        id: "ev-hb-created",
        kind: "repo",
        repo: "anil-ganti-nbc/clank-systems-handbook",
        note: "created_at 2026-08-27T02:02:54Z. Initial SHA 3374e81382163878bf19394236f74649aa366052.",
        status: "verified",
      },
    ],
    commits: [
      { repo: "anil-ganti-nbc/clank-systems-handbook", sha: "3374e81382163878bf19394236f74649aa366052", note: "initial content" },
      { repo: "anil-ganti-nbc/clank-systems-handbook", sha: "8c267dea6617eb63adef6aa1bcdb841e48ae94fb", note: "standalone + CI dispatch (branch point for this work)" },
    ],
    conceptIds: ["operator-role", "implementation-agent", "dogfooding"],
    lawIds: [],
    incidentIds: [],
    laterConsequence: "Handbook owns historical evidence. DAU owns mastery. Worlds own simulators.",
    confidence: "verified",
  }),
  e("h-watch-qc-race", {
    date: "2026-08-27",
    period: "2026-08-27",
    phaseId: "p-current",
    systems: ["watch-clank", "human QC queue"],
    event: "Watch QC recovers from a concurrent double-submit: UNIQUE is not an operator-facing contract.",
    before: "UNIQUE(event_id) already made a duplicate archive row impossible, but two near-simultaneous POSTs could both read 'no existing review' before either committed.",
    change:
      "watch-clank ee3f34d (2026-08-27T03:16:34Z): UNIQUE(event_id) is the database guarantee. Two near-simultaneous POSTs could both read 'no existing review' before either committed; the losing insert would raise IntegrityError. The commit catches that violation, rolls back the losing insert, and replays the same verdict as a correction against whichever row won — that is the UI/operator contract. The suite can reproduce the race; '468 passed, 2 skipped/live' is that commit's test run, not a host probe. Those are separate facts from a lived host 500, which is not recorded. Later Watch HEADs (d4fda37, 9d812ed) stay out of this incident. Live deployed SHA remains UNKNOWN.",
    why: "A database uniqueness constraint is not an operator-facing contract. The QC button is a writer (Law 7); races must fail closed into the promised behaviour, not a 500.",
    evidence: [
      {
        id: "ev-watch-qc-race",
        kind: "commit",
        repo: "anil-ganti-nbc/watch-clank",
        sha: "ee3f34d7eba8715838196d59fbf562818349009b",
        note: "fix(qc): recover gracefully from a concurrent double-QC submission. Idempotent-by-correction. Git-resident application contract, not a recorded lived host 500.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/watch-clank", sha: "ee3f34d7eba8715838196d59fbf562818349009b", note: "QC race recovery, 2026-08-27T03:16:34Z" }],
    conceptIds: ["race-condition", "lock", "operator-role", "implementation-agent"],
    lawIds: ["law-7"],
    incidentIds: ["inc-writer-lock", "inc-qc"],
    laterConsequence: "The uniqueness constraint remains the last line; the application now speaks the same language as the constraint.",
    verification:
      "Mechanism (UNIQUE ≠ operator contract under concurrent POSTs; catch/rollback/replay in ee3f34d): VERIFIED from the commit. A lived host 500: not evidenced. Live Watch SHA: UNKNOWN.",
    residualRisk:
      "Live Watch deployed SHA remains UNKNOWN. Do not teach ee3f34d, d4fda37, or 9d812ed as production. Green tests on the commit are not a host SHA.",
    confidence: "verified",
  }),
  e("h-tablet-local", {
    date: "2026-08-27",
    period: "2026-08-27",
    phaseId: "p-current",
    systems: ["tablet-clank"],
    event: "Tablet Clank repo gains a genuine manual-only QC layer and a Windows local launcher. This is a repository change, not a proven Hetzner membership change.",
    before: "2026-08-22 inventory: disabled experimental checkout, INTENTIONALLY_DORMANT, no production members.",
    change:
      "a41d1e7 2026-08-27T04:35:52Z (author Anil, Co-Authored-By: Claude Sonnet 5): separate on-disk QCArchive, Run All limited to the production allowlist, Windows launcher that starts HTTP only — no Task Scheduler entry. Wave 2 honor_uk_tablets experimental (b176523, 2026-08-26) remains excluded from PRODUCTION_ALLOWLIST.",
    why: "Local field-test parity with other refreshed Clanks. A first-local baseline stayed silent (no false-novelty flood).",
    evidence: [
      {
        id: "ev-tablet-qc",
        kind: "commit",
        repo: "anil-ganti-nbc/tablet-clank",
        sha: "a41d1e7fa58f81cb9f8662d0357e8746f4b192dc",
        note: "Add QC contract, active queue, Run All, and Windows local launcher. Verified against a genuine first local baseline.",
        status: "verified",
      },
    ],
    commits: [{ repo: "anil-ganti-nbc/tablet-clank", sha: "a41d1e7fa58f81cb9f8662d0357e8746f4b192dc" }],
    conceptIds: ["diagnostic-clank", "head-vs-deployed", "qc-flood", "baseline"],
    lawIds: ["law-5", "law-1"],
    incidentIds: ["inc-directory-sweep"],
    residualRisk: "Live host membership remains UNKNOWN. Repo HEAD is not a fleet.yaml row. Do not treat this commit as 'Tablet is now production'.",
    laterConsequence: "Directory sweep is even more dangerous: a richer checkout can look 'alive' while remaining INTENTIONALLY_DORMANT on the host.",
    confidence: "verified",
  }),
  e("h-current-gaps", {
    date: "2026-08-27",
    period: "as of 2026-08-27",
    phaseId: "p-current",
    systems: ["fleet"],
    event: "Current-state snapshot: observer-supervised, promotion-frozen, survivability incomplete.",
    before: "See p-current phase.",
    change:
      "Capability matrix (motherclank@local / diagnostic-clank@p41-capability-contract) is evidence, not a score. Archaeology inventory was current through 2026-08-22; live host SHA/backup facts remain UNKNOWN where not re-probed. This Handbook must not invent a healthier present than the artefacts support.",
    why: "A current-state map that upgrades UNKNOWN to healthy would repeat Law 3 inside the course itself.",
    evidence: [
      {
        id: "ev-matrix",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_CAPABILITY_MATRIX.md",
        note: "Evidence snapshot. UNKNOWN stays visible. FGT REAL_STATE_VALIDATION BLOCKED until live copy.",
        status: "verified",
      },
      {
        id: "ev-arch-limit",
        kind: "report",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md",
        note: "Did not operate collectors or inspect production DBs. Host statements only from fleet inventory.",
        status: "verified",
      },
    ],
    commits: [],
    conceptIds: ["health-check", "deployment-drift", "authoritative-state"],
    lawIds: ["law-3", "law-6", "law-9"],
    incidentIds: [],
    residualRisk: "Durable off-host backups; Windows UNKNOWN; smartphone Law 2 novelty debt; FGT webhook rotation blocked-on-operator; cross-Clank identity ADR still blocking participant profile.",
    confidence: "verified",
  }),
  e("h-evidence-preservation", {
    date: "2026-08-27",
    period: "2026-08-27",
    phaseId: "p-current",
    systems: ["clank-systems-handbook", "fleet"],
    event: "Evidence-preservation campaign: git-resident deployment artefacts hashed into the Handbook; live host re-probe recorded INCOMPLETE.",
    before: "Content-phase ledger (27 rows) cited archaeology and ADRs. Unit files, backup scripts, continuity seeds, and fleet.yaml lived only in collector repos. Live SHA/scheduler/backup cells were already labelled UNKNOWN.",
    change:
      "docs/preserved/ copies of fleet.yaml, unit/timer/cron templates, compose files, backup/restore scripts, Motherclank continuity seeds, DATA_SURVIVABILITY.md, and the Aug 22–23 impact map, each with SHA-256. Operator re-probe script authored, not executed (no SSH). Google Drive empty of Clank dumps. Durable off-host backup remains DESIGNED. The original 27 ledger rows were queued for human review, not silently rewritten.",
    why: "Templates and seeds can rotate. Syslog and Motherclank var/ already might have. A prettier present must not be invented from GitHub HEAD.",
    evidence: [
      {
        id: "ev-preserved-fleet-yaml",
        kind: "file",
        repo: "anil-ganti-nbc/diagnostic-clank",
        path: "clank-fleet/inventories/fleet.yaml",
        sha: "3667af02c8dd33503ce75461ec2974d42f2f1d4c",
        note: "Preserved copy sha256:9d8d950b53cdc72ed61cdd477690d938b939a3787b8aeea0023ed53240d71ca5. Inventory as_of 2026-08-22T22:30:00Z, status INVENTORY_INCOMPLETE.",
        status: "verified",
      },
      {
        id: "ev-live-probe-incomplete",
        kind: "deployment",
        repo: "anil-ganti-nbc/clank-systems-handbook",
        path: "docs/LIVE_PROVENANCE_REPORT.md",
        note: "This campaign could not SSH to Hetzner. Law 6 cells stay UNKNOWN.",
        status: "incomplete",
      },
    ],
    commits: [],
    conceptIds: ["provenance", "runtime-provenance", "head-vs-deployed", "untracked"],
    lawIds: ["law-6", "law-3", "law-5"],
    incidentIds: ["inc-deployed-sha", "inc-materialization", "inc-volume-loss"],
    residualRisk: "Syslog and Motherclank var/ still unpreserved. ACT-011 scratch is not Layer C. Repo HEADs from 2026-08-27 must not be taught as production.",
    laterConsequence: "Confidence-audit view and human review queue exist so UNKNOWN cannot be painted over.",
    confidence: "verified",
  }),
];
