import type { FleetLaw } from "../lib/handbook/schema.ts";

export const LAWS: FleetLaw[] = [
  {
    id: "law-1",
    number: 1,
    title: "Initialization / no-flood",
    rule: "A collector's first run against an existing database MUST NOT emit notifications for pre-existing entities; genuine freshness must survive initialization via evidence-dated rescue.",
    plainEnglish:
      "The first time the notebook opens on a kitchen that already has food in it, you do not announce every tin as a launch. You mark the shelf as 'already there', and you still catch the one new tin that arrived with a date.",
    triggeringIncidentIds: ["inc-bankai", "inc-qc", "inc-volume-loss"],
    historyIds: ["h-expansion-scars", "h-fleet-laws", "h-volume-loss", "h-tablet-local"],
    evidence: [
      {
        id: "ev-l1",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        sha: "d046d54428b1e9dfdb63b8336959df955dd6820a",
        note: "Law 1. Specimens: FGT fresh-DB burst; Timex Weekender cluster; Samsung legacy rows; OEM bankai Lenovo 6349→0.",
        status: "verified",
      },
    ],
    prevents: "Notification floods on first run; treating a restored or new-epoch database as a market explosion.",
    cannotPrevent: "A soak whose success criterion is not recall (BANKAI). A human deleting the volume (Law 1 does not backup data).",
    specimens: [
      "FGT fresh-DB burst",
      "watch Timex Weekender cluster",
      "smartphone Samsung legacy rows",
      "OEM bankai Lenovo 6349→0 blind soak",
    ],
    conceptIds: ["baseline", "first-seen", "initial-fill", "epoch"],
  },
  {
    id: "law-2",
    number: 2,
    title: "Observation ≠ novelty",
    rule: "First local sighting is UNCONFIRMED novelty unless source-published evidence proves recency within policy window. Ambiguity surfaces; it is never suppressed.",
    plainEnglish:
      "Noticing a watch on a shelf for the first time is not the same as it launching today. FIRST_SEEN_BY_CLANK is a fact about the collector, not about the market.",
    triggeringIncidentIds: ["inc-qc"],
    historyIds: ["h-expansion-scars", "h-watch-qc", "h-fleet-laws", "h-watch-qc-race"],
    evidence: [
      {
        id: "ev-l2",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 2. Specimens: Timex 22-second launch cluster; Apple IN 48 false positives; FGT expiring-and-returning giveaway.",
        status: "verified",
      },
      {
        id: "ev-l2-watch",
        kind: "doc",
        repo: "anil-ganti-nbc/watch-clank",
        path: "WATCH_EXPANSION_FAILURE_CORPUS.md",
        note: "L-WATCH-001 CONFIRMED FIXED / canonical regression class.",
        status: "verified",
      },
    ],
    prevents: "False-positive 'new product' alerts from catch-up crawls and weak first-sightings.",
    cannotPrevent: "A source that is healthy in one region and blind in another (L-WATCH-006 remains OPEN). Official pages that are authoritative but too late for journalism (L-WATCH-003).",
    specimens: ["Timex 22-second launch cluster", "Apple IN 48 false positives", "FGT expiring-and-returning giveaway"],
    conceptIds: ["first-seen", "false-positive", "baseline"],
  },
  {
    id: "law-3",
    number: 3,
    title: "Health honesty",
    rule: "HTTP success without useful output is not healthy after policy cycles. Blocked sources surface BLOCKED. Scheduler invocation ≠ successful work; a failing scheduled unit must be observable in one query.",
    plainEnglish:
      "A green light that only means 'the process answered ping' can lie about the mission. A timer that rang is not proof anyone got out of bed. Empty-but-200 is a blank page, not a healthy press.",
    triggeringIncidentIds: ["inc-materialization", "inc-bankai", "inc-health-honesty"],
    historyIds: ["h-expansion-scars", "h-materialization", "h-def-m15", "h-fleet-laws", "h-gitignore-runtime"],
    evidence: [
      {
        id: "ev-l3",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 3. Specimens: SK hynix HOST-BLOCKED; smartwatch-soak exit-code journal 2026-08-21T20:12:44Z; Google consent-wall; FGT 200+0=ok.",
        status: "verified",
      },
    ],
    prevents: "Dashboards that stay green through silent outages, blocked sources, and zero-recall soaks.",
    cannotPrevent: "A legitimate zero (GIC-02) or NO_WORK_DUE (GIC-06). Those must remain distinguishable from MATERIALIZATION_GAP.",
    specimens: [
      "SK hynix HOST-BLOCKED matrix",
      "smartwatch failing timer lane (retired Phase 2A)",
      "KTW dashboard HEALTHY-iff-ever-succeeded",
      "FGT 200+0=ok",
    ],
    conceptIds: ["health-check", "dual-plane-health", "execution-liveness", "materialization-gap", "source-gap"],
  },
  {
    id: "law-4",
    number: 4,
    title: "Explicit event capability",
    rule: "emit_events/notify are explicit per-path contracts with fail-closed defaults; unknown reasons/categories never send.",
    plainEnglish:
      "If it is not on the list, it does not go through. Silence is safer than invention. A Clank that declares 'we do not notify' is honest; a path that notifies by accident is not.",
    triggeringIncidentIds: [],
    historyIds: ["h-fleet-laws"],
    evidence: [
      {
        id: "ev-l4",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 4. Specimens: casio_multi silent period; FGT subscription blackout. KTW/CTW-host/FPC-today satisfy by documented absence.",
        status: "verified",
      },
    ],
    prevents: "Unknown event reasons becoming Discord messages. Latent NotImplementedError transport.",
    cannotPrevent: "A correctly declared notify path that sends junk because novelty (Law 2) or baseline (Law 1) is wrong.",
    specimens: ["casio_multi silent period", "FGT subscription blackout", "smartwatch NotImplementedError latent transport"],
    conceptIds: ["allowlist", "contract", "outbox"],
  },
  {
    id: "law-5",
    number: 5,
    title: "Single scheduler and notification authority per lane",
    rule: "Exactly one enabled scheduling mechanism per Clank-lane; exactly one production notification channel set; experimental lanes structurally cannot reach production channels.",
    plainEnglish:
      "One clock, one megaphone, per notebook. A second timer is not a backup — it is a second author of history.",
    triggeringIncidentIds: ["inc-dual-scheduler"],
    historyIds: ["h-dual-scheduler", "h-fleet-laws", "h-tablet-local"],
    evidence: [
      {
        id: "ev-l5",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 5. Specimens: watch fcb5e91 ghost cron; smartwatch 2026-08-21 dual-lane journals; SemInt wrong-app installer.",
        status: "verified",
      },
    ],
    prevents: "Dual delivery, starved lanes, experimental soaks hitting production collectors, unobservable failing timers.",
    cannotPrevent: "A single authorized scheduler whose pre-exec fails (that's Law 3 / MATERIALIZATION_GAP). Deliberate multi-host isolation when DB+lock+volume are proven disjoint (feature-phone model).",
    specimens: ["watch fcb5e91 ghost cron", "smartwatch dual-lane 2026-08-21T21:06Z", "SemInt wrong-app installer"],
    conceptIds: ["scheduler", "cron", "systemd", "configuration-drift"],
  },
  {
    id: "law-6",
    number: 6,
    title: "Provenance",
    rule: "Every event carries run/source/code-revision; every deployment row carries exact SHA or artifact digest evidenced on host; missing evidence stays literal UNKNOWN.",
    plainEnglish:
      "The footnote is part of the sentence. Guessing the SHA because 'it is probably main' is a lie. UNKNOWN is allowed; a fabricated fingerprint is not.",
    triggeringIncidentIds: ["inc-deployed-sha", "inc-qc"],
    historyIds: ["h-portability", "h-ctw-dogfood", "h-fleet-laws", "h-current-gaps", "h-watch-unwired"],
    evidence: [
      {
        id: "ev-l6",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 6. Specimens: FGT pre-cec0346 hashed snapshots; SemInt d43481f claim-vs-ledger contradiction.",
        status: "verified",
      },
    ],
    prevents: "Treating GitHub main, host HEAD, and the running image as the same object. Reconstructing invocation intent from result shape.",
    cannotPrevent: "A host that is unreachable (Windows UNKNOWN). A SHA that is real but whose mission failed (BANKAI).",
    specimens: ["FGT pre-cec0346 hashed snapshots", "SemInt d43481f claim-vs-ledger contradiction", "KTW deployed-SHA env-fallback"],
    conceptIds: ["provenance", "runtime-provenance", "sha", "head-vs-deployed"],
  },
  {
    id: "law-7",
    number: 7,
    title: "Writer coordination",
    rule: "All writers of one SQLite database share one cross-process lock — dashboard paths included.",
    plainEnglish:
      "A lock is a talking stick for the database. Two speakers at once shred the minutes. A web button is a writer.",
    triggeringIncidentIds: ["inc-writer-lock"],
    historyIds: ["h-sqlite-authoritative", "h-fleet-laws", "h-watch-qc-race"],
    evidence: [
      {
        id: "ev-l7",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 7. Specimen: FGT 'DB Eradication' purge incident. Violators: FGT /api/run threading.Lock bypass; KTW feedback POST bypasses RunLock.",
        status: "verified",
      },
    ],
    prevents: "Dashboard threads and scheduled runs corrupting the same SQLite file.",
    cannotPrevent: "A single writer deleting the volume (that's survivability). Schema drift (GIC-14).",
    specimens: ["FGT DB Eradication purge incident", "L-WATCH-001 shared SQLite writer contention (DiagnosticBench)"],
    conceptIds: ["lock", "database", "race-condition", "sqlite-authoritative"],
  },
  {
    id: "law-8",
    number: 8,
    title: "Promotion gates",
    rule: "No source reaches production scheduling without soak evidence, an explicit promotion record, and rollback state; conversely every production-scheduled source appears in a promotion record.",
    plainEnglish:
      "You do not put a new reporter on the live desk because the trial issue 'looked fine'. There is a paper trail, a soak, and a way back. If it is live, it is in the book.",
    triggeringIncidentIds: ["inc-bankai"],
    historyIds: ["h-phase0-freeze", "h-fleet-laws", "h-watch-unwired"],
    evidence: [
      {
        id: "ev-l8",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Law 8. oem-radar bankai soaks operated outside any record until Phase 2A. Reference: KTW written policy + per-source yield log.",
        status: "verified",
      },
    ],
    prevents: "Silent promotion, promotion theater (approved-never-scheduled), soaks that cannot be compared or rolled back.",
    cannotPrevent: "Operator-run diagnostic probes outside promotion scope. A recorded soak whose metric is the wrong question (recall vs HTTP).",
    specimens: ["The Elec/ETNews promotions", "LG Display CONTINUE-EXPERIMENTAL", "Xiaomi KEEP_STAGING", "Apple-IN retirement", "oem-radar bankai soaks"],
    conceptIds: ["promotion-gate", "soak", "rollback"],
  },
  {
    id: "law-9",
    number: 9,
    title: "Deployment convergence (deferred)",
    rule: "A repository's default branch must never trail its own production checkout longer than one review cycle.",
    plainEnglish:
      "The map (GitHub main) and the terrain (the server) should not stay disagreed for long. Enforcement needs inventory machinery that did not exist at codification, so this is recorded as a candidate, not yet a binding law.",
    triggeringIncidentIds: ["inc-deployed-sha"],
    historyIds: ["h-portability", "h-current-gaps"],
    evidence: [
      {
        id: "ev-l9",
        kind: "doc",
        repo: "anil-ganti-nbc/clank-architecture",
        path: "FLEET_LAWS.md",
        note: "Deferred candidate. First violations: KTW main-behind-production (healed in Phase 2A by merge; host checkout still trails), SemInt host pre-heartbeat-fix.",
        status: "verified",
      },
    ],
    prevents: "Intended: long-lived secret forks where production is a SHA GitHub does not treat as trunk.",
    cannotPrevent: "A host that cannot be probed (fact stays UNKNOWN). Same-day deploy lag during an authorized rollout.",
    specimens: ["KTW main-behind-production", "SemInt host pre-heartbeat-fix"],
    deferred: true,
    conceptIds: ["deployment-drift", "head-vs-deployed", "main"],
  },
];
