import type { LedgerReview } from "../lib/handbook/schema.ts";

/** Human-review queue for all 28 history rows. Git/document-backed walk complete; live probe deferred. */
function r(row: LedgerReview): LedgerReview {
  return row;
}

export const LEDGER_REVIEWS: LedgerReview[] = [
  r({
    historyId: "h-github-account",
    currentConfidence: "verified",
    supportingArtefacts: ["GitHub user API created_at 2026-08-03T08:56:41Z"],
    verifiedClaims: ["Account anil-ganti-nbc exists; created_at as cited."],
    inferredClaims: ["Collectors needed a shared remote so agent sessions and hosts could push."],
    overreadRisk: "The why-clause is operator intent, not an API field. Event itself is solid.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-first-repos",
    currentConfidence: "verified",
    supportingArtefacts: ["repo created_at stamps", "clank-architecture@b91c156"],
    verifiedClaims: ["Four repos appear 2026-08-04 morning. Architecture baseline commit exists."],
    inferredClaims: ["Unification was hoped for before it was earned."],
    overreadRisk: "Motive is inferred from same-day unified-clank-platform + later ADR-0001. Do not treat motive as a Git fact.",
    openQuestions: ["Was unified-clank-platform ever deployed anywhere?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-consumer-clanks",
    currentConfidence: "verified",
    supportingArtefacts: ["archaeology report §3", "GitHub created_at re-fetched 2026-08-30: CTW/watch/smartwatch/smartphone/KTW"],
    verifiedClaims: [
      "Independent consumer/wire repos existed 8–10 Aug before Diagnostic (17 Aug) or Motherclank (22 Aug).",
      "GitHub created_at matches the 9–10 Aug window for CTW, smartphone, watch, smartwatch, KTW.",
    ],
    inferredClaims: [
      "Watch 14712d9 / Smartwatch 4c115ce are the identity of those Clanks or were running then.",
      "Copying a working SQLite collector was faster than a platform (motive).",
    ],
    overreadRisk:
      "Owner walk 2026-08-30: in-row split applied. Phase stays VERIFIED. Archaeology baselines are recoverability checkpoints (“before cloud migration”), not exam SHAs, not GitHub birth, not live. Do not put them in commits[]. Live SHA/host UNKNOWN.",
    openQuestions: ["Live collector SHA and host layout remain UNKNOWN (deferred reprobe)."],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-sqlite-authoritative",
    currentConfidence: "verified",
    supportingArtefacts: ["archaeology executive finding", "ADR-0002"],
    verifiedClaims: ["Docs say collectors are mostly SQLite-backed; Motherclank must not centralize DBs."],
    inferredClaims: ["“Every mature Clank persists observations in a local SQLite file” as a live host listing."],
    overreadRisk: "Owner walk 2026-08-30: archaeology “mostly SQLite-backed” stays VERIFIED. Do not treat “every” as a live filename census. Live DB filenames UNKNOWN for several lanes.",
    openQuestions: ["Live DB filenames still UNKNOWN for several lanes (Watch path, FGT live volume)."],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-portability",
    currentConfidence: "verified",
    supportingArtefacts: ["archaeology §3 portability phase", "git-resident Docker/unit templates preserved this campaign"],
    verifiedClaims: [
      "Repos gained Docker, backup scripts, unit examples, host handoffs in the 2026-08-08 through 2026-08-19 window (archaeology §3).",
      "FGT 473931e and Watch 12e8d3e / 938cc62 / f0b327a are named as commit citations in that report.",
      "2026-08-22 fleet.yaml inventory recorded Watch f0b327a and FGT cec0346.",
    ],
    inferredClaims: [
      "Those archaeology SHAs were the running images during 8–19 Aug.",
      "Those SHAs (or later HEADs) are the running images now.",
      "Git-resident Docker/unit/backup templates are enabled on the host.",
    ],
    overreadRisk:
      "Owner walk 2026-08-28: in-row split applied. Machinery-in-git stays VERIFIED. Archaeology-cited SHAs are not live deployed SHAs. Inventory 22 Aug is a dated snapshot, not a current probe. Later HEADs (Watch 9d812ed, FGT 45b47a5) stay out. Live deployed SHA UNKNOWN. Do not put 473931e / 12e8d3e / 938cc62 / f0b327a into commits[].",
    openQuestions: ["Which SHA (if any) is the running image on the host now?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-diagnostic-clank",
    currentConfidence: "verified",
    supportingArtefacts: ["repo created_at 2026-08-17T21:01:36Z", "ADR-0001", "fleet.yaml preserved"],
    verifiedClaims: ["Repo exists. Default branch diagnostic-clank-2026-08. fleet.yaml is the inventory artefact."],
    inferredClaims: [],
    overreadRisk: "Low. Do not infer Diagnostic Clank is a running supervisor — it is the adapter/inventory plane.",
    openQuestions: ["Is Diagnostic Clank itself deployed? Inventory says UNKNOWN."],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-expansion-scars",
    currentConfidence: "verified",
    supportingArtefacts: ["archaeology §3", "WATCH_EXPANSION_FAILURE_CORPUS.md L-WATCH-001"],
    verifiedClaims: ["Named failure classes exist as documents/specimens."],
    inferredClaims: ["Coverage pressure produced the failure classes."],
    overreadRisk: "The why is narrative. Specimens are real. Do not imply every listed source expansion was independently re-read this campaign.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-dual-scheduler",
    currentConfidence: "verified",
    supportingArtefacts: ["FLEET_LAWS.md Law 5 @ d046d54", "fleet.yaml soak row 2026-08-22", "soak timer templates still in smartwatch git"],
    verifiedClaims: [
      "Law 5 names dual scheduling as a failure class and the smartwatch specimen: systemd soak retired 2026-08-21T21:06Z, cron kept.",
      "2026-08-22 fleet.yaml lists smartwatch-hetzner-soak-timer-retired DISABLED (enabled: false; files retained unscheduled) beside a cron lane RUNNING staging at d987b66.",
    ],
    inferredClaims: [
      "The failing timer is still disabled on the live host today.",
      "Cron is the sole enabled scheduler on smartwatch now.",
      "Watch fcb5e91 and SemInt residuals were repaired in the same host action.",
    ],
    overreadRisk:
      "Owner walk 2026-08-28: in-row split applied. Historical scar stays VERIFIED. 21:06Z is law/inventory text, not live journalctl. Templates ≠ enabled. Later HEADs out. Current scheduler authority UNKNOWN. Do not teach 'one clock is authoritative now'.",
    openQuestions: ["What is the single enabled scheduler on smartwatch right now?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-phase0-freeze",
    currentConfidence: "verified",
    supportingArtefacts: ["ADR-0001", "NO_PROMOTION_POLICY.md", "ac83a2e merge"],
    verifiedClaims: ["Freeze documents and merge exist. fleet.yaml still has promotion_policy.frozen: true as of 2026-08-22 inventory."],
    inferredClaims: ["Hetzner and NAS were untouched by that merge."],
    overreadRisk: "Host-untouched is a merge-note claim, not a 2026-08-27 probe. Freeze still controlling is supported by inventory + freeze marker, not by live deploy state.",
    openQuestions: ["Has anyone promoted a source since Phase 0 despite the freeze?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-fleet-laws",
    currentConfidence: "verified",
    supportingArtefacts: ["FLEET_LAWS.md @ d046d54", "conformance/test_fleet_laws.py", "preserved copy hash 77d2abf2c975…"],
    verifiedClaims: ["Eight binding laws + deferred 9 committed 2026-08-21T21:27:48Z."],
    inferredClaims: [],
    overreadRisk: "Low.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-motherclank-born",
    currentConfidence: "verified",
    supportingArtefacts: ["ADR-0002 @ b341b0f", "motherclank created_at 2026-08-22T06:02:49Z", "install-user-timer.sh preserved"],
    verifiedClaims: [
      "ADR-0002 (b341b0f, 2026-08-22T05:52:04Z) established read-only supervisory design; M5 mutation deferred.",
      "motherclank repository created 2026-08-22T06:02:49Z, initially described as M0 read-only fleet harvester.",
    ],
    inferredClaims: [
      "A harvest timer is installed and firing on the host.",
      "M1–M4 were live stages on 22 Aug.",
      "Later repo HEAD is the deployed harvest SHA.",
    ],
    overreadRisk:
      "Owner walk 2026-08-28: in-row split applied. Architectural birth stays VERIFIED. Created ≠ actively supervising. Installer/unit templates ≠ timer enablement. Repo HEAD ≠ deployed SHA. Live SHA, process, timer, and host var/ remain UNKNOWN. Do not present M1–M4 as proven live on the birth date.",
    openQuestions: ["Is motherclank-harvest.timer enabled? Last harvest timestamp? Deployed Motherclank SHA?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-def-m15",
    currentConfidence: "verified",
    supportingArtefacts: ["DECISION_LEDGER.md DEF-M1.5 CLOSED", "diagnostic-clank 97b07ae cited"],
    verifiedClaims: ["Ledger row CLOSED the same day (b300b36). UUID-order defect is a named defect."],
    inferredClaims: [],
    overreadRisk: "Low for the defect. Do not claim current Motherclank synthesis is healthy without a harvest report.",
    openQuestions: ["Was 97b07ae the adapter SHA on the host at first harvest after the fix?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-materialization",
    currentConfidence: "verified",
    supportingArtefacts: ["DECISION_LEDGER INC-20260822-A", "INCIDENT_IMPACT_MAP Family A", "ADR-0008", "continuity seed INC-20260822-23"],
    verifiedClaims: [
      "Incident class MATERIALIZATION_GAP: scheduler activity visible, collector never became a running process.",
      "Preserved records attribute this to a pre-exec logging/permission failure (stash -u → logs/ root:root → cron redirect).",
      "OEM Radar lost no DB data (ledger). ADR-0008 + G1–G8 fixtures exist.",
    ],
    inferredClaims: ["Exact 09:59–10:06Z window and the ~36h duration as lived on the host."],
    overreadRisk:
      "Owner walk 2026-08-27: in-row split applied. Mechanism stays VERIFIED from git-resident decision/architecture records. Host timestamps/syslog remain INCOMPLETE. Do not re-promote ~09:59–10:06Z or ~36h as independently recovered.",
    openQuestions: ["Does journalctl still contain 2026-08-22 cron failures, or has it rotated?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-volume-loss",
    currentConfidence: "verified",
    supportingArtefacts: ["impact map Family B", "continuity seeds INC-20260823", "DATA_SURVIVABILITY §17.1 on h-act011"],
    verifiedClaims: [
      "Two named volumes destroyed (SW 21:22:08Z, FPC 21:22:11Z) as recorded in the impact map and seeds.",
      "SW RESTORED_HISTORY from 2026-08-18T20:50:37Z backup; FPC NEW_EPOCH fpc-epoch-2 at 21:36:11Z.",
      "SW ≈3d13h and FPC pre-epoch history are permanently missing. ACT-011 later proved scratch restore of remaining RPs (separate row).",
    ],
    inferredClaims: [
      "The original historical state was fully reconstructed.",
      "Motherclank var/ batches for states A–E survived.",
      "Restored volumes are still attached; scratch copies still exist; durable off-host backup exists.",
    ],
    overreadRisk:
      "Owner walk 2026-08-29: in-row split applied. Restore ≠ rewind. Instants are operator-provided, not live logs. ACT-011 stays on h-act011. var/ BLOCKED. Live path/epoch/backup UNKNOWN. Do not re-round 3d13h to 4 days.",
    openQuestions: ["Can var/ still be copied? Are the restored volume names still attached? Do ACT-011 scratch copies still exist?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-dau-worlds",
    currentConfidence: "verified",
    supportingArtefacts: ["dau-world-generator created_at 2026-08-23T19:57:17Z"],
    verifiedClaims: ["Repo created that day."],
    inferredClaims: ["Later absorbed natively into DAU (commit 5595073 cited in prior Handbook work)."],
    overreadRisk: "Absorption SHA was not re-fetched this campaign. Low risk if DAU still contains that commit.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-archaeology",
    currentConfidence: "verified",
    supportingArtefacts: ["audits/CLANK_FLEET_ARCHAEOLOGY_REPORT_2026-08-24.md hash 726c8b8e4638…", "ADR-0005"],
    verifiedClaims: ["Report exists. Inventory current through 2026-08-22. Did not operate collectors or inspect production DBs."],
    inferredClaims: [],
    overreadRisk: "Low. The report's own limit is the honest part.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-act011",
    currentConfidence: "verified",
    supportingArtefacts: ["DATA_SURVIVABILITY.md §17.1", "survivability-ACT011-verified-live.jsonl hash 84149d7c3adc…"],
    verifiedClaims: ["Two lanes on 2026-08-24: integrity_check=ok and disposable-volume restore passed. off_host_durable: false. Gate OPEN."],
    inferredClaims: ["Those scratch copies still exist now. Backup is scheduled. Layer C exists."],
    overreadRisk: "Owner walk 2026-08-30: dated scratch drill stays VERIFIED. Do not say 'we have backups'. Scratch existence today UNKNOWN. Durable off-host is DESIGNED ONLY.",
    openQuestions: ["Do the scratch files still exist? Any newer RP since 24 Aug?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-ctw-dogfood",
    currentConfidence: "verified",
    supportingArtefacts: ["CTW_ONBOARDING_DOGFOOD.md @ 64f92aa / 66cef4c", "7f977d6 operator finding + ONBOARDING.md patch"],
    verifiedClaims: [
      "14-step dogfood run against CTW; adapter-thinness (0 participant-specific core lines).",
      "Scorecard step 8 PASS on registry+refresh; FGT filename friction on the card.",
      "7f977d6 records the guessed-path finding and the three-way cross-check patch.",
    ],
    inferredClaims: [
      "The 24–25 Aug volume/path layout is still production.",
      "Live store volume name as of 2026-08-27 matches the dogfood finding.",
    ],
    overreadRisk:
      "Owner walk 2026-08-30: in-row split applied. Dogfooding exposed that the playbook was guessing where the system lived instead of proving it. Dated topology is not a permanent map. Live volume/SHA/scheduler UNKNOWN.",
    openQuestions: ["What is the CTW volume name right now? Is hourly cron still the live scheduler?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-gitignore-runtime",
    currentConfidence: "verified",
    supportingArtefacts: ["oem-radar@44ce1ac", "commit message cites INC-20260822-A pattern"],
    verifiedClaims: ["Commit exists; runtime logs/backups gitignored."],
    inferredClaims: ["This prevents a repeat on this repo if the same stash -u is used."],
    overreadRisk: "Low. Other checkouts may still have untracked runtime dirs.",
    openQuestions: ["Which other Clanks still keep logs/ inside the working tree on the host?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-watch-qc",
    currentConfidence: "verified",
    supportingArtefacts: ["ARCHITECTURE_NOTES_QC_VOLUME.md", "watch-clank@5de5329"],
    verifiedClaims: [
      "Catalogue-pass is an invocation fact (persisted max_items), never inferred from output cardinality.",
      "FIRST_SEEN_BY_CLANK is not novelty; weak FS (≤ 15) auto-deprioritized.",
      "Queue tiers are distinct: raw unreviewed ≠ default FIFO ≠ background.",
      "2026-08-26 snapshot values 639 / 580 / 41 are recorded in 5de5329 and the notes.",
    ],
    inferredClaims: ["Those queue counts are still the live queue."],
    overreadRisk:
      "Owner walk 2026-08-27: SHA pinned, numbers dated. Do not re-promote 639/580/41 as a live dashboard. Later Watch HEADs (ee3f34d, d4fda37, 9d812ed) are out of this incident narrative. Live queue UNKNOWN.",
    openQuestions: ["Live queue size on the host?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-watch-unwired",
    currentConfidence: "verified",
    supportingArtefacts: ["watch-clank@e7eeb3f", "test_production_wiring.py cited in the message"],
    verifiedClaims: ["Commit wires tissot + timex_uk into production invocation path."],
    inferredClaims: ["Hetzner deployment finding (Claude, 2026-08-25) as independently recovered host evidence. tissot/timex_uk timers are enabled now."],
    overreadRisk: "Owner walk 2026-08-30: commit e7eeb3f verified. 'Host deployment found the gap' is commit-message testimony, not a live unit listing. Live timer enablement UNKNOWN.",
    openQuestions: ["Are tissot/timex_uk timers enabled on the host?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-v03-freeze",
    currentConfidence: "verified",
    supportingArtefacts: ["FLEET_CAPABILITY_MATRIX.md freeze marker", "e9c4a2b closure hygiene"],
    verifiedClaims: ["v0.3 frozen 2026-08-25 in the matrix. e9c4a2b is a later freeze-marker commit."],
    inferredClaims: [],
    overreadRisk: "e9c4a2b date is 2026-08-26/27 closure hygiene, not the 25 Aug freeze itself. Residual scheduler-trace is matrix evidence.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-ai-workflow",
    currentConfidence: "verified",
    supportingArtefacts: ["AGENT_RULES.md @ 0a80fe6", "7f977d6 author Anil", "cd27668 author ox-alpha"],
    verifiedClaims: ["Commit metadata shows implementation-agent vs operator roles. AGENT_RULES.md exists."],
    inferredClaims: ["The tempting paste story is what this course exists to refuse — framing, not an event."],
    overreadRisk: "Low if read as process description. Do not claim a complete census of every agent session.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-handbook",
    currentConfidence: "verified",
    supportingArtefacts: ["repo created_at 2026-08-27T02:02:54Z", "3374e81", "8c267de", "cacfe56 content branch"],
    verifiedClaims: ["Repo and content-phase commits exist."],
    inferredClaims: [],
    overreadRisk: "The sentence 'this curriculum expansion is the content phase' is now historically incomplete — evidence-preservation follows. Add a new row rather than rewriting this one.",
    openQuestions: [],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-watch-qc-race",
    currentConfidence: "verified",
    supportingArtefacts: ["watch-clank@ee3f34d"],
    verifiedClaims: [
      "ee3f34d (2026-08-27T03:16:34Z) exists: catch IntegrityError, rollback losing insert, replay verdict as correction.",
      "UNIQUE(event_id) is a database guarantee; the application contract is the catch/replay path.",
    ],
    inferredClaims: [
      "An operator saw a raw IntegrityError/500 on the live host.",
      "Hetzner is running ee3f34d (or later d4fda37 / 9d812ed).",
    ],
    overreadRisk:
      "Owner walk 2026-08-28: in-row split applied. Pin ee3f34d. UNIQUE ≠ operator contract. Do not narrate a lived host 500. Later HEADs (d4fda37, 9d812ed) stay out. Live SHA UNKNOWN.",
    openQuestions: ["Deployed Watch SHA? Was a concurrent double-submit ever observed on the host?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-tablet-local",
    currentConfidence: "verified",
    supportingArtefacts: ["tablet-clank@a41d1e7"],
    verifiedClaims: ["QC layer + Windows launcher commit exists. Residual already says not a Hetzner membership change."],
    inferredClaims: [],
    overreadRisk: "Low if residual is kept visible. High if anyone drops the residual when teaching.",
    openQuestions: ["Live host membership still INTENTIONALLY_DORMANT?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-current-gaps",
    currentConfidence: "verified",
    supportingArtefacts: ["FLEET_CAPABILITY_MATRIX.md", "archaeology limit paragraph", "this campaign's INCOMPLETE live probe"],
    verifiedClaims: ["Live host SHA/backup cells remain UNKNOWN where not re-probed. This campaign did not close them."],
    inferredClaims: [],
    overreadRisk: "Do not let a prettier Evidence page upgrade this row. The campaign preserved git-resident artefacts; it did not replace a host probe.",
    openQuestions: ["See EVIDENCE_GAPS. Operator reprobe still deferred."],
    recommendedAction: "await-host-probe",
    recommendedConfidence: "verified",
  }),
  r({
    historyId: "h-evidence-preservation",
    currentConfidence: "verified",
    supportingArtefacts: ["docs/preserved/CAPTURE.json", "docs/EVIDENCE_PRESERVATION_MANIFEST.md", "hashed copies under docs/preserved/"],
    verifiedClaims: ["Git-resident artefacts were copied and hashed on 2026-08-27T08:14Z. Live host probe is INCOMPLETE. 27 prior rows were not silently rewritten."],
    inferredClaims: [],
    overreadRisk: "Do not read 'artefacts preserved' as 'live host state known'. Preservation of a systemd template is not proof the timer is enabled.",
    openQuestions: ["Will the operator run operator-reprobe.sh?"],
    recommendedAction: "keep",
    recommendedConfidence: "verified",
  }),
];
