import type { NextStep } from "../lib/handbook/schema.ts";

export const NEXT_STEPS: NextStep[] = [
  {
    id: "ns-operator-reprobe",
    title: "Run the read-only operator re-probe on Hetzner",
    impact: "high",
    urgency: "now",
    confidence: "verified",
    dependency: "SSH to ubuntu-4gb-hel1-1 (or current host). Script: docs/scripts/operator-reprobe.sh",
    scope: "small",
    doNow: true,
    body: "This is the only way to close Law 6 live SHA / scheduler / backup cells. Commit the redacted transcript. Do not restart services to inspect them.",
  },
  {
    id: "ns-mirror-git-artefacts",
    title: "Keep the preserved unit/compose/seed copies off the Hetzner failure domain",
    impact: "high",
    urgency: "now",
    confidence: "verified",
    dependency: "docs/preserved/ already in this handbook; push the evidence branch",
    scope: "small",
    doNow: true,
    body: "GitHub is an off-host copy of templates and seeds, not of live DBs. Still worth landing immediately so unit files cannot rotate away undocumented.",
  },
  {
    id: "ns-durable-offhost",
    title: "Implement Layer C for CRITICAL lanes (destination ADR + first copy)",
    impact: "high",
    urgency: "now",
    confidence: "verified",
    dependency: "Operator chooses NAS vs object storage. ACT-011 scratch is not Layer C.",
    scope: "medium",
    doNow: true,
    body: "Minimum viable: sqlite3 .backup of feature-phone epoch-2 and restored smartwatch, checksummed, copied off Hetzner, then restore-drill from THAT copy onto a labeled temp volume. Do not overwrite production.",
  },
  {
    id: "ns-motherclank-var-copy",
    title: "Read-only copy of Motherclank var/ if it still exists",
    impact: "high",
    urgency: "soon",
    confidence: "inferred",
    dependency: "Host access. Impact map listed BLOCKED.",
    scope: "small",
    doNow: true,
    body: "If batches intersecting 2026-08-22–24 remain, copy them off-host without rewriting lines. If rotated, record irrecoverable.",
  },
  {
    id: "ns-syslog-export",
    title: "Export journalctl for 2026-08-22–24 if still retained",
    impact: "medium",
    urgency: "soon",
    confidence: "incomplete",
    dependency: "Host journal retention. Likely rotated.",
    scope: "small",
    doNow: false,
    body: "Would let h-materialization host-facing timestamps be independently re-read. If gone, keep INCOMPLETE.",
  },
  {
    id: "ns-human-ledger-walk",
    title: "Owner walks the 27-row review queue",
    impact: "high",
    urgency: "soon",
    confidence: "verified",
    dependency: "docs/LEDGER_HUMAN_REVIEW_QUEUE.md / Evidence page",
    scope: "small",
    doNow: true,
    body: "No silent rewrite. Several rows should split git-verified facts from host-facing clauses (especially h-materialization, h-portability, h-act011 scratch vs durable).",
  },
  {
    id: "ns-watch-db-path",
    title: "Record Watch production DB path + backup cadence",
    impact: "high",
    urgency: "soon",
    confidence: "incomplete",
    dependency: "Host probe. CRITICAL class lane.",
    scope: "small",
    doNow: true,
    body: "Survivability matrix lists host path UNKNOWN. A CRITICAL lane with unknown path cannot be restored even in principle.",
  },
  {
    id: "ns-fgt-live-volume",
    title: "FGT REAL_STATE_VALIDATION — live volume filename + IMAGE_TAG",
    impact: "medium",
    urgency: "soon",
    confidence: "verified",
    dependency: "Host probe. CTW dogfood already showed this class of drift.",
    scope: "small",
    doNow: false,
    body: "Do not teach FGT from newsroom.db in the checkout. That copy is documented STALE.",
  },
  {
    id: "ns-motherclank-module",
    title: "Later teaching pass: dedicated Motherclank M0–M4 module",
    impact: "medium",
    urgency: "later",
    confidence: "verified",
    dependency: "Structure now in mod-motherclank-stages. Harvest reports still missing.",
    scope: "medium",
    doNow: false,
    body: "Enough verified structure exists for a later teaching pass. Do not expand into a giant curriculum until var/ or a fresh harvest report exists.",
  },
  {
    id: "ns-diagnostic-module",
    title: "Later teaching pass: Diagnostic Clank inventory/adapter module",
    impact: "medium",
    urgency: "later",
    confidence: "verified",
    dependency: "fleet.yaml preserved. Live Diagnostic deployment UNKNOWN.",
    scope: "medium",
    doNow: false,
    body: "Teach membership-as-registry now; defer a full adapter-authoring lab until a live harvest uses the Tablet adapter.",
  },
  {
    id: "ns-fleet-snapshot-teaching",
    title: "Treat current fleet cards as teaching-with-stale-notes, not as live health",
    impact: "high",
    urgency: "now",
    confidence: "verified",
    dependency: "None. Already labelled.",
    scope: "small",
    doNow: true,
    body: "The snapshot is trustworthy enough to teach Law 6, INTENTIONALLY_DORMANT, and ACT-011 limits. It is not trustworthy as a 2026-08-27 operations dashboard.",
  },
  {
    id: "ns-second-db-archaeology",
    title: "Second DB archaeology pass — only for ranked questions",
    impact: "medium",
    urgency: "later",
    confidence: "inferred",
    dependency: "Read-only host DB access + off-host copies of the files first.",
    scope: "large",
    doNow: false,
    body: "Justified questions: (1) FIRST_SEEN flood claims that still lack row-level proof; (2) epoch transitions SW restore vs FPC new-epoch; (3) Watch QC 639/580/41 if the live queue is the lesson. Not justified: a giant sweep, BANKAI recall (docs/tests suffice), Fleet Laws specimens already in conformance tests.",
  },
  {
    id: "ns-dau-launch",
    title: "DAU launch integration",
    impact: "low",
    urgency: "later",
    confidence: "verified",
    dependency: "Practice Labs ?practice= already exists. DAU is a separate app.",
    scope: "medium",
    doNow: false,
    body: "Do not fold Handbook into DAU. Do not assign mastery here. A later wiring pass is optional.",
  },
  {
    id: "ns-handbook-search",
    title: "Handbook search/filter (this campaign)",
    impact: "medium",
    urgency: "now",
    confidence: "verified",
    dependency: "Ships on /evidence and /history this campaign.",
    scope: "small",
    doNow: true,
    body: "Filter by epistemic state, Clank, date, law, concept. Confidence-audit view is the product; do not redesign chrome.",
  },
  {
    id: "ns-no-downgrade-mass",
    title: "Do not mass-downgrade or delete ledger rows",
    impact: "high",
    urgency: "now",
    confidence: "verified",
    dependency: "Human review queue.",
    scope: "small",
    doNow: true,
    body: "Recommended split/await-host on a few rows. No row should be removed. Host-facing clauses can be marked incomplete without throwing away git-verified events.",
  },
];

export const DO_NOT_DO_YET: string[] = [
  "Do not fill Law 6 UNKNOWNs from GitHub HEAD (watch d4fda37, tablet a41d1e7, smartwatch 7ed4d74, …).",
  "Do not treat Tablet a41d1e7 or Watch HEAD as production membership.",
  "Do not un-freeze promotion.",
  "Do not archive or decommission old repos.",
  "Do not fold Handbook into DAU or assign mastery.",
  "Do not add LLM grading of Explain It Back.",
  "Do not expand incidents first; evidence holes first.",
  "Do not destructively restore over production.",
  "Do not restart services merely to inspect them.",
  "Do not implement M5 mutation.",
  "Do not run a giant production-DB archaeology sweep.",
  "Do not copy App Builder auth/PWA chrome into the GitHub standalone handbook.",
  "Do not claim durable off-host survivability from ACT-011 scratch restores.",
  "Do not change live volume deletion permissions in this campaign (ACT-012 is a later audit).",
];
