import type { TimelineEvent } from "../lib/handbook/schema.ts";

export const TIMELINE: TimelineEvent[] = [
  {
    id: "t-account",
    date: "2026-08-03",
    title: "GitHub account created",
    body: "anil-ganti-nbc appears (created_at 2026-08-03T08:56:41Z). Idea becomes a remote that can hold repositories.",
    status: "verified",
    conceptIds: ["github", "repository", "origin"],
    evidenceIds: ["ev-gh-me"],
    historyId: "h-github-account",
  },
  {
    id: "t-first-repos",
    date: "2026-08-04",
    title: "First four Clank-related repositories",
    body: "oem-radar, free-game-tracker, unified-clank-platform, clank-architecture land the same morning. Architecture baseline b91c156.",
    status: "verified",
    conceptIds: ["repository", "commit", "collector"],
    evidenceIds: ["ev-oem-created", "ev-arch-init"],
    historyId: "h-first-repos",
  },
  {
    id: "t-fleet",
    date: "2026-08-09",
    title: "Consumer-device Clanks and wires proliferate",
    body: "Watch, smartwatch, smartphone, feature-phone, CTW, SemInt, then KTW (10 Aug). Many collectors, not yet a supervisor. SQLite is already the memory.",
    status: "verified",
    conceptIds: ["collector", "sqlite-authoritative"],
    evidenceIds: ["ev-archaeology-origin"],
    historyId: "h-consumer-clanks",
  },
  {
    id: "t-portability",
    date: "2026-08-12",
    title: "Portability: Docker, NAS, Hetzner",
    body: "Collectors leave the laptop. First real SHA-vs-runtime and volume-vs-checkout problems. Duplicate schedulers start to appear.",
    status: "verified",
    conceptIds: ["deployment", "container", "host", "head-vs-deployed"],
    evidenceIds: ["ev-port-phase"],
    historyId: "h-portability",
    lawIds: ["law-6"],
  },
  {
    id: "t-diagnostic",
    date: "2026-08-17",
    title: "Diagnostic Clank created",
    body: "Read-only diagnostics, inventory, adapter plane. Membership will later be a registry, not a directory listing.",
    status: "verified",
    conceptIds: ["diagnostic-clank", "contract"],
    evidenceIds: ["ev-dc-created"],
    historyId: "h-diagnostic-clank",
  },
  {
    id: "t-p0",
    date: "2026-08-21",
    title: "Phase 0 freeze and dual-scheduler repair",
    body: "Promotion freeze (ADR-0001). Smartwatch failing systemd soak timer retired 21:06Z; cron kept as sole scheduler (Law 5).",
    status: "verified",
    conceptIds: ["promotion-gate", "scheduler", "contract"],
    evidenceIds: ["ev-adr1-full", "ev-law5"],
    historyId: "h-phase0-freeze",
    lawIds: ["law-5", "law-8"],
  },
  {
    id: "t-laws",
    date: "2026-08-22",
    title: "Fleet Laws v1 and Motherclank M0",
    body: "Eight binding laws (d046d54) plus deferred Law 9. Motherclank created as read-only harvester (ADR-0002, b341b0f). DEF-M1.5 UUID false-STALE closed the same day.",
    status: "verified",
    conceptIds: ["motherclank", "fleet-law", "invariant", "first-seen"],
    evidenceIds: ["ev-laws-commit", "ev-adr2-commit"],
    historyId: "h-fleet-laws",
    lawIds: ["law-1", "law-2", "law-3", "law-4", "law-5", "law-6", "law-7", "law-8", "law-9"],
  },
  {
    id: "t-materialization",
    date: "2026-08-22",
    title: "INC-20260822-A: scheduler fired, process never started",
    body: "Decision/architecture records: stash -u recreated logs/ as root:root; cron redirects failed pre-exec. Named MATERIALIZATION_GAP (ADR-0008). Raw syslog and exact host timing not recovered.",
    status: "verified",
    conceptIds: ["materialization-gap", "scheduler", "untracked"],
    evidenceIds: ["ev-inc-a", "ev-gic-04"],
    historyId: "h-materialization",
    lawIds: ["law-3"],
  },
  {
    id: "t-volume",
    date: "2026-08-23",
    title: "INC-20260823 volume loss",
    body: "Destructive operator error deleted live volumes. Smartwatch restored from 2026-08-18 backup (~3d 13h gap). Feature-phone: no backup → NEW_EPOCH at 2026-08-23T21:36:11Z.",
    status: "verified",
    conceptIds: ["epoch", "volume", "blast-radius", "rollback"],
    evidenceIds: ["ev-inc-23", "ev-impact-b"],
    historyId: "h-volume-loss",
    lawIds: ["law-1"],
  },
  {
    id: "t-dau-worlds",
    date: "2026-08-23",
    title: "DAU World Generator vertical slice",
    body: "Causal seeded diagnostic worlds. Later absorbed natively into Dead Air University without deleting the provenance repo.",
    status: "verified",
    conceptIds: ["deterministic", "fixtures"],
    evidenceIds: ["ev-dwg-created"],
    historyId: "h-dau-worlds",
  },
  {
    id: "t-archaeology",
    date: "2026-08-24",
    title: "Archaeology report, ACT-011, CTW dogfood",
    body: "Adapter-first preservation ratified (ADR-0005). Live restore drills on Smartwatch and Feature Phone. CTW onboarding is the first real v0.3 dogfood. oem-radar gitignores runtime logs (44ce1ac).",
    status: "verified",
    conceptIds: ["dogfooding", "verification", "untracked"],
    evidenceIds: ["ev-arch-report", "ev-act011", "ev-ctw-dog"],
    historyId: "h-archaeology",
    lawIds: ["law-6"],
  },
  {
    id: "t-qc",
    date: "2026-08-25",
    title: "Watch QC flood, unwired collectors, v0.3 freeze",
    body: "Validation runs counted as catalogue passes. 2026-08-26 snapshot at watch-clank 5de5329: 639/580/41 (not live). Tissot/Timex UK existed in registry but not in the production invocation chain (e7eeb3f). Architecture v0.3 frozen: no speculative core redesign.",
    status: "verified",
    conceptIds: ["qc-flood", "runtime-provenance", "head-vs-deployed", "contract"],
    evidenceIds: ["ev-qc-vol", "ev-watch-unwired", "ev-freeze"],
    historyId: "h-watch-qc",
    lawIds: ["law-2"],
  },
  {
    id: "t-handbook",
    date: "2026-08-27",
    title: "Handbook created; collector repos still moving",
    body: "Clank Systems Handbook (3374e81). Watch QC race recovery (ee3f34d). Tablet repo gains local QC/Windows launcher (a41d1e7) — not a proven Hetzner membership change. Promotion still frozen. Survivability still incomplete.",
    status: "verified",
    conceptIds: ["operator-role", "race-condition", "head-vs-deployed"],
    evidenceIds: ["ev-hb-created", "ev-watch-qc-race", "ev-tablet-qc"],
    historyId: "h-handbook",
  },
];
