import type { TimelineEvent } from "../lib/handbook/schema.ts";

export const TIMELINE: TimelineEvent[] = [
  {
    id: "t-account",
    date: "2026-08-03",
    title: "GitHub account and first Clank repos",
    body: "anil-ganti-nbc appears; oem-radar, unified-clank-platform, clank-architecture follow within a day. Idea becomes repositories.",
    status: "verified",
    conceptIds: ["repository", "github"],
    evidenceIds: [],
  },
  {
    id: "t-fleet",
    date: "2026-08-09",
    title: "Consumer-device Clanks proliferate",
    body: "feature-phone, smartphone, smartwatch, watch-clank, chinese-tech-wire. Many collectors, not yet a supervisor.",
    status: "verified",
    conceptIds: ["process"],
    evidenceIds: [],
  },
  {
    id: "t-p0",
    date: "2026-08-21",
    title: "P0 freeze and ADR-0001",
    body: "Governance belongs in clank-architecture; control plane in diagnostic-clank. Promotion freeze proposed until Phase 0 is evidenced.",
    status: "verified",
    conceptIds: ["contract"],
    evidenceIds: ["ev-ledger-a"],
  },
  {
    id: "t-laws",
    date: "2026-08-22",
    title: "Fleet Laws v1 and Motherclank M0",
    body: "Eight binding laws (initialization, novelty, health honesty, allowlists, single scheduler, provenance, locks, promotion). Motherclank created as read-only harvester (ADR-0002).",
    status: "verified",
    conceptIds: ["motherclank", "invariant", "first-seen"],
    evidenceIds: ["ev-law1", "ev-law2"],
  },
  {
    id: "t-volume",
    date: "2026-08-23",
    title: "INC-20260823 volume loss",
    body: "Destructive operator error deleted live volumes. smartwatch restored from 2026-08-18 backup (~4 days missing). feature-phone: no backup → explicit NEW_EPOCH at 2026-08-23T21:36:11Z.",
    status: "verified",
    conceptIds: ["blast-radius", "rollback"],
    evidenceIds: [],
  },
  {
    id: "t-liveness",
    date: "2026-08-24",
    title: "MATERIALIZATION_GAP named",
    body: "INC-20260822-A: stash -u, root-owned logs/, cron pre-exec failure, ~36h silence. ADR-0008 / GIC-04.",
    status: "verified",
    conceptIds: ["scheduler", "root-cause"],
    evidenceIds: ["ev-ledger-a", "ev-gic-04"],
  },
  {
    id: "t-qc",
    date: "2026-08-25",
    title: "Watch QC flood",
    body: "Validation runs counted as catalogue passes. Notes on 2026-08-26 fix invocation provenance and queue accounting (639 / 580 / 41).",
    status: "verified",
    conceptIds: ["qc-flood", "runtime-provenance"],
    evidenceIds: ["ev-qc-vol"],
  },
  {
    id: "t-dau-worlds",
    date: "2026-08-23",
    title: "DAU World Generator vertical slice",
    body: "Causal seeded worlds (cpu-memory). Later absorbed natively into Dead Air University (5595073) without deleting the provenance repo.",
    status: "verified",
    conceptIds: ["deterministic", "fixtures"],
    evidenceIds: [],
  },
];
