/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BasicsRouteImport } from './routes/basics'
import { Route as BuiltRouteImport } from './routes/built'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as LabsIncidentIdRouteImport } from './routes/labs.$incidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicsRoute = BasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltRoute = BuiltRouteImport.update({
  id: '/built',
  path: '/built',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabsRoute,
} as any)
const LabsIncidentIdRoute = LabsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => LabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/basics': typeof BasicsRoute
  '/built': typeof BuiltRoute
  '/explain': typeof ExplainRoute
  '/glossary': typeof GlossaryRoute
  '/incidents': typeof IncidentsRoute
  '/labs': typeof LabsRouteWithChildren
  '/systems': typeof SystemsRoute
  '/labs/$incidentId': typeof LabsIncidentIdRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/basics': typeof BasicsRoute
  '/built': typeof BuiltRoute
  '/explain': typeof ExplainRoute
  '/glossary': typeof GlossaryRoute
  '/incidents': typeof IncidentsRoute
  '/systems': typeof SystemsRoute
  '/labs/$incidentId': typeof LabsIncidentIdRoute
  '/labs': typeof LabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/basics': typeof BasicsRoute
  '/built': typeof BuiltRoute
  '/explain': typeof ExplainRoute
  '/glossary': typeof GlossaryRoute
  '/incidents': typeof IncidentsRoute
  '/labs': typeof LabsRouteWithChildren
  '/systems': typeof SystemsRoute
  '/labs/$incidentId': typeof LabsIncidentIdRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/basics'
    | '/built'
    | '/explain'
    | '/glossary'
    | '/incidents'
    | '/labs'
    | '/systems'
    | '/labs/$incidentId'
    | '/labs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/basics'
    | '/built'
    | '/explain'
    | '/glossary'
    | '/incidents'
    | '/systems'
    | '/labs/$incidentId'
    | '/labs'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/basics'
    | '/built'
    | '/explain'
    | '/glossary'
    | '/incidents'
    | '/labs'
    | '/systems'
    | '/labs/$incidentId'
    | '/labs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BasicsRoute: typeof BasicsRoute
  BuiltRoute: typeof BuiltRoute
  ExplainRoute: typeof ExplainRoute
  GlossaryRoute: typeof GlossaryRoute
  IncidentsRoute: typeof IncidentsRoute
  LabsRoute: typeof LabsRouteWithChildren
  SystemsRoute: typeof SystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basics': {
      id: '/basics'
      path: '/basics'
      fullPath: '/basics'
      preLoaderRoute: typeof BasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built': {
      id: '/built'
      path: '/built'
      fullPath: '/built'
      preLoaderRoute: typeof BuiltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/$incidentId': {
      id: '/labs/$incidentId'
      path: '/$incidentId'
      fullPath: '/labs/$incidentId'
      preLoaderRoute: typeof LabsIncidentIdRouteImport
      parentRoute: typeof LabsRoute
    }
  }
}

interface LabsRouteChildren {
  LabsIncidentIdRoute: typeof LabsIncidentIdRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsIncidentIdRoute: LabsIncidentIdRoute,
  LabsIndexRoute: LabsIndexRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BasicsRoute: BasicsRoute,
  BuiltRoute: BuiltRoute,
  ExplainRoute: ExplainRoute,
  GlossaryRoute: GlossaryRoute,
  IncidentsRoute: IncidentsRoute,
  LabsRoute: LabsRouteWithChildren,
  SystemsRoute: SystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
